version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo Skipping gh-pages build
      
workflows:
  main:
    jobs:
      - build:
           filters:
             branches:
               ignore: gh-pages    
