OpenAPI::OAIApiRouter Class Reference
#include <OAIApiRouter.h>
Public Member Functions
OAIApiRouter ()
virtual ~OAIApiRouter ()
void setUpRoutes ()
void processRequest (QHttpEngine::Socket *socket)
void setOAIDefaultApiHandler (QSharedPointer< OAIDefaultApiHandler > handler)
Protected Member Functions
virtual void createApiHandlers ()
Private Member Functions
bool handleRequest (QHttpEngine::Socket *socket)
bool handleRequestAndExtractPathParam (QHttpEngine::Socket *socket)
QString fromQHttpEngineMethod (QHttpEngine::Socket::Method method)
QRegularExpressionMatch getRequestMatch (QString serverTemplatePath, QString requestPath)
Private Attributes
QMap< QString, std::function< void(QHttpEngine::Socket *)> > Routes
QMultiMap< QString, std::function< void(QHttpEngine::Socket *)> > RoutesWithPathParam
QSharedPointer< OAIDefaultApiHandler > mOAIDefaultApiHandler
Detailed Description
Definition at line 54 of file OAIApiRouter.h.
Constructor & Destructor Documentation
OAIApiRouter()
OpenAPI::OAIApiRouter::OAIApiRouter ()
Definition at line 24 of file OAIApiRouter.cpp.
                           {
    createApiHandlers();
}
References createApiHandlers().
 OAIApiRouter()
OpenAPI::OAIApiRouter::~OAIApiRouter () [virtual]
Definition at line 28 of file OAIApiRouter.cpp.
                           {
}
Member Function Documentation
createApiHandlers()
void OpenAPI::OAIApiRouter::createApiHandlers () [protected], [virtual]
Definition at line 32 of file OAIApiRouter.cpp.
                                     {
    mOAIDefaultApiHandler = QSharedPointer<OAIDefaultApiHandler>::create();
}
References mOAIDefaultApiHandler.
Referenced by OAIApiRouter().
fromQHttpEngineMethod()
QString OpenAPI::OAIApiRouter::fromQHttpEngineMethod (QHttpEngine::Socket::Method method) [inline], [private]
Definition at line 79 of file OAIApiRouter.h.
                                                                        {
        switch(method){
            case QHttpEngine::Socket::Method::OPTIONS:
                return QStringLiteral("OPTIONS");
            case QHttpEngine::Socket::Method::GET:
                return QStringLiteral("GET");
            case QHttpEngine::Socket::Method::HEAD:
                return QStringLiteral("HEAD");
            case QHttpEngine::Socket::Method::POST:
                return QStringLiteral("POST");
            case QHttpEngine::Socket::Method::PUT:
                return QStringLiteral("PUT");
            case QHttpEngine::Socket::Method::DELETE:
                return QStringLiteral("DELETE");
            case QHttpEngine::Socket::Method::TRACE:
                return QStringLiteral("TRACE");
            case QHttpEngine::Socket::Method::CONNECT:
                return QStringLiteral("CONNECT");
        }
        return QStringLiteral("");
    }
Referenced by handleRequest(), and handleRequestAndExtractPathParam().
getRequestMatch()
QRegularExpressionMatch OpenAPI::OAIApiRouter::getRequestMatch (QString serverTemplatePath, QString requestPath) [inline], [private]
Definition at line 101 of file OAIApiRouter.h.
                                                                                                   {
        QRegularExpression parExpr(R"(\{([^\/\s]+)\})");
        serverTemplatePath.replace(parExpr, R"((?<\1>[^\/\s]+))");
        serverTemplatePath.append("[\\/]?$");
        QRegularExpression pathExpr(serverTemplatePath);
        return pathExpr.match(requestPath);
    }
Referenced by handleRequestAndExtractPathParam().
handleRequest()
bool OpenAPI::OAIApiRouter::handleRequest (QHttpEngine::Socket * socket) [private]
Definition at line 75 of file OAIApiRouter.cpp.
                                                         {
    auto reqPath = QString("%1 %2").arg(fromQHttpEngineMethod(socket->method())).arg(socket->path()).toLower();
    if (Routes.contains(reqPath)) {
        Routes.value(reqPath).operator()(socket);
        return true;
    }
    return false;
}
References fromQHttpEngineMethod(), and Routes.
Referenced by processRequest().
handleRequestAndExtractPathParam()
bool OpenAPI::OAIApiRouter::handleRequestAndExtractPathParam (QHttpEngine::Socket * socket) [private]
Definition at line 84 of file OAIApiRouter.cpp.
                                                                            {
    auto reqPath = QString("%1 %2").arg(fromQHttpEngineMethod(socket->method())).arg(socket->path()).toLower();
    {
        auto completePath = QString("%1 %2").arg("GET").arg("/intersection_model/v1/get_conflict_lanelets/{link_lanelet_id}").toLower();
        if (reqPath.startsWith(completePath.leftRef(completePath.indexOf(QString("/{"))))) {
            QRegularExpressionMatch match = getRequestMatch(completePath, reqPath);
            if (match.hasMatch()){
                QString link_lanelet_id = match.captured(QString("link_lanelet_id").toLower());
                auto reqObj = new OAIDefaultApiRequest(socket, mOAIDefaultApiHandler);
                reqObj->getConflictLaneletsRequest(link_lanelet_id);
                return true;
            }
        }
    }
    return false;
}
References fromQHttpEngineMethod(), getRequestMatch(), and mOAIDefaultApiHandler.
Referenced by processRequest().
processRequest()
void OpenAPI::OAIApiRouter::processRequest (QHttpEngine::Socket * socket)
Definition at line 61 of file OAIApiRouter.cpp.
                                                          {
    if(handleRequest(socket)){
        return;
    }
    if(handleRequestAndExtractPathParam(socket)){
        return;
    }
    socket->setStatusCode(QHttpEngine::Socket::NotFound);
    if(socket->isOpen()){
        socket->writeHeaders();
        socket->close();
    }
}
References handleRequest(), and handleRequestAndExtractPathParam().
setOAIDefaultApiHandler()
void OpenAPI::OAIApiRouter::setOAIDefaultApiHandler (QSharedPointer< OAIDefaultApiHandler > handler)
Definition at line 37 of file OAIApiRouter.cpp.
                                                                                      {
    mOAIDefaultApiHandler = handler;
}
References mOAIDefaultApiHandler.
Referenced by IntersectionModelAPI::IntersectionModelRouter::IntersectionModelRouter().
setUpRoutes()
void OpenAPI::OAIApiRouter::setUpRoutes ()
Definition at line 41 of file OAIApiRouter.cpp.
                               {
    
    Routes.insert(QString("%1 %2").arg("GET").arg("/intersection_model/v1/info").toLower(), [this](QHttpEngine::Socket *socket) {
            auto reqObj = new OAIDefaultApiRequest(socket, mOAIDefaultApiHandler);
            reqObj->getIntersectionInfoRequest();
    });
    Routes.insert(QString("%1 %2").arg("GET").arg("/intersection_model/v1/departure_lanelets").toLower(), [this](QHttpEngine::Socket *socket) {
            auto reqObj = new OAIDefaultApiRequest(socket, mOAIDefaultApiHandler);
            reqObj->listDepartureLaneletsRequest();
    });
    Routes.insert(QString("%1 %2").arg("GET").arg("/intersection_model/v1/entry_lanelets").toLower(), [this](QHttpEngine::Socket *socket) {
            auto reqObj = new OAIDefaultApiRequest(socket, mOAIDefaultApiHandler);
            reqObj->listEntryLaneletsRequest();
    });
    Routes.insert(QString("%1 %2").arg("GET").arg("/intersection_model/v1/link_lanelets").toLower(), [this](QHttpEngine::Socket *socket) {
            auto reqObj = new OAIDefaultApiRequest(socket, mOAIDefaultApiHandler);
            reqObj->listLinkLaneletsRequest();
    });
}
References mOAIDefaultApiHandler, and Routes.
Member Data Documentation
mOAIDefaultApiHandler
QSharedPointer<OAIDefaultApiHandler> OpenAPI::OAIApiRouter::mOAIDefaultApiHandler [private]
Definition at line 73 of file OAIApiRouter.h.
Referenced by createApiHandlers(), handleRequestAndExtractPathParam(), setOAIDefaultApiHandler(), and setUpRoutes().
Routes
QMap<QString, std::function<void(QHttpEngine::Socket *)> > OpenAPI::OAIApiRouter::Routes [private]
Definition at line 66 of file OAIApiRouter.h.
Referenced by handleRequest(), and setUpRoutes().
RoutesWithPathParam
QMultiMap<QString, std::function<void(QHttpEngine::Socket *)> > OpenAPI::OAIApiRouter::RoutesWithPathParam [private]
Definition at line 67 of file OAIApiRouter.h.
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_server_api/src/handlers/OAIApiRouter.h
streets_utils/streets_api/intersection_server_api/src/handlers/OAIApiRouter.cpp