OpenAPI::OAILanelet_info Class Reference
#include <OAILanelet_info.h>
Public Member Functions
OAILanelet_info ()
OAILanelet_info (QString json)
~OAILanelet_info () override
QString asJson () const override
QJsonObject asJsonObject () const override
void fromJsonObject (QJsonObject json) override
void fromJson (QString jsonString) override
qint32 getId () const
void setId (const qint32 &id)
bool is_id_Set () const
bool is_id_Valid () const
double getSpeedLimit () const
void setSpeedLimit (const double &speed_limit)
bool is_speed_limit_Set () const
bool is_speed_limit_Valid () const
QList< qint32 > getConflictLaneletIds () const
void setConflictLaneletIds (const QList< qint32 > &conflict_lanelet_ids)
bool is_conflict_lanelet_ids_Set () const
bool is_conflict_lanelet_ids_Valid () const
double getLength () const
void setLength (const double &length)
bool is_length_Set () const
bool is_length_Valid () const
QString getTurnDirection () const
void setTurnDirection (const QString &turn_direction)
bool is_turn_direction_Set () const
bool is_turn_direction_Valid () const
qint32 getSignalGroupId () const
void setSignalGroupId (const qint32 &signal_group_id)
bool is_signal_group_id_Set () const
bool is_signal_group_id_Valid () const
QList< qint32 > getConnectingLaneletIds () const
void setConnectingLaneletIds (const QList< qint32 > &connecting_lanelet_ids)
bool is_connecting_lanelet_ids_Set () const
bool is_connecting_lanelet_ids_Valid () const
virtual bool isSet () const override
virtual bool isValid () const override
OAILanelet_info ()
OAILanelet_info (QString json)
~OAILanelet_info () override
QString asJson () const override
QJsonObject asJsonObject () const override
void fromJsonObject (QJsonObject json) override
void fromJson (QString jsonString) override
qint32 getId () const
void setId (const qint32 &id)
bool is_id_Set () const
bool is_id_Valid () const
double getSpeedLimit () const
void setSpeedLimit (const double &speed_limit)
bool is_speed_limit_Set () const
bool is_speed_limit_Valid () const
QList< qint32 > getConflictLaneletIds () const
void setConflictLaneletIds (const QList< qint32 > &conflict_lanelet_ids)
bool is_conflict_lanelet_ids_Set () const
bool is_conflict_lanelet_ids_Valid () const
double getLength () const
void setLength (const double &length)
bool is_length_Set () const
bool is_length_Valid () const
QString getTurnDirection () const
void setTurnDirection (const QString &turn_direction)
bool is_turn_direction_Set () const
bool is_turn_direction_Valid () const
qint32 getSignalGroupId () const
void setSignalGroupId (const qint32 &signal_group_id)
bool is_signal_group_id_Set () const
bool is_signal_group_id_Valid () const
QList< qint32 > getConnectingLaneletIds () const
void setConnectingLaneletIds (const QList< qint32 > &connecting_lanelet_ids)
bool is_connecting_lanelet_ids_Set () const
bool is_connecting_lanelet_ids_Valid () const
virtual bool isSet () const override
virtual bool isValid () const override
Private Member Functions
void initializeModel ()
void initializeModel ()
Private Attributes
qint32 id
bool m_id_isSet
bool m_id_isValid
double speed_limit
bool m_speed_limit_isSet
bool m_speed_limit_isValid
QList< qint32 > conflict_lanelet_ids
bool m_conflict_lanelet_ids_isSet
bool m_conflict_lanelet_ids_isValid
double length
bool m_length_isSet
bool m_length_isValid
QString turn_direction
bool m_turn_direction_isSet
bool m_turn_direction_isValid
qint32 signal_group_id
bool m_signal_group_id_isSet
bool m_signal_group_id_isValid
QList< qint32 > connecting_lanelet_ids
bool m_connecting_lanelet_ids_isSet
bool m_connecting_lanelet_ids_isValid
Detailed Description
Definition at line 31 of file OAILanelet_info.h.
Constructor & Destructor Documentation
OAILanelet_info() [1/4]
OpenAPI::OAILanelet_info::OAILanelet_info ()
Definition at line 28 of file OAILanelet_info.cpp.
                                 {
    this->initializeModel();
}
References initializeModel().
OAILanelet_info() [2/4]
OpenAPI::OAILanelet_info::OAILanelet_info (QString json)
Definition at line 23 of file OAILanelet_info.cpp.
                                             {
    this->initializeModel();
    this->fromJson(json);
}
References fromJson(), and initializeModel().
 OAILanelet_info() [1/2]
OpenAPI::OAILanelet_info::~OAILanelet_info () [override]
Definition at line 32 of file OAILanelet_info.cpp.
{}
OAILanelet_info() [3/4]
OpenAPI::OAILanelet_info::OAILanelet_info ()
OAILanelet_info() [4/4]
OpenAPI::OAILanelet_info::OAILanelet_info (QString json)
 OAILanelet_info() [2/2]
OpenAPI::OAILanelet_info::~OAILanelet_info () [override]
Member Function Documentation
asJson() [1/2]
QString OpenAPI::OAILanelet_info::asJson () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 88 of file OAILanelet_info.cpp.
                                      {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}
References asJsonObject().
asJson() [2/2]
QString OpenAPI::OAILanelet_info::asJson () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
asJsonObject() [1/2]
QJsonObject OpenAPI::OAILanelet_info::asJsonObject () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 95 of file OAILanelet_info.cpp.
                                                {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_speed_limit_isSet) {
        obj.insert(QString("speed_limit"), ::OpenAPI::toJsonValue(speed_limit));
    }
    if (conflict_lanelet_ids.size() > 0) {
        obj.insert(QString("conflict_lanelet_ids"), ::OpenAPI::toJsonValue(conflict_lanelet_ids));
    }
    if (m_length_isSet) {
        obj.insert(QString("length"), ::OpenAPI::toJsonValue(length));
    }
    if (m_turn_direction_isSet) {
        obj.insert(QString("turn_direction"), ::OpenAPI::toJsonValue(turn_direction));
    }
    if (m_signal_group_id_isSet) {
        obj.insert(QString("signal_group_id"), ::OpenAPI::toJsonValue(signal_group_id));
    }
    if (connecting_lanelet_ids.size() > 0) {
        obj.insert(QString("connecting_lanelet_ids"), ::OpenAPI::toJsonValue(connecting_lanelet_ids));
    }
    return obj;
}
References conflict_lanelet_ids, connecting_lanelet_ids, length, m_id_isSet, m_length_isSet, m_signal_group_id_isSet, m_speed_limit_isSet, m_turn_direction_isSet, signal_group_id, speed_limit, OpenAPI::toJsonValue(), and turn_direction.
Referenced by asJson().
asJsonObject() [2/2]
QJsonObject OpenAPI::OAILanelet_info::asJsonObject () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
fromJson() [1/2]
void OpenAPI::OAILanelet_info::fromJson (QString jsonString) [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 57 of file OAILanelet_info.cpp.
                                                 {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}
References fromJsonObject().
Referenced by OAILanelet_info().
fromJson() [2/2]
void OpenAPI::OAILanelet_info::fromJson (QString jsonString) [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
fromJsonObject() [1/2]
void OpenAPI::OAILanelet_info::fromJsonObject (QJsonObject json) [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 64 of file OAILanelet_info.cpp.
                                                     {
    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;
    m_speed_limit_isValid = ::OpenAPI::fromJsonValue(speed_limit, json[QString("speed_limit")]);
    m_speed_limit_isSet = !json[QString("speed_limit")].isNull() && m_speed_limit_isValid;
    m_conflict_lanelet_ids_isValid = ::OpenAPI::fromJsonValue(conflict_lanelet_ids, json[QString("conflict_lanelet_ids")]);
    m_conflict_lanelet_ids_isSet = !json[QString("conflict_lanelet_ids")].isNull() && m_conflict_lanelet_ids_isValid;
    m_length_isValid = ::OpenAPI::fromJsonValue(length, json[QString("length")]);
    m_length_isSet = !json[QString("length")].isNull() && m_length_isValid;
    m_turn_direction_isValid = ::OpenAPI::fromJsonValue(turn_direction, json[QString("turn_direction")]);
    m_turn_direction_isSet = !json[QString("turn_direction")].isNull() && m_turn_direction_isValid;
    m_signal_group_id_isValid = ::OpenAPI::fromJsonValue(signal_group_id, json[QString("signal_group_id")]);
    m_signal_group_id_isSet = !json[QString("signal_group_id")].isNull() && m_signal_group_id_isValid;
    m_connecting_lanelet_ids_isValid = ::OpenAPI::fromJsonValue(connecting_lanelet_ids, json[QString("connecting_lanelet_ids")]);
    m_connecting_lanelet_ids_isSet = !json[QString("connecting_lanelet_ids")].isNull() && m_connecting_lanelet_ids_isValid;
}
References conflict_lanelet_ids, connecting_lanelet_ids, OpenAPI::fromJsonValue(), length, m_conflict_lanelet_ids_isSet, m_conflict_lanelet_ids_isValid, m_connecting_lanelet_ids_isSet, m_connecting_lanelet_ids_isValid, m_id_isSet, m_id_isValid, m_length_isSet, m_length_isValid, m_signal_group_id_isSet, m_signal_group_id_isValid, m_speed_limit_isSet, m_speed_limit_isValid, m_turn_direction_isSet, m_turn_direction_isValid, signal_group_id, speed_limit, and turn_direction.
Referenced by fromJson().
fromJsonObject() [2/2]
void OpenAPI::OAILanelet_info::fromJsonObject (QJsonObject json) [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
getConflictLaneletIds() [1/2]
QList< qint32 > OpenAPI::OAILanelet_info::getConflictLaneletIds () const
Definition at line 153 of file OAILanelet_info.cpp.
                                                           {
    return conflict_lanelet_ids;
}
References conflict_lanelet_ids.
Referenced by streets_vehicle_scheduler::all_stop_vehicle_scheduler::get_latest_conflicting().
getConflictLaneletIds() [2/2]
QList< qint32 > OpenAPI::OAILanelet_info::getConflictLaneletIds () const
getConnectingLaneletIds() [1/2]
QList< qint32 > OpenAPI::OAILanelet_info::getConnectingLaneletIds () const
Definition at line 217 of file OAILanelet_info.cpp.
                                                             {
    return connecting_lanelet_ids;
}
References connecting_lanelet_ids.
getConnectingLaneletIds() [2/2]
QList< qint32 > OpenAPI::OAILanelet_info::getConnectingLaneletIds () const
getId() [1/2]
qint32 OpenAPI::OAILanelet_info::getId () const
Definition at line 121 of file OAILanelet_info.cpp.
                                    {
    return id;
}
References id.
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_et(), streets_vehicle_scheduler::vehicle_scheduler::get_entry_lanelet_info(), streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_evs(), and streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_evs().
getId() [2/2]
qint32 OpenAPI::OAILanelet_info::getId () const
getLength() [1/2]
double OpenAPI::OAILanelet_info::getLength () const
Definition at line 169 of file OAILanelet_info.cpp.
                                        {
    return length;
}
References length.
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_clearance_time(), and streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_clearance_time().
getLength() [2/2]
double OpenAPI::OAILanelet_info::getLength () const
getSignalGroupId() [1/2]
qint32 OpenAPI::OAILanelet_info::getSignalGroupId () const
Definition at line 201 of file OAILanelet_info.cpp.
                                               {
    return signal_group_id;
}
References signal_group_id.
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::find_movement_state_for_lane(), and streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_evs().
getSignalGroupId() [2/2]
qint32 OpenAPI::OAILanelet_info::getSignalGroupId () const
getSpeedLimit() [1/2]
double OpenAPI::OAILanelet_info::getSpeedLimit () const
Definition at line 137 of file OAILanelet_info.cpp.
                                            {
    return speed_limit;
}
References speed_limit.
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_earliest_entering_time(), streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_clearance_time(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_clearance_time(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_delta_x_prime(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_earliest_time_to_stop_bar(), and streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_et().
getSpeedLimit() [2/2]
double OpenAPI::OAILanelet_info::getSpeedLimit () const
getTurnDirection() [1/2]
QString OpenAPI::OAILanelet_info::getTurnDirection () const
Definition at line 185 of file OAILanelet_info.cpp.
                                                {
    return turn_direction;
}
References turn_direction.
getTurnDirection() [2/2]
QString OpenAPI::OAILanelet_info::getTurnDirection () const
initializeModel() [1/2]
void OpenAPI::OAILanelet_info::initializeModel () [private]
Definition at line 34 of file OAILanelet_info.cpp.
                                      {
    m_id_isSet = false;
    m_id_isValid = false;
    m_speed_limit_isSet = false;
    m_speed_limit_isValid = false;
    m_conflict_lanelet_ids_isSet = false;
    m_conflict_lanelet_ids_isValid = false;
    m_length_isSet = false;
    m_length_isValid = false;
    m_turn_direction_isSet = false;
    m_turn_direction_isValid = false;
    m_signal_group_id_isSet = false;
    m_signal_group_id_isValid = false;
    m_connecting_lanelet_ids_isSet = false;
    m_connecting_lanelet_ids_isValid = false;
}
References m_conflict_lanelet_ids_isSet, m_conflict_lanelet_ids_isValid, m_connecting_lanelet_ids_isSet, m_connecting_lanelet_ids_isValid, m_id_isSet, m_id_isValid, m_length_isSet, m_length_isValid, m_signal_group_id_isSet, m_signal_group_id_isValid, m_speed_limit_isSet, m_speed_limit_isValid, m_turn_direction_isSet, and m_turn_direction_isValid.
Referenced by OAILanelet_info().
initializeModel() [2/2]
void OpenAPI::OAILanelet_info::initializeModel () [private]
is_conflict_lanelet_ids_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_conflict_lanelet_ids_Set () const
Definition at line 161 of file OAILanelet_info.cpp.
                                                       {
    return m_conflict_lanelet_ids_isSet;
}
References m_conflict_lanelet_ids_isSet.
is_conflict_lanelet_ids_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_conflict_lanelet_ids_Set () const
is_conflict_lanelet_ids_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_conflict_lanelet_ids_Valid () const
Definition at line 165 of file OAILanelet_info.cpp.
                                                         {
    return m_conflict_lanelet_ids_isValid;
}
References m_conflict_lanelet_ids_isValid.
is_conflict_lanelet_ids_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_conflict_lanelet_ids_Valid () const
is_connecting_lanelet_ids_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_connecting_lanelet_ids_Set () const
Definition at line 225 of file OAILanelet_info.cpp.
                                                         {
    return m_connecting_lanelet_ids_isSet;
}
References m_connecting_lanelet_ids_isSet.
is_connecting_lanelet_ids_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_connecting_lanelet_ids_Set () const
is_connecting_lanelet_ids_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_connecting_lanelet_ids_Valid () const
Definition at line 229 of file OAILanelet_info.cpp.
                                                           {
    return m_connecting_lanelet_ids_isValid;
}
References m_connecting_lanelet_ids_isValid.
is_connecting_lanelet_ids_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_connecting_lanelet_ids_Valid () const
is_id_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_id_Set () const
Definition at line 129 of file OAILanelet_info.cpp.
                                     {
    return m_id_isSet;
}
References m_id_isSet.
is_id_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_id_Set () const
is_id_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_id_Valid () const
Definition at line 133 of file OAILanelet_info.cpp.
                                       {
    return m_id_isValid;
}
References m_id_isValid.
is_id_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_id_Valid () const
is_length_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_length_Set () const
Definition at line 177 of file OAILanelet_info.cpp.
                                         {
    return m_length_isSet;
}
References m_length_isSet.
is_length_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_length_Set () const
is_length_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_length_Valid () const
Definition at line 181 of file OAILanelet_info.cpp.
                                           {
    return m_length_isValid;
}
References m_length_isValid.
is_length_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_length_Valid () const
is_signal_group_id_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_signal_group_id_Set () const
Definition at line 209 of file OAILanelet_info.cpp.
                                                  {
    return m_signal_group_id_isSet;
}
References m_signal_group_id_isSet.
is_signal_group_id_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_signal_group_id_Set () const
is_signal_group_id_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_signal_group_id_Valid () const
Definition at line 213 of file OAILanelet_info.cpp.
                                                    {
    return m_signal_group_id_isValid;
}
References m_signal_group_id_isValid.
is_signal_group_id_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_signal_group_id_Valid () const
is_speed_limit_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_speed_limit_Set () const
Definition at line 145 of file OAILanelet_info.cpp.
                                              {
    return m_speed_limit_isSet;
}
References m_speed_limit_isSet.
is_speed_limit_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_speed_limit_Set () const
is_speed_limit_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_speed_limit_Valid () const
Definition at line 149 of file OAILanelet_info.cpp.
                                                {
    return m_speed_limit_isValid;
}
References m_speed_limit_isValid.
is_speed_limit_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_speed_limit_Valid () const
is_turn_direction_Set() [1/2]
bool OpenAPI::OAILanelet_info::is_turn_direction_Set () const
Definition at line 193 of file OAILanelet_info.cpp.
                                                 {
    return m_turn_direction_isSet;
}
References m_turn_direction_isSet.
is_turn_direction_Set() [2/2]
bool OpenAPI::OAILanelet_info::is_turn_direction_Set () const
is_turn_direction_Valid() [1/2]
bool OpenAPI::OAILanelet_info::is_turn_direction_Valid () const
Definition at line 197 of file OAILanelet_info.cpp.
                                                   {
    return m_turn_direction_isValid;
}
References m_turn_direction_isValid.
is_turn_direction_Valid() [2/2]
bool OpenAPI::OAILanelet_info::is_turn_direction_Valid () const
isSet() [1/2]
bool OpenAPI::OAILanelet_info::isSet () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 233 of file OAILanelet_info.cpp.
                                  {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }
        if (m_speed_limit_isSet) {
            isObjectUpdated = true;
            break;
        }
        if (conflict_lanelet_ids.size() > 0) {
            isObjectUpdated = true;
            break;
        }
        if (m_length_isSet) {
            isObjectUpdated = true;
            break;
        }
        if (m_turn_direction_isSet) {
            isObjectUpdated = true;
            break;
        }
        if (m_signal_group_id_isSet) {
            isObjectUpdated = true;
            break;
        }
        if (connecting_lanelet_ids.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}
References conflict_lanelet_ids, connecting_lanelet_ids, m_id_isSet, m_length_isSet, m_signal_group_id_isSet, m_speed_limit_isSet, and m_turn_direction_isSet.
isSet() [2/2]
virtual bool OpenAPI::OAILanelet_info::isSet () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
isValid() [1/2]
bool OpenAPI::OAILanelet_info::isValid () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
Definition at line 274 of file OAILanelet_info.cpp.
                                    {
    // only required properties are required for the object to be considered valid
    return true;
}
isValid() [2/2]
virtual bool OpenAPI::OAILanelet_info::isValid () const [override], [virtual]
Reimplemented from OpenAPI::OAIObject.
setConflictLaneletIds() [1/2]
void OpenAPI::OAILanelet_info::setConflictLaneletIds (const QList< qint32 > & conflict_lanelet_ids)
Definition at line 156 of file OAILanelet_info.cpp.
                                                                                     {
    this->conflict_lanelet_ids = conflict_lanelet_ids;
    this->m_conflict_lanelet_ids_isSet = true;
}
References conflict_lanelet_ids, and m_conflict_lanelet_ids_isSet.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo().
setConflictLaneletIds() [2/2]
void OpenAPI::OAILanelet_info::setConflictLaneletIds (const QList< qint32 > & conflict_lanelet_ids)
setConnectingLaneletIds() [1/2]
void OpenAPI::OAILanelet_info::setConnectingLaneletIds (const QList< qint32 > & connecting_lanelet_ids)
Definition at line 220 of file OAILanelet_info.cpp.
                                                                                         {
    this->connecting_lanelet_ids = connecting_lanelet_ids;
    this->m_connecting_lanelet_ids_isSet = true;
}
References connecting_lanelet_ids, and m_connecting_lanelet_ids_isSet.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo(), and IntersectionModelAPI::IntersectionModelHandler::listEntryLanelets().
setConnectingLaneletIds() [2/2]
void OpenAPI::OAILanelet_info::setConnectingLaneletIds (const QList< qint32 > & connecting_lanelet_ids)
setId() [1/2]
void OpenAPI::OAILanelet_info::setId (const qint32 & id)
Definition at line 124 of file OAILanelet_info.cpp.
                                            {
    this->id = id;
    this->m_id_isSet = true;
}
References id, and m_id_isSet.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getConflictLanelets(), IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo(), IntersectionModelAPI::IntersectionModelHandler::listDepartureLanelets(), IntersectionModelAPI::IntersectionModelHandler::listEntryLanelets(), and IntersectionModelAPI::IntersectionModelHandler::listLinkLanelets().
setId() [2/2]
void OpenAPI::OAILanelet_info::setId (const qint32 & id)
setLength() [1/2]
void OpenAPI::OAILanelet_info::setLength (const double & length)
Definition at line 172 of file OAILanelet_info.cpp.
                                                    {
    this->length = length;
    this->m_length_isSet = true;
}
References length, and m_length_isSet.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getConflictLanelets(), IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo(), IntersectionModelAPI::IntersectionModelHandler::listDepartureLanelets(), IntersectionModelAPI::IntersectionModelHandler::listEntryLanelets(), and IntersectionModelAPI::IntersectionModelHandler::listLinkLanelets().
setLength() [2/2]
void OpenAPI::OAILanelet_info::setLength (const double & length)
setSignalGroupId() [1/2]
void OpenAPI::OAILanelet_info::setSignalGroupId (const qint32 & signal_group_id)
Definition at line 204 of file OAILanelet_info.cpp.
                                                                    {
    this->signal_group_id = signal_group_id;
    this->m_signal_group_id_isSet = true;
}
References m_signal_group_id_isSet, and signal_group_id.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getConflictLanelets(), IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo(), and IntersectionModelAPI::IntersectionModelHandler::listLinkLanelets().
setSignalGroupId() [2/2]
void OpenAPI::OAILanelet_info::setSignalGroupId (const qint32 & signal_group_id)
setSpeedLimit() [1/2]
void OpenAPI::OAILanelet_info::setSpeedLimit (const double & speed_limit)
Definition at line 140 of file OAILanelet_info.cpp.
                                                             {
    this->speed_limit = speed_limit;
    this->m_speed_limit_isSet = true;
}
References m_speed_limit_isSet, and speed_limit.
Referenced by IntersectionModelAPI::IntersectionModelHandler::getConflictLanelets(), IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo(), IntersectionModelAPI::IntersectionModelHandler::listDepartureLanelets(), IntersectionModelAPI::IntersectionModelHandler::listEntryLanelets(), and IntersectionModelAPI::IntersectionModelHandler::listLinkLanelets().
setSpeedLimit() [2/2]
void OpenAPI::OAILanelet_info::setSpeedLimit (const double & speed_limit)
setTurnDirection() [1/2]
void OpenAPI::OAILanelet_info::setTurnDirection (const QString & turn_direction)
Definition at line 188 of file OAILanelet_info.cpp.
                                                                    {
    this->turn_direction = turn_direction;
    this->m_turn_direction_isSet = true;
}
References m_turn_direction_isSet, and turn_direction.
setTurnDirection() [2/2]
void OpenAPI::OAILanelet_info::setTurnDirection (const QString & turn_direction)
Member Data Documentation
conflict_lanelet_ids
QList< qint32 > OpenAPI::OAILanelet_info::conflict_lanelet_ids [private]
Definition at line 91 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getConflictLaneletIds(), isSet(), and setConflictLaneletIds().
connecting_lanelet_ids
QList< qint32 > OpenAPI::OAILanelet_info::connecting_lanelet_ids [private]
Definition at line 107 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getConnectingLaneletIds(), isSet(), and setConnectingLaneletIds().
id
qint32 OpenAPI::OAILanelet_info::id [private]
Definition at line 83 of file OAILanelet_info.h.
Referenced by getId(), and setId().
length
double OpenAPI::OAILanelet_info::length [private]
Definition at line 95 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getLength(), and setLength().
m_conflict_lanelet_ids_isSet
bool OpenAPI::OAILanelet_info::m_conflict_lanelet_ids_isSet [private]
Definition at line 92 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), is_conflict_lanelet_ids_Set(), and setConflictLaneletIds().
m_conflict_lanelet_ids_isValid
bool OpenAPI::OAILanelet_info::m_conflict_lanelet_ids_isValid [private]
Definition at line 93 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_conflict_lanelet_ids_Valid().
m_connecting_lanelet_ids_isSet
bool OpenAPI::OAILanelet_info::m_connecting_lanelet_ids_isSet [private]
Definition at line 108 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), is_connecting_lanelet_ids_Set(), and setConnectingLaneletIds().
m_connecting_lanelet_ids_isValid
bool OpenAPI::OAILanelet_info::m_connecting_lanelet_ids_isValid [private]
Definition at line 109 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_connecting_lanelet_ids_Valid().
m_id_isSet
bool OpenAPI::OAILanelet_info::m_id_isSet [private]
Definition at line 84 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), initializeModel(), is_id_Set(), isSet(), and setId().
m_id_isValid
bool OpenAPI::OAILanelet_info::m_id_isValid [private]
Definition at line 85 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_id_Valid().
m_length_isSet
bool OpenAPI::OAILanelet_info::m_length_isSet [private]
Definition at line 96 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), initializeModel(), is_length_Set(), isSet(), and setLength().
m_length_isValid
bool OpenAPI::OAILanelet_info::m_length_isValid [private]
Definition at line 97 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_length_Valid().
m_signal_group_id_isSet
bool OpenAPI::OAILanelet_info::m_signal_group_id_isSet [private]
Definition at line 104 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), initializeModel(), is_signal_group_id_Set(), isSet(), and setSignalGroupId().
m_signal_group_id_isValid
bool OpenAPI::OAILanelet_info::m_signal_group_id_isValid [private]
Definition at line 105 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_signal_group_id_Valid().
m_speed_limit_isSet
bool OpenAPI::OAILanelet_info::m_speed_limit_isSet [private]
Definition at line 88 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), initializeModel(), is_speed_limit_Set(), isSet(), and setSpeedLimit().
m_speed_limit_isValid
bool OpenAPI::OAILanelet_info::m_speed_limit_isValid [private]
Definition at line 89 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_speed_limit_Valid().
m_turn_direction_isSet
bool OpenAPI::OAILanelet_info::m_turn_direction_isSet [private]
Definition at line 100 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), initializeModel(), is_turn_direction_Set(), isSet(), and setTurnDirection().
m_turn_direction_isValid
bool OpenAPI::OAILanelet_info::m_turn_direction_isValid [private]
Definition at line 101 of file OAILanelet_info.h.
Referenced by fromJsonObject(), initializeModel(), and is_turn_direction_Valid().
signal_group_id
qint32 OpenAPI::OAILanelet_info::signal_group_id [private]
Definition at line 103 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getSignalGroupId(), and setSignalGroupId().
speed_limit
double OpenAPI::OAILanelet_info::speed_limit [private]
Definition at line 87 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getSpeedLimit(), and setSpeedLimit().
turn_direction
QString OpenAPI::OAILanelet_info::turn_direction [private]
Definition at line 99 of file OAILanelet_info.h.
Referenced by asJsonObject(), fromJsonObject(), getTurnDirection(), and setTurnDirection().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAILanelet_info.h
streets_utils/streets_api/intersection_server_api/src/models/OAILanelet_info.h
streets_utils/streets_api/intersection_client_api/OAILanelet_info.cpp
streets_utils/streets_api/intersection_server_api/src/models/OAILanelet_info.cpp