OpenAPI::OAISerializerSettings Class Reference
Classes
struct CustomDateTimeFormat
Static Public Member Functions
static CustomDateTimeFormat getCustomDateTimeFormat ()
static void setDateTimeFormatString (const QString &dtFormat)
static void setDateTimeFormatEnum (const Qt::DateFormat &dtFormat)
static OAISerializerSettings * getInstance ()
static void setDateTimeFormat (const QString &dtFormat)
static QString getDateTimeFormat ()
static OAISerializerSettings * getInstance ()
Private Member Functions
OAISerializerSettings ()
OAISerializerSettings ()
Private Attributes
CustomDateTimeFormat customDateTimeFormat
QString dateTimeFormat
Static Private Attributes
static OAISerializerSettings * instance = nullptr
Detailed Description
Definition at line 18 of file OAIHelpers.cpp.
Constructor & Destructor Documentation
OAISerializerSettings() [1/2]
OpenAPI::OAISerializerSettings::OAISerializerSettings () [inline], [explicit], [private]
Definition at line 51 of file OAIHelpers.cpp.
                                    {
        instance = this;
        customDateTimeFormat.isStringSet = false;
        customDateTimeFormat.isEnumSet = false;
    }
References customDateTimeFormat, instance, OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isEnumSet, and OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isStringSet.
Referenced by getInstance().
OAISerializerSettings() [2/2]
OpenAPI::OAISerializerSettings::OAISerializerSettings () [inline], [explicit], [private]
Definition at line 33 of file OAIHelpers.cpp.
                                    {
        instance = this;
        dateTimeFormat.clear();
    }
References dateTimeFormat, and instance.
Member Function Documentation
getCustomDateTimeFormat()
static CustomDateTimeFormat OpenAPI::OAISerializerSettings::getCustomDateTimeFormat () [inline], [static]
Definition at line 27 of file OAIHelpers.cpp.
                                                          {
        return getInstance()->customDateTimeFormat;
    }
References customDateTimeFormat, and getInstance().
Referenced by OpenAPI::fromJsonValue(), and OpenAPI::toJsonValue().
getDateTimeFormat()
static QString OpenAPI::OAISerializerSettings::getDateTimeFormat () [inline], [static]
Definition at line 23 of file OAIHelpers.cpp.
                                       {
        return getInstance()->dateTimeFormat;
    }
References dateTimeFormat, and getInstance().
getInstance() [1/2]
static OAISerializerSettings * OpenAPI::OAISerializerSettings::getInstance () [inline], [static]
Definition at line 43 of file OAIHelpers.cpp.
                                               {
        if(instance == nullptr){
            instance = new OAISerializerSettings();
        }
        return instance;
    }
References OAISerializerSettings(), and instance.
Referenced by OpenAPI::fromJsonValue(), OpenAPI::fromStringValue(), getCustomDateTimeFormat(), getDateTimeFormat(), setDateTimeFormat(), setDateTimeFormatEnum(), setDateTimeFormatString(), OpenAPI::toJsonValue(), and OpenAPI::toStringValue().
getInstance() [2/2]
static OAISerializerSettings * OpenAPI::OAISerializerSettings::getInstance () [inline], [static]
Definition at line 26 of file OAIHelpers.cpp.
                                               {
        if(instance == nullptr){
            instance = new OAISerializerSettings();
        }
        return instance;
    }
References OAISerializerSettings(), and instance.
setDateTimeFormat()
static void OpenAPI::OAISerializerSettings::setDateTimeFormat (const QString & dtFormat) [inline], [static]
Definition at line 20 of file OAIHelpers.cpp.
                                                           {
        getInstance()->dateTimeFormat = dtFormat;
    }
References dateTimeFormat, and getInstance().
setDateTimeFormatEnum()
static void OpenAPI::OAISerializerSettings::setDateTimeFormatEnum (const Qt::DateFormat & dtFormat) [inline], [static]
Definition at line 37 of file OAIHelpers.cpp.
                                                                   {
        getInstance()->customDateTimeFormat.isEnumSet = true;
        getInstance()->customDateTimeFormat.isStringSet = false;
        getInstance()->customDateTimeFormat.formatEnum = dtFormat;
    }
References customDateTimeFormat, OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatEnum, getInstance(), OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isEnumSet, and OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isStringSet.
Referenced by OpenAPI::setDateTimeFormat().
setDateTimeFormatString()
static void OpenAPI::OAISerializerSettings::setDateTimeFormatString (const QString & dtFormat) [inline], [static]
Definition at line 31 of file OAIHelpers.cpp.
                                                                {
        getInstance()->customDateTimeFormat.isStringSet = true;
        getInstance()->customDateTimeFormat.isEnumSet = false;
        getInstance()->customDateTimeFormat.formatString = dtFormat;
    }
References customDateTimeFormat, OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatString, getInstance(), OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isEnumSet, and OpenAPI::OAISerializerSettings::CustomDateTimeFormat::isStringSet.
Referenced by OpenAPI::setDateTimeFormat().
Member Data Documentation
customDateTimeFormat
CustomDateTimeFormat OpenAPI::OAISerializerSettings::customDateTimeFormat [private]
Definition at line 57 of file OAIHelpers.cpp.
Referenced by OAISerializerSettings(), getCustomDateTimeFormat(), setDateTimeFormatEnum(), and setDateTimeFormatString().
dateTimeFormat
QString OpenAPI::OAISerializerSettings::dateTimeFormat [private]
Definition at line 38 of file OAIHelpers.cpp.
Referenced by OAISerializerSettings(), getDateTimeFormat(), and setDateTimeFormat().
instance
OAISerializerSettings * OpenAPI::OAISerializerSettings::instance = nullptr [static], [private]
Definition at line 56 of file OAIHelpers.cpp.
Referenced by OAISerializerSettings(), and getInstance().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIHelpers.cpp
streets_utils/streets_api/intersection_server_api/src/models/OAIHelpers.cpp