streets_vehicle_scheduler::all_stop_vehicle_scheduler Class Reference
#include <all_stop_vehicle_scheduler.h>
Public Member Functions
all_stop_vehicle_scheduler ()=default
Construct a new all stop vehicle scheduler object.
~all_stop_vehicle_scheduler () override=default
Destroy the all stop vehicle scheduler object.
void schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, std::shared_ptr< intersection_schedule > &schedule) override
Method to schedule vehicles. Given and empty intersection_schedule object and a map of vehicles and vehicle ids. This method will populate the intersection schedule with a schedule for each EV,RDV and DV in the vehicle map based on UC 1 scheduling logic to minimize delay for a all way stop intersection.
void set_entering_time_buffer (const uint64_t buffer)
Set the entering time buffer (ms). This value is used to account for the time it takes a vehicle stopped before the stop bar at an entry lane to exit the entry lane and enter the link lane once given access.
void set_flexibility_limit (const int limit)
Set the flexibility limit. This limit controls how much departure position can change for any given vehicle between successive intersection schedule calculations. Each subsequent intersection scheduling calculation may have a slightly different departure order. This value controls how much this departure order can change.A value of 1 represents that vehicles departure position can change by one between two intersection schedules.
Private Member Functions
void schedule_dvs (std::list< streets_vehicles::vehicle > &dvs, const std::shared_ptr< all_stop_intersection_schedule > &schedule) const
Schedule all currently Departing Vehicle (DVs). Estimate intersection departure times (dt's) for each vehicle based on kinematic vehicle information and intersection geometry. Method assumes empty intersection_schedule is passed in. Method will add vehicle_schedule(s) for each DV in the vector.
void schedule_rdvs (std::list< streets_vehicles::vehicle > &rdvs, const std::shared_ptr< all_stop_intersection_schedule > &schedule)
Schedule all currently Ready to Depart Vehicles (RDVs). Consider all possible RDV departure orders. Select the one with the least calculated delay. Delay for a given vehicle is the difference between Entering Time and Stopping Time. Method assumes intersection_schedule only populated with DV(s) vehicle_schedules. Method will add vehicle_schedule(s) for each RDV in vector.
bool is_rdv_previously_granted_access (const streets_vehicles::vehicle &veh) const
Method to determine whether vehicle was granted access to the intersection in previous schedules. To avoid granting conflicting vehicles intersection access simultaneously, the scheduling service maintains a list of vehicles it has granted access to in the past. Vehicles are removed from this list once their update reflects that they have received and processed this access.
void remove_rdv_previously_granted_access (const streets_vehicles::vehicle &veh)
This method will remove a vehicle (DV) once it's updates reflect that is has received access from the list of previously granted access RDVs. This method should be called once a RDV received the schedule update that grants it access to the intersection. This is indicated by the vehicle no longer being a RDV and instead being a DV (.
streets_vehicles::vehicle get_vehicle_with_id (const std::list< streets_vehicles::vehicle > &veh_list, const std::string &veh_id) const
Given a list of vehicles and a vehicle id, this method returns the vehicle with a matching vehicle id if there is one. This method will throw a scheduling_exception if no vehicle with the given id is found.
void schedule_evs (std::list< streets_vehicles::vehicle > &evs, const std::shared_ptr< all_stop_intersection_schedule > &schedule) const
Schedule all Entering Vehicles (EVs). Method first organizes all EVs into lists based on their entry lane. These list are order in ascending order with the vehicle closest to the intersection in a given lane being the first vehicle in that entry lanes vehicle list. Then stopping time (ST) for the unscheduled front EVs from every approach are calculated and the vehicle with the lowest (earliest) stopping times is scheduled. This is repeated until all evs from all approach lanelets are scheduled.
uint64_t estimate_entering_time_for_ev (const std::vector< all_stop_vehicle_schedule > &vehicle_schedules, const streets_vehicles::vehicle &ev, const uint64_t st) const
Estimates an entering time (ET) for a given Entering Vehicle (EV). This method first searches among the existing scheduled vehicles and find the departure time (DT) of the last scheduled vehicle with conflicting direction. The ET of the vehicle is calculated based on this DT (if exist) and the estimated stopping time (ST) oft the vehicle.
bool consider_departure_position_permutation (const std::list< streets_vehicles::vehicle > &rdvs, const std::shared_ptr< all_stop_intersection_schedule > &option, int starting_departure_position) const
Creates and intersection schedule for a given RDV departure order. RDV departure order is based on rdvs order. Returns reference to intersection_schedule option/possibility with given departure order. Assumes intersection_schedule option only contains schedules for DVs. Populates intersection_schedule with RDV vehicle_schedules.
uint64_t estimate_clearance_time (const streets_vehicles::vehicle &veh, const OpenAPI::OAILanelet_info &link_lane_info) const
Estimate clearance time any vehicle given it's link lanelet information.
std::shared_ptr< all_stop_vehicle_schedule > get_latest_conflicting (const OpenAPI::OAILanelet_info &link_lane, const std::vector< all_stop_vehicle_schedule > &schedules) const
Given a link lane and a vector of vehicle schedules, this method returns a pointer to a vehicle schedule with a conflicting direction and the latest departure time. If no vehicle schedules have conflicting directions it returns nullptr. This method is meant to return the limiting conflicting vehicle for scheduling new RDVs in a link lane.
uint64_t estimate_earliest_time_to_stop_bar (const streets_vehicles::vehicle &veh) const
Method to use vehicle kinematic information to estimate earliest possible time stopping time for a vehicle. Does not consider any other vehicles. Limiting factors are the vehicles current kinematic information, lane speed limits and vehicle acceleration and deceleration limits.
double estimate_delta_x_prime (const streets_vehicles::vehicle &veh, const OpenAPI::OAILanelet_info &entry_lane) const
Calculate minumum distance required to speed up to lane speed limit with maximum acceleration, cruise at lane speed limit for some time, then decelerate with maximum deceleration. This is used to determine the trajectory to provide the vehicle.
double calculate_v_hat (const streets_vehicles::vehicle &veh) const
Method to calculate v_hat. This is the maximum speed reached between maximum speed reached between acceleration and deceleration periods for a vehicle trajectory towards stopping at a stop bar.
double calculate_acceleration_time (const streets_vehicles::vehicle &veh, const double v_hat) const
Method to calculate time interval necessary for accelerating to speed v_hat for a given vehicle. Will return 0 if v_hat is less than vehicle speed.
double calculate_deceleration_time (const streets_vehicles::vehicle &veh, const double v_hat) const
Method to calculate time interval necessary for deceleration from v_hat to 0 to stop at stop bar. Assumes trajectory with constant maximum deceleration.
double calculate_cruising_time (const streets_vehicles::vehicle &veh, const double v_hat, const double delta_x_prime) const
Method to calculate time interval necessary for cruising at a constant speed v_hat (speed limit) greater than current vehicle speed.If vehicle speed is greater that v_hat, this method will return 0.
Private Attributes
std::list< streets_vehicles::vehicle > rdvs_previously_granted_access
A list of RDV vehicles granted access by the vehicle_scheduler, who's updates do not yet reflect they have received access (still considered RDV by all_stop_status_intent_processor). We maintain this list to ensure we do not grant conflicting vehicles access to the intersection simultaneously in back to back scheduling calculations where the first RDV granted access in the first schedule has not yet provided a vehicle update the reflects this access by the time we calculate the second schedule.
uint64_t entering_time_buffer = 0
Configurable time buffer in milliseconds for estimating the time it takes a vehicle to leave its entry lane and enter the intersection box once granted access to the intersection.
int flexibility_limit = 5
Limits how much departure position for a given vehicle can change from current reported departure position.
Additional Inherited Members
Detailed Description
Definition at line 16 of file all_stop_vehicle_scheduler.h.
Constructor & Destructor Documentation
all_stop_vehicle_scheduler()
streets_vehicle_scheduler::all_stop_vehicle_scheduler::all_stop_vehicle_scheduler () [default]
Construct a new all stop vehicle scheduler object.
 all_stop_vehicle_scheduler()
streets_vehicle_scheduler::all_stop_vehicle_scheduler::~all_stop_vehicle_scheduler () [override], [default]
Destroy the all stop vehicle scheduler object.
Member Function Documentation
calculate_acceleration_time()
double streets_vehicle_scheduler::all_stop_vehicle_scheduler::calculate_acceleration_time (const streets_vehicles::vehicle & veh, const double v_hat) const [private]
Method to calculate time interval necessary for accelerating to speed v_hat for a given vehicle. Will return 0 if v_hat is less than vehicle speed.
Parameters
veh vehicle for which to calculate trajectory.
v_hat maximum speed to reach during acceleration in m/s.
Returns
double time interval necessary for acceleration in seconds.
Definition at line 93 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                {
        // If v_hat is less than current vehicle speed there is only time for deceleration
        // Note: This is an error case and means stopping before the stop bar is not possible given current kinematic information
        // and deceleration limits
        if (v_hat < veh._cur_speed){
            return 0.0;
        }
        return (v_hat-veh._cur_speed)/veh._accel_max;
    }
References streets_vehicles::vehicle::_accel_max, and streets_vehicles::vehicle::_cur_speed.
Referenced by estimate_earliest_time_to_stop_bar().
calculate_cruising_time()
double streets_vehicle_scheduler::all_stop_vehicle_scheduler::calculate_cruising_time (const streets_vehicles::vehicle & veh, const double v_hat, const double delta_x_prime) const [private]
Method to calculate time interval necessary for cruising at a constant speed v_hat (speed limit) greater than current vehicle speed.If vehicle speed is greater that v_hat, this method will return 0.
Parameters
veh vehicle for which to calculate trajectory for.
v_hat cruising speed, usually lane speed limit, in m/s.
delta_x_prime the distance necessary for vehicle to accelerate to speed limit with maximum acceleration and then decelerate back to a stop in meters.The difference the distance to the stop bar and this distance is the part of the trajectory for which the vehicle can cruise at the speed limit.
Returns
double time interval necessary for cruising at speed limit in seconds.
Definition at line 103 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                                        {
        // If v_hat is less than current speed there is only time for deceleration
        // Note: This is an error case and means stopping before the stop bar is not possible given current kinematic information
        // and deceleration limits
        if (v_hat < veh._cur_speed) {
            return 0.0;
        }
        return (veh._cur_distance - delta_x_prime)/v_hat;
    }
References streets_vehicles::vehicle::_cur_distance, and streets_vehicles::vehicle::_cur_speed.
Referenced by estimate_earliest_time_to_stop_bar().
calculate_deceleration_time()
double streets_vehicle_scheduler::all_stop_vehicle_scheduler::calculate_deceleration_time (const streets_vehicles::vehicle & veh, const double v_hat) const [private]
Method to calculate time interval necessary for deceleration from v_hat to 0 to stop at stop bar. Assumes trajectory with constant maximum deceleration.
Parameters
veh vehicle for which to calculate trajectory.
v_hat max speed from which to decelerate from in m/s
Returns
double time interval necessary for acceleration in seconds.
Definition at line 113 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                {
        return -v_hat/veh._decel_max;
    }
References streets_vehicles::vehicle::_decel_max.
Referenced by estimate_earliest_time_to_stop_bar().
calculate_v_hat()
double streets_vehicle_scheduler::all_stop_vehicle_scheduler::calculate_v_hat (const streets_vehicles::vehicle & veh) const [private]
Method to calculate v_hat. This is the maximum speed reached between maximum speed reached between acceleration and deceleration periods for a vehicle trajectory towards stopping at a stop bar.
Parameters
veh vehicle to calculate trajectory for.
Returns
double v_hat in m/s
Definition at line 82 of file all_stop_vehicle_scheduler.cpp.
                                                                                               {
        double numerator = veh._decel_max *(2 * veh._cur_distance*veh._accel_max + pow(veh._cur_speed, 2));
        double denominator = veh._decel_max-veh._accel_max;
        double v_hat = sqrt(numerator/denominator);
        // If v_hat is less that current vehicle speed, const maximum deceleration will not stop before stop bar
        if (v_hat < veh._cur_speed) {
            SPDLOG_ERROR("Stopping trajectory not possible for vehicle {0} with speed {1} m/s and v_hat {2} m/s!", veh._id, veh._cur_speed, v_hat);
        }
        return v_hat;
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_distance, streets_vehicles::vehicle::_cur_speed, streets_vehicles::vehicle::_decel_max, and streets_vehicles::vehicle::_id.
Referenced by estimate_earliest_time_to_stop_bar().
consider_departure_position_permutation()
bool streets_vehicle_scheduler::all_stop_vehicle_scheduler::consider_departure_position_permutation (const std::list< streets_vehicles::vehicle > & rdvs, const std::shared_ptr< all_stop_intersection_schedule > & option, int starting_departure_position) const [private]
Creates and intersection schedule for a given RDV departure order. RDV departure order is based on rdvs order. Returns reference to intersection_schedule option/possibility with given departure order. Assumes intersection_schedule option only contains schedules for DVs. Populates intersection_schedule with RDV vehicle_schedules.
Parameters
rdvs vector of unscheduled RDVs
option all_stop_intersection_schedule possibility.
starting_departure_position first available departure position given already scheduled vehicle (e.i. DVs)
scheduled_dvs a vector of scheduled dvs, This includes dvs already schedules and any RDVs scheduled in this permutation. This is necessary for calculating the current RDVs entering time based on already scheduled DVs and RDVs conflicts.
Returns
true if departure order is valid and does not violate flexibility_limit for any vehicle.
false if departure order is invalid and does violate flexibility_limit for any vehicle.
Definition at line 432 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                        {
        for (const auto &veh : rdvs) {
            // If scheduling option moves vehicle departure position more than flexibility limit it is not a valid option.
            if (abs(starting_departure_position - veh._departure_position) > flexibility_limit) {
                SPDLOG_WARN(
                    "Not considering scheduling option since change in departure position for vehicle {0} exceeds flexibility limit {1}!",
                    veh._id, flexibility_limit);
                // Break out of scheduling estimation loop and do not consider this scheduling option
                return false;
            }
            all_stop_vehicle_schedule sched;
            // Populate common vehicle schedule information
            sched.v_id = veh._id;
            // RDVs should have already stopped
            sched.st = veh._actual_st;
            sched.est = veh._actual_st;
            // set dp position for current permutation
            sched.dp = starting_departure_position;
            // Set connection link lanelet id
            sched.link_id = veh._link_id;
            // Set entry lanelet id
            sched.entry_lane = veh._entry_lane_id;
            // Get vehicle lane info
            OpenAPI::OAILanelet_info veh_lane = get_link_lanelet_info(veh);
            std::shared_ptr<all_stop_vehicle_schedule> latest_conflicting_vehicle = get_latest_conflicting(veh_lane, option->vehicle_schedules);
            // If there is no conflicting scheduled vehicle (RDVs and DVs)
            if (latest_conflicting_vehicle == nullptr) {
                // Consider previously scheduled vehicle. Current vehicle cannot be granted access
                // to intersection regardless of conflict status before previously scheduled vehicle
                // to preserve departure order
                if (option->vehicle_schedules.empty() || option->vehicle_schedules.back().access) {
                    // Give vehicle access since there are no proceeding vehicles
                    sched.access = true;
                    // Set vehicle state. Will not impact clearance time estimation since set on schedule
                    sched.state = streets_vehicles::vehicle_state::DV;
                    // Entering time equals schedule time
                    sched.et = option->timestamp;
                    // Departure time equals entering time + clearance time
                    sched.dt = sched.et + estimate_clearance_time(veh, veh_lane);
                }
                else {
                    // Can not grant access to vehicle if previous vehicle does not have access yet.
                    sched.access = false;
                    // Set vehicle state. Will not impact clearance time estimation since set on schedule
                    sched.state = streets_vehicles::vehicle_state::RDV;
                    // Entering time equals schedule time
                    sched.et = option->vehicle_schedules.back().et;
                    // Departure time equals entering time + clearance time
                    sched.dt = sched.et + estimate_clearance_time(veh, veh_lane);
                }
            }
            else {
                SPDLOG_DEBUG("Latest conflicting vehicle is {0} and next vehicle is {1}", latest_conflicting_vehicle->v_id, veh._id);
                sched.access = false;
                sched.state = streets_vehicles::vehicle_state::RDV;
                sched.et = std::max(latest_conflicting_vehicle->dt, option->vehicle_schedules.back().et);
                // Departure time is estimated clearance time for vehicle and link lane plus entering time
                sched.dt = sched.et + estimate_clearance_time(veh, veh_lane);
                
            }
            // Add vehicle schedule to option
            option->vehicle_schedules.push_back(sched);
            // Point to new previously scheduled vehicle
            // Increment departure position
            starting_departure_position++;
            
        }
        SPDLOG_DEBUG("Schedule Option: \n"+option->toCSV());
        SPDLOG_DEBUG("With delay {0}." ,option->get_delay());
        return true;
            
    }
References streets_vehicle_scheduler::all_stop_vehicle_schedule::access, streets_vehicle_scheduler::all_stop_vehicle_schedule::dp, streets_vehicle_scheduler::all_stop_vehicle_schedule::dt, streets_vehicles::DV, streets_vehicle_scheduler::vehicle_schedule::entry_lane, streets_vehicle_scheduler::all_stop_vehicle_schedule::est, estimate_clearance_time(), streets_vehicle_scheduler::all_stop_vehicle_schedule::et, flexibility_limit, get_latest_conflicting(), streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), streets_vehicle_scheduler::vehicle_schedule::link_id, streets_vehicles::RDV, streets_vehicle_scheduler::all_stop_vehicle_schedule::st, streets_vehicle_scheduler::all_stop_vehicle_schedule::state, and streets_vehicle_scheduler::vehicle_schedule::v_id.
Referenced by schedule_rdvs().
estimate_clearance_time()
uint64_t streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_clearance_time (const streets_vehicles::vehicle & veh, const OpenAPI::OAILanelet_info & link_lane_info) const [private]
Estimate clearance time any vehicle given it's link lanelet information.
Parameters
veh vehicle to estimate clearance time for.
link_lane_info link lanelet vehicle is attempting to clear.
Returns
uint64_t clearance time in milliseconds.
Definition at line 511 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                       {
        // Clearance time in seconds
        double clearance_time = 0;
        // If vehicle is Departing Vehicle consider its location in the link lanelet.
        if (veh._cur_state == streets_vehicles::vehicle_state::DV) {
            // Distance covered during constant max acceleration to speed limit
            double constant_acceleration_delta_x = (pow(link_lane_info.getSpeedLimit(), 2) - pow(veh._cur_speed, 2))/(2* veh._accel_max);
            // If vehicle accelerates to speed limit with max acceleration is it still in link lanelet
            if (veh._cur_distance > constant_acceleration_delta_x) {
                clearance_time = (2 * veh._accel_max * veh._cur_distance - link_lane_info.getSpeedLimit()*veh._cur_speed + pow(veh._cur_speed, 2))/
                    (2*veh._accel_max*link_lane_info.getSpeedLimit());
            } else {
                clearance_time = (sqrt(pow(veh._cur_speed, 2)+2*veh._accel_max*veh._cur_distance) -veh._cur_speed)/
                        veh._accel_max;
            }
        }
        // Consider vehicle is stopped at stop bar
        else {
            // Distance covered during constant max acceleration to speed limit assuming initial 0 speed.
            double constant_acceleration_delta_x = pow(link_lane_info.getSpeedLimit(), 2) / (2 * veh._accel_max);
            // If vehicle accelerates to speed limit with max acceleration is it still in the link lanelet
            if (constant_acceleration_delta_x < link_lane_info.getLength()){
                // If yes assume vehicle cruises at speed limit for the duration of the lanelet
                clearance_time = link_lane_info.getLength() / link_lane_info.getSpeedLimit() +
                            link_lane_info.getSpeedLimit() / (2 *veh._accel_max);
            } else{
                // If not assume vehicle trajectory is constant acceleration from initial speed of 0
                clearance_time = sqrt(2 * link_lane_info.getLength() / veh._accel_max) ;
            }
        }
        // Convert time to milliseconds and round up.
        return static_cast<uint64_t>(ceil(1000.0* clearance_time));
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_distance, streets_vehicles::vehicle::_cur_speed, streets_vehicles::vehicle::_cur_state, streets_vehicles::DV, OpenAPI::OAILanelet_info::getLength(), and OpenAPI::OAILanelet_info::getSpeedLimit().
Referenced by consider_departure_position_permutation(), schedule_dvs(), and schedule_evs().
estimate_delta_x_prime()
double streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_delta_x_prime (const streets_vehicles::vehicle & veh, const OpenAPI::OAILanelet_info & entry_lane) const [private]
Calculate minumum distance required to speed up to lane speed limit with maximum acceleration, cruise at lane speed limit for some time, then decelerate with maximum deceleration. This is used to determine the trajectory to provide the vehicle.
Parameters
veh vehicle for which to calculate distance.
entry_lane entry lane information.
Returns
double distance in meters
Definition at line 68 of file all_stop_vehicle_scheduler.cpp.
                                                                                                               {
        if (veh._cur_state == streets_vehicles::vehicle_state::EV) {
            // Get Entry Lanelet
            double delta_x_prime = (pow(entry_lane.getSpeedLimit(),2)-pow(veh._cur_speed,2))/(2*veh._accel_max) -
                pow(entry_lane.getSpeedLimit(), 2)/(2*veh._decel_max);
            return delta_x_prime;
        }
        else {
            SPDLOG_WARN("Cannot estimate delta x prime for vehicle {0} because it's state {1} != EV !");
        }
        return -1;
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_speed, streets_vehicles::vehicle::_cur_state, streets_vehicles::vehicle::_decel_max, streets_vehicles::EV, and OpenAPI::OAILanelet_info::getSpeedLimit().
Referenced by estimate_earliest_time_to_stop_bar().
estimate_earliest_time_to_stop_bar()
uint64_t streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_earliest_time_to_stop_bar (const streets_vehicles::vehicle & veh) const [private]
Method to use vehicle kinematic information to estimate earliest possible time stopping time for a vehicle. Does not consider any other vehicles. Limiting factors are the vehicles current kinematic information, lane speed limits and vehicle acceleration and deceleration limits.
Parameters
veh vehicle for which to calculate trajectory
Returns
uint64_t time in milliseconds.
Definition at line 390 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                   {
        // Distance to stop bar
        double delta_x = veh._cur_distance;
        // Get Entry Lane
        OpenAPI::OAILanelet_info lane_info = get_entry_lanelet_info(veh);
        // Distance necessary to get to max speed and decelerate with decel_max
        double delta_x_prime = estimate_delta_x_prime(veh, lane_info);
        SPDLOG_DEBUG("Delta X Prime = {0}.", delta_x_prime);
        // Calculate v_hat and planned cruising time interval
        double v_hat;
        double t_cruising;
        if (delta_x >= delta_x_prime) {
            v_hat = lane_info.getSpeedLimit();
            SPDLOG_DEBUG("V hat = {0}.", v_hat);
            t_cruising = calculate_cruising_time(veh, v_hat, delta_x_prime);
            SPDLOG_DEBUG("T cruising = {0}.",t_cruising);
        }
        else {
            v_hat = calculate_v_hat(veh);
            SPDLOG_DEBUG("V hat = {0}.", v_hat);
            t_cruising = 0.0;
            SPDLOG_DEBUG("T cruising = {0}.",t_cruising);
        }
        
        // calculate planned acceleration time interval
        double t_accel = calculate_acceleration_time(veh, v_hat);
        SPDLOG_DEBUG("T accel = {0}.",t_accel);
        // calculate planned deceleration time interval
        double t_decel = calculate_deceleration_time(veh, v_hat);
        SPDLOG_DEBUG("T decel = {0}.",t_decel);
        // calculate time to stop bar
        double time_to_stop_bar = t_accel + t_cruising + t_decel;
        return static_cast<uint64_t>(ceil(time_to_stop_bar * 1000.0)) + veh._cur_time;
    }
References streets_vehicles::vehicle::_cur_distance, streets_vehicles::vehicle::_cur_time, calculate_acceleration_time(), calculate_cruising_time(), calculate_deceleration_time(), calculate_v_hat(), estimate_delta_x_prime(), streets_vehicle_scheduler::vehicle_scheduler::get_entry_lanelet_info(), and OpenAPI::OAILanelet_info::getSpeedLimit().
Referenced by schedule_evs().
estimate_entering_time_for_ev()
uint64_t streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_entering_time_for_ev (const std::vector< all_stop_vehicle_schedule > & vehicle_schedules, const streets_vehicles::vehicle & ev, const uint64_t st) const [private]
Estimates an entering time (ET) for a given Entering Vehicle (EV). This method first searches among the existing scheduled vehicles and find the departure time (DT) of the last scheduled vehicle with conflicting direction. The ET of the vehicle is calculated based on this DT (if exist) and the estimated stopping time (ST) oft the vehicle.
Parameters
schedule all_stop_intersection_schedule.
ev vehicle for which to estimate ET.
st estimated stopping time.
Definition at line 368 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                                                                                 {
        // Get link lanelet information for ev
        OpenAPI::OAILanelet_info link_lane = get_link_lanelet_info(ev);
        // Get schedule of conflicting vehicle with largest dt from already scheduled vehicles
        if (!vehicle_schedules.empty()) {
            std::shared_ptr<all_stop_vehicle_schedule> conflict_with_largest_dt = get_latest_conflicting(link_lane, vehicle_schedules);
            
            if (conflict_with_largest_dt != nullptr) {
                SPDLOG_DEBUG("Vehicle with largest conflict to {0} is {1}.", ev._id, conflict_with_largest_dt->v_id);
                // Entering time is the maximum between the conflicting vehicles departure time and the current vehicles stopping time
                return std::max(conflict_with_largest_dt->dt, st);
            }else{
                // If there is no conflicting scheduled vehicle, st == et
                return st;
            }
        }
        else {
            // If schedule is empty there can be no conflict
            return st;
        }
    }
References streets_vehicles::vehicle::_id, get_latest_conflicting(), and streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info().
Referenced by schedule_evs().
get_latest_conflicting()
std::shared_ptr< all_stop_vehicle_schedule > streets_vehicle_scheduler::all_stop_vehicle_scheduler::get_latest_conflicting (const OpenAPI::OAILanelet_info & link_lane, const std::vector< all_stop_vehicle_schedule > & schedules) const [private]
Given a link lane and a vector of vehicle schedules, this method returns a pointer to a vehicle schedule with a conflicting direction and the latest departure time. If no vehicle schedules have conflicting directions it returns nullptr. This method is meant to return the limiting conflicting vehicle for scheduling new RDVs in a link lane.
Parameters
link_lane the linking lane to be traveled
schedules Already scheduled vehicles
Returns
std::shared_ptr<vehicle_schedule> pointer to vehicle schedule with conflicting direction and latest departure time.
Definition at line 547 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                             {
        std::shared_ptr<all_stop_vehicle_schedule> conflict = nullptr;
        // Loop through all scheduled vehicles and return conflict with largest dt
        for (const auto &sched : schedules) {
            // check if that have conflict with link_lane
            if (link_lane.getConflictLaneletIds().contains(sched.link_id)) {
                // If no conflicting schedule has been set yet set conflict to first conflicting
                if (conflict == nullptr) {
                    conflict = std::make_shared<all_stop_vehicle_schedule>(sched);
                }
                else if (conflict->dt < sched.dt) {
                    conflict = std::make_shared<all_stop_vehicle_schedule>(sched);
                }
            }
            
        }
        return conflict;
    }
References OpenAPI::OAILanelet_info::getConflictLaneletIds().
Referenced by consider_departure_position_permutation(), and estimate_entering_time_for_ev().
get_vehicle_with_id()
streets_vehicles::vehicle streets_vehicle_scheduler::all_stop_vehicle_scheduler::get_vehicle_with_id (const std::list< streets_vehicles::vehicle > & veh_list, const std::string & veh_id) const [private]
Given a list of vehicles and a vehicle id, this method returns the vehicle with a matching vehicle id if there is one. This method will throw a scheduling_exception if no vehicle with the given id is found.
Parameters
veh_list list to search.
veh_id vehicle id to search for.
Returns
streets_vehicles::vehicle vehicle with matching vehicle id
Exceptions
scheduling_exception if vehicle is not in list.
Definition at line 595 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                                             {
        streets_vehicles::vehicle rtn;
        bool found_veh = false;
        if (veh_list.empty()) {
            throw scheduling_exception("Vehicle List is empty!");
            
        }
        else {
            for (const auto &veh : veh_list) {
                if (veh._id == veh_id) {
                    rtn = veh;
                    found_veh = true;
                }
            }
        }
        if (!found_veh) {
            throw scheduling_exception("Vehicle" + veh_id + " not found!");
 
        }
        return rtn;
    }
Referenced by schedule_rdvs().
is_rdv_previously_granted_access()
bool streets_vehicle_scheduler::all_stop_vehicle_scheduler::is_rdv_previously_granted_access (const streets_vehicles::vehicle & veh) const [private]
Method to determine whether vehicle was granted access to the intersection in previous schedules. To avoid granting conflicting vehicles intersection access simultaneously, the scheduling service maintains a list of vehicles it has granted access to in the past. Vehicles are removed from this list once their update reflects that they have received and processed this access.
Parameters
veh
Returns
true if vehicle is in list of vehicles previously granted access.
false if vehicle is not in list of vehicles previously granted access.
Definition at line 580 of file all_stop_vehicle_scheduler.cpp.
                                                                                                               {
        if (rdvs_previously_granted_access.empty()) {
            return false;
        }
        else {
            for (const auto &rdv: rdvs_previously_granted_access) {
                if (rdv._id == veh._id) {
                    return true;
                }
            }
            // not in list
            return false;
        }
    }
References streets_vehicles::vehicle::_id, and rdvs_previously_granted_access.
Referenced by schedule_dvs(), and schedule_vehicles().
remove_rdv_previously_granted_access()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::remove_rdv_previously_granted_access (const streets_vehicles::vehicle & veh) [private]
This method will remove a vehicle (DV) once it's updates reflect that is has received access from the list of previously granted access RDVs. This method should be called once a RDV received the schedule update that grants it access to the intersection. This is indicated by the vehicle no longer being a RDV and instead being a DV (.
See also
streets_vehicle_list library).
Parameters
veh DV to be removed from list
Definition at line 567 of file all_stop_vehicle_scheduler.cpp.
                                                                                                             {
        auto previously_granted_itr = rdvs_previously_granted_access.begin();
        while (previously_granted_itr != rdvs_previously_granted_access.end()) {
            if (previously_granted_itr->_id == veh._id) {
                SPDLOG_INFO("Removing DV {0} from list of RDVs previously granted access.", previously_granted_itr->_id);
                rdvs_previously_granted_access.erase(previously_granted_itr);
                break;
            }else {
                previously_granted_itr++;
            }
        }
    }
References streets_vehicles::vehicle::_id, and rdvs_previously_granted_access.
Referenced by schedule_vehicles().
schedule_dvs()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_dvs (std::list< streets_vehicles::vehicle > & dvs, const std::shared_ptr< all_stop_intersection_schedule > & schedule) const [private]
Schedule all currently Departing Vehicle (DVs). Estimate intersection departure times (dt's) for each vehicle based on kinematic vehicle information and intersection geometry. Method assumes empty intersection_schedule is passed in. Method will add vehicle_schedule(s) for each DV in the vector.
Parameters
dvs vector of unscheduled DVs
schedule all_stop_intersection_schedule to add DV scheduling information to.
Definition at line 117 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                    {
        // Sort based on departure position
        dvs.sort(departure_position_comparator);
        // Regardless of previously set departure index, set DV with lowest departure position to departure position 1
        // to account for DVs that have become LVs
        int departure_position_index = 1;
        for (const auto &departing_veh : dvs) {
            SPDLOG_DEBUG("Scheduling DV with ID {0} .", departing_veh._id);
            // get link lane info
            OpenAPI::OAILanelet_info lane_info = get_link_lanelet_info(departing_veh);
            // calculate clearance time in milliseconds
            uint64_t clearance_time = estimate_clearance_time(departing_veh, lane_info);
            all_stop_vehicle_schedule veh_sched;
            // set id
            veh_sched.v_id = departing_veh._id;
            // set est
            veh_sched.est = departing_veh._actual_st;
            // set st
            veh_sched.st = departing_veh._actual_st;
            // set et
            // if the vehicle is a previously granted access rdv but did not confirm it has received access and thus, doesn't have an actual et
            if (is_rdv_previously_granted_access(departing_veh))
            {
                veh_sched.et = schedule->timestamp;
            }
            // otherwise
            else
            {
                veh_sched.et = departing_veh._actual_et;
            }
            // departure time is equal to current time plus clearance time for DVs
            veh_sched.dt = schedule->timestamp + clearance_time;
            // set departure position to departure position index
            veh_sched.dp = departure_position_index;
            // Increment index for next DV
            departure_position_index++;
            // set state
            veh_sched.state = departing_veh._cur_state;
            // set vehicle link id
            veh_sched.link_id = departing_veh._link_id;
            // set vehicle entry lane id
            veh_sched.entry_lane = departing_veh._entry_lane_id;
            // set access
            veh_sched.access = true;
            SPDLOG_DEBUG("Added schedule for {0} with dt {1}.", veh_sched.v_id, veh_sched.dt);
            // add vehicle_schedule
            schedule->vehicle_schedules.push_back(veh_sched);
        }
    }
References streets_vehicle_scheduler::all_stop_vehicle_schedule::access, streets_vehicle_scheduler::departure_position_comparator(), streets_vehicle_scheduler::all_stop_vehicle_schedule::dp, streets_vehicle_scheduler::all_stop_vehicle_schedule::dt, streets_vehicle_scheduler::vehicle_schedule::entry_lane, streets_vehicle_scheduler::all_stop_vehicle_schedule::est, estimate_clearance_time(), streets_vehicle_scheduler::all_stop_vehicle_schedule::et, streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), is_rdv_previously_granted_access(), streets_vehicle_scheduler::vehicle_schedule::link_id, streets_vehicle_scheduler::all_stop_vehicle_schedule::st, streets_vehicle_scheduler::all_stop_vehicle_schedule::state, and streets_vehicle_scheduler::vehicle_schedule::v_id.
Referenced by schedule_vehicles().
schedule_evs()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_evs (std::list< streets_vehicles::vehicle > & evs, const std::shared_ptr< all_stop_intersection_schedule > & schedule) const [private]
Schedule all Entering Vehicles (EVs). Method first organizes all EVs into lists based on their entry lane. These list are order in ascending order with the vehicle closest to the intersection in a given lane being the first vehicle in that entry lanes vehicle list. Then stopping time (ST) for the unscheduled front EVs from every approach are calculated and the vehicle with the lowest (earliest) stopping times is scheduled. This is repeated until all evs from all approach lanelets are scheduled.
Parameters
evs vector of unscheduled EVs.
schedule all_stop_intersection_schedule to add EV scheduling information to.
Definition at line 230 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                                              {
        // Map of entry lane ids to preceding already scheduled vehicle
        std::unordered_map<int , all_stop_vehicle_schedule> preceding_vehicle_entry_lane_map;
        for (const auto &entry_lane : intersection_info->getEntryLanelets()) {
            int lane_id = entry_lane.getId();
            all_stop_vehicle_schedule preceding_veh;
            // Only one RDV can exist for each approach
            for (const auto &veh_sched : schedule->vehicle_schedules) {
                if (veh_sched.state == streets_vehicles::vehicle_state::RDV) {
                    // All RDVs
                    preceding_veh = veh_sched;
                    preceding_vehicle_entry_lane_map.try_emplace(lane_id, preceding_veh);
                }
                // Consider vehicles recently granted access
                else if (veh_sched.state == streets_vehicles::vehicle_state::DV && (veh_sched.et-schedule->timestamp) <= entering_time_buffer) {
                    SPDLOG_DEBUG("Considering DV {0} as still in entry since entering time {1} - timestamp {2} does not exceed buffer {3}",
                            veh_sched.v_id, veh_sched.et, schedule->timestamp, entering_time_buffer);
                    preceding_veh = veh_sched;
                    preceding_vehicle_entry_lane_map.try_emplace(lane_id, preceding_veh);
                }
            }
        }
        // Sort vehicles based on distance
        evs.sort(distance_comparator);
        
        // Create a map of entry lane id keys and list of vehicle to be scheduled next in each lane.
        std::unordered_map<int, std::list<streets_vehicles::vehicle>> vehicle_to_be_scheduled_next;
        for (const auto &entry_lane : intersection_info->getEntryLanelets()) {
            std::list<streets_vehicles::vehicle> vehicles_in_lane;
            for (const auto &ev : evs) {
                if (ev._entry_lane_id == entry_lane.getId()) {
                    SPDLOG_DEBUG("Adding vehicle {0} to EVs list in entry lane {1}", ev._id, ev._entry_lane_id);
                    vehicles_in_lane.push_back(ev);
                }
            }
            if (!vehicles_in_lane.empty())
                vehicle_to_be_scheduled_next.try_emplace(entry_lane.getId(), vehicles_in_lane);
            else {
                SPDLOG_DEBUG("No EVs in lane {0}.",static_cast<int>(entry_lane.getId()));
            }
        }
        if (!vehicle_to_be_scheduled_next.empty()) {
            for (const auto &[entry_lane, next_veh] : vehicle_to_be_scheduled_next) {
                SPDLOG_DEBUG("Next Vehicle {0} to be scheduled in lane {1}",next_veh.front()._id, entry_lane);
            }
        }
        else {
            throw scheduling_exception("Map of vehicles to be scheduled is empty but list of EVs to be scheduled is not!");
        }
        // Get next available departure index, default to 1 if schedule is empty
        int last_departure_index = 1;
        if (!schedule->vehicle_schedules.empty()) {
            last_departure_index = schedule->vehicle_schedules.back().dp + 1;
        }
        do {
            all_stop_vehicle_schedule sched;
            // Calculate ST for each next vehicle in each lane and schedule the vehicle with the lowest ST
            uint64_t lowest_st = 0;
            // Populate Map
            // Find next vehicle for each entry lanelet
            for (const auto &[entry_lane, evs_in_lane] : vehicle_to_be_scheduled_next) {
                // Take first vehicle to be scheduled in lane.
                streets_vehicles::vehicle ev = evs_in_lane.front();
                SPDLOG_DEBUG("Estimating schedule for {0}.", ev._id);
                // Get link lanelet information for ev
                OpenAPI::OAILanelet_info link_lane = get_link_lanelet_info(ev);
                SPDLOG_DEBUG("Link lanelet for {0} is {1}.", ev._id, link_lane.getId());
                // Calculate EST for vehicle
                uint64_t est = estimate_earliest_time_to_stop_bar(ev);
                SPDLOG_DEBUG("EST for vehicle {0} is {1}." ,ev._id, est) ;
                // Store ST value for vehicle
                uint64_t st;
                // If there is a preceding vehicle scheduled in this lane
                if (preceding_vehicle_entry_lane_map.find(ev._cur_lane_id) != preceding_vehicle_entry_lane_map.end()) {
                    // Get preceding vehicle in lane
                    all_stop_vehicle_schedule preceding_veh = preceding_vehicle_entry_lane_map.find(ev._cur_lane_id)->second;
                    SPDLOG_DEBUG("Preceding vehicle schedule in lane {0} is {1}.", preceding_veh.entry_lane, preceding_veh.v_id);
                    // If there is a preceding vehicle the st is calculated as max of EST and preceding vehicle ET plus a time
                    // buffer to account for the time it takes the preceding vehicle to enter the intersection
                    SPDLOG_DEBUG("Preceding vehicle et {0}", preceding_veh.et);
                    st = std::max(est, preceding_veh.et + entering_time_buffer);
                    SPDLOG_DEBUG("Setting st for vehicle {0} to max of {1} , {2}.", ev._id, est, preceding_veh.et + entering_time_buffer);
                }
                // IF there is no preceding vehicle ST == EST
                else {
                    SPDLOG_DEBUG("No proceeding vehicle for {0}", ev._id);
                    st = est;
                }
                // If lowest st has not been set yet. This is currently the lowest st
                if (lowest_st == 0 || lowest_st > st) {
                    lowest_st = st;
                    // Set schedule properties
                    sched.v_id = ev._id;
                    sched.est = est;
                    sched.st = st;
                    sched.entry_lane = ev._entry_lane_id;
                    sched.link_id = ev._link_id;
                    sched.state = streets_vehicles::vehicle_state::EV;
                    sched.access = false;
                    sched.dp = last_departure_index;
                    sched.et = estimate_entering_time_for_ev(schedule->vehicle_schedules, ev, st);
                    // Departure time is equal to entering time + clearance time
                    sched.dt = sched.et + estimate_clearance_time(ev, link_lane);
            
                }
               
            }
            SPDLOG_DEBUG("Found vehicle {0} with lowest stopping time {1} in lane {2}", sched.v_id, sched.st, sched.entry_lane);
            // Add lowest ST to schedule
            schedule->vehicle_schedules.push_back(sched);
            // Increment departure index
            last_departure_index++;
            // Replace previous preceeding vehicle for lane with scheduled vehicle
            if (preceding_vehicle_entry_lane_map.find(sched.entry_lane) != preceding_vehicle_entry_lane_map.end()) {
                preceding_vehicle_entry_lane_map.find(sched.entry_lane)->second = sched;
            }
            else {
                preceding_vehicle_entry_lane_map.try_emplace(sched.entry_lane, sched);
            }
            // Pop vehicle off of list of vehicles to be scheduled for each lane
            vehicle_to_be_scheduled_next.find(sched.entry_lane)->second.pop_front();
            // If pop makes list empty remove map entry
            if (vehicle_to_be_scheduled_next.find(sched.entry_lane)->second.empty()) {
                SPDLOG_DEBUG("All vehicles in approach lanelet {0} have been scheduled!", sched.entry_lane);
                vehicle_to_be_scheduled_next.erase(sched.entry_lane);
            }
            
        }
        while (!vehicle_to_be_scheduled_next.empty());
    }
References streets_vehicles::vehicle::_cur_lane_id, streets_vehicles::vehicle::_entry_lane_id, streets_vehicles::vehicle::_id, streets_vehicles::vehicle::_link_id, streets_vehicle_scheduler::all_stop_vehicle_schedule::access, streets_vehicle_scheduler::distance_comparator(), streets_vehicle_scheduler::all_stop_vehicle_schedule::dp, streets_vehicle_scheduler::all_stop_vehicle_schedule::dt, streets_vehicles::DV, entering_time_buffer, streets_vehicle_scheduler::vehicle_schedule::entry_lane, streets_vehicle_scheduler::all_stop_vehicle_schedule::est, estimate_clearance_time(), estimate_earliest_time_to_stop_bar(), estimate_entering_time_for_ev(), streets_vehicle_scheduler::all_stop_vehicle_schedule::et, streets_vehicles::EV, streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), OpenAPI::OAILanelet_info::getId(), streets_vehicle_scheduler::vehicle_scheduler::intersection_info, streets_vehicle_scheduler::vehicle_schedule::link_id, streets_vehicles::RDV, streets_vehicle_scheduler::all_stop_vehicle_schedule::st, streets_vehicle_scheduler::all_stop_vehicle_schedule::state, and streets_vehicle_scheduler::vehicle_schedule::v_id.
Referenced by schedule_vehicles().
schedule_rdvs()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_rdvs (std::list< streets_vehicles::vehicle > & rdvs, const std::shared_ptr< all_stop_intersection_schedule > & schedule) [private]
Schedule all currently Ready to Depart Vehicles (RDVs). Consider all possible RDV departure orders. Select the one with the least calculated delay. Delay for a given vehicle is the difference between Entering Time and Stopping Time. Method assumes intersection_schedule only populated with DV(s) vehicle_schedules. Method will add vehicle_schedule(s) for each RDV in vector.
Parameters
rdvs vector of unscheduled RDVs
schedule all_stop_intersection_schedule to add RDV scheduling information to.
Definition at line 171 of file all_stop_vehicle_scheduler.cpp.
                                                                                                                                                          {
        // Vector of considered intersection_schedule_options
        std::vector<std::shared_ptr<all_stop_intersection_schedule>> schedule_options;
        // Sort rdvs ascending order based on departure position
        rdvs.sort(departure_position_comparator);
        // Earliest possible departure position for RDVs is last scheduled DV departure position +1
        int starting_departure_position;
        if (!schedule->vehicle_schedules.empty()) {
            starting_departure_position = schedule->vehicle_schedules.back().dp +1;
        }
        else {
            // If no scheduled DVs, first available departure position is 1
            starting_departure_position = 1;
        }
        SPDLOG_DEBUG("Staring the schedule RDVs from departure index {0}!", starting_departure_position);
        // TODO: for 8 possible approaches this may need to be optimized (greedy search)
        do {
            SPDLOG_DEBUG("Considering scheduling options with {0} as first RDV." ,rdvs.front()._id);
            // update schedule option to include already scheduled vehicles
            auto option = std::make_shared<all_stop_intersection_schedule> (*schedule);
            // consider current permutation of RDV departure order
            bool valid_option = consider_departure_position_permutation(rdvs, option, starting_departure_position);
            SPDLOG_DEBUG("Scheduling option is valid : {0}.", valid_option);
            // is permutation valid in terms of flexibility limit? Has any vehicle's departure index changed by more
            // than the current flexibility limit.
            if (valid_option) {
                schedule_options.push_back(option);
            }
        }
        while (std::next_permutation(rdvs.begin(), rdvs.end(), departure_position_comparator));
        // If no valid options were added.
        if (schedule_options.empty()) {
            throw scheduling_exception("There are no valid schedules for RDVs! Please check flexibility_limit setting.");
        }
        // Sort in ascending order based on delay.
        std::sort(schedule_options.begin(), schedule_options.end(), delay_comparator);
        SPDLOG_DEBUG("All all scheduling options, the option with RDV {0} first has the least delay of {1}.",
                                schedule_options.front()->vehicle_schedules[starting_departure_position-1].v_id,
                                schedule_options.front()->get_delay());
       
        // Add scheduled RDVs starting at last scheduled DV position to schedule
        for (const auto &sched : schedule_options.front()->vehicle_schedules){
            // starting at first available departure position for dvs, add rdvs from best option to current schedule
            if (starting_departure_position <= sched.dp) {
                // if rdv was granted access in this schedule add it to the list of RDVs granted access
                if (sched.access) {
                        streets_vehicles::vehicle rdv_granted_access = get_vehicle_with_id(rdvs, sched.v_id);
                        SPDLOG_DEBUG("Added RDV {0} to list of RDVs previously granted access.", rdv_granted_access._id);
                        rdvs_previously_granted_access.push_back(rdv_granted_access);
                }
                schedule->vehicle_schedules.push_back(sched);
                starting_departure_position ++;
            }
        }
        SPDLOG_DEBUG("Schedule for RDVs: \n" + schedule->toCSV());
    }
References streets_vehicles::vehicle::_id, consider_departure_position_permutation(), streets_vehicle_scheduler::delay_comparator(), streets_vehicle_scheduler::departure_position_comparator(), get_vehicle_with_id(), and rdvs_previously_granted_access.
Referenced by schedule_vehicles().
schedule_vehicles()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles, std::shared_ptr< intersection_schedule > & schedule) [override], [virtual]
Method to schedule vehicles. Given and empty intersection_schedule object and a map of vehicles and vehicle ids. This method will populate the intersection schedule with a schedule for each EV,RDV and DV in the vehicle map based on UC 1 scheduling logic to minimize delay for a all way stop intersection.
Parameters
vehicles A map of the vehicles to schedule, with vehicle id as keys
schedule An all_stop_intersection schedule object populated with a vehicle schedule for each EV,RDV and DV in the map.
Implements streets_vehicle_scheduler::vehicle_scheduler.
Definition at line 9 of file all_stop_vehicle_scheduler.cpp.
                                                                                                           {
        
        try
        {
            auto schedule = std::dynamic_pointer_cast<all_stop_intersection_schedule> (i_sched);
            if (vehicles.empty()) {
                SPDLOG_DEBUG("No vehicles to schedule.");
                return;
            }
            // Estimate Vehicles at common time
            estimate_vehicles_at_common_time(vehicles, schedule->timestamp);
            // Create vectors of EVs RDVs and DVs
            std::list<streets_vehicles::vehicle> DVs;
            std::list<streets_vehicles::vehicle> RDVs;
            std::list<streets_vehicles::vehicle> EVs;
            for (const auto &[v_id, veh] : vehicles) {
                if (veh._cur_state == streets_vehicles::vehicle_state::DV) {
                    // Once vehicle is considered as DV it has confirmed that it has received access.
                    if (is_rdv_previously_granted_access(veh)) {
                        remove_rdv_previously_granted_access(veh);
                    }
                    DVs.push_back(veh);
                }
                else if (veh._cur_state == streets_vehicles::vehicle_state::RDV) {
                    // Consider any RDVs previously granted access as a DV
                    if (is_rdv_previously_granted_access(veh)) {
                        DVs.push_back(veh);
                    }
                    else {
                        RDVs.push_back(veh);
                    }
                }
                else if (veh._cur_state == streets_vehicles::vehicle_state::EV) {
                    EVs.push_back(veh);
                }
            }
            
            SPDLOG_DEBUG("Vehicles to schedule are DVs : {0}, RDVs : {1}, EVs {2} ", DVs.size(), RDVs.size(), EVs.size());
            // Schedule DVs
            if (!DVs.empty())
                schedule_dvs(DVs, schedule);
            // Schedule RDVs
            if (!RDVs.empty())
                schedule_rdvs(RDVs, schedule);
            // Schedule EVs
            if (!EVs.empty())
                schedule_evs(EVs, schedule);
        
        }
        catch (const streets_service::streets_configuration_exception &ex) {
            SPDLOG_ERROR("all stop scheduler failure: {0} ", ex.what());
        }
    }
References streets_vehicles::DV, streets_vehicle_scheduler::vehicle_scheduler::estimate_vehicles_at_common_time(), streets_vehicles::EV, is_rdv_previously_granted_access(), streets_vehicles::RDV, remove_rdv_previously_granted_access(), schedule_dvs(), schedule_evs(), and schedule_rdvs().
set_entering_time_buffer()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::set_entering_time_buffer (const uint64_t buffer)
Set the entering time buffer (ms). This value is used to account for the time it takes a vehicle stopped before the stop bar at an entry lane to exit the entry lane and enter the link lane once given access.
Parameters
buffer entering time buff in milliseconds.
set_flexibility_limit()
void streets_vehicle_scheduler::all_stop_vehicle_scheduler::set_flexibility_limit (const int limit)
Set the flexibility limit. This limit controls how much departure position can change for any given vehicle between successive intersection schedule calculations. Each subsequent intersection scheduling calculation may have a slightly different departure order. This value controls how much this departure order can change.A value of 1 represents that vehicles departure position can change by one between two intersection schedules.
Parameters
limit How much can departure position change between schedules for any vehicle.
Definition at line 5 of file all_stop_vehicle_scheduler.cpp.
                                                                            {
        flexibility_limit = limit;
    }
References flexibility_limit.
Member Data Documentation
entering_time_buffer
uint64_t streets_vehicle_scheduler::all_stop_vehicle_scheduler::entering_time_buffer = 0 [private]
Configurable time buffer in milliseconds for estimating the time it takes a vehicle to leave its entry lane and enter the intersection box once granted access to the intersection.
Definition at line 32 of file all_stop_vehicle_scheduler.h.
Referenced by schedule_evs().
flexibility_limit
int streets_vehicle_scheduler::all_stop_vehicle_scheduler::flexibility_limit = 5 [private]
Limits how much departure position for a given vehicle can change from current reported departure position.
Definition at line 36 of file all_stop_vehicle_scheduler.h.
Referenced by consider_departure_position_permutation(), and set_flexibility_limit().
rdvs_previously_granted_access
std::list<streets_vehicles::vehicle> streets_vehicle_scheduler::all_stop_vehicle_scheduler::rdvs_previously_granted_access [private]
A list of RDV vehicles granted access by the vehicle_scheduler, who's updates do not yet reflect they have received access (still considered RDV by all_stop_status_intent_processor). We maintain this list to ensure we do not grant conflicting vehicles access to the intersection simultaneously in back to back scheduling calculations where the first RDV granted access in the first schedule has not yet provided a vehicle update the reflects this access by the time we calculate the second schedule.
Definition at line 27 of file all_stop_vehicle_scheduler.h.
Referenced by is_rdv_previously_granted_access(), remove_rdv_previously_granted_access(), and schedule_rdvs().
The documentation for this class was generated from the following files:
streets_utils/streets_vehicle_scheduler/include/all_stop_vehicle_scheduler.h
streets_utils/streets_vehicle_scheduler/src/all_stop_vehicle_scheduler.cpp