OpenAPI::OAIDefaultApiRequest Class Reference
#include <OAIDefaultApiRequest.h>
Signals
void getConflictLanelets (qint32 link_lanelet_id)
void getIntersectionInfo ()
void listDepartureLanelets ()
void listEntryLanelets ()
void listLinkLanelets ()
Public Member Functions
OAIDefaultApiRequest (QHttpEngine::Socket *s, QSharedPointer< OAIDefaultApiHandler > handler)
virtual ~OAIDefaultApiRequest ()
void getConflictLaneletsRequest (const QString &link_lanelet_id)
void getIntersectionInfoRequest ()
void listDepartureLaneletsRequest ()
void listEntryLaneletsRequest ()
void listLinkLaneletsRequest ()
void getConflictLaneletsResponse (const QList< OAILanelet_info > &res)
void getIntersectionInfoResponse (const OAIIntersection_info &res)
void listDepartureLaneletsResponse (const QList< OAILanelet_info > &res)
void listEntryLaneletsResponse (const QList< OAILanelet_info > &res)
void listLinkLaneletsResponse (const QList< OAILanelet_info > &res)
void getConflictLaneletsError (const QList< OAILanelet_info > &res, QNetworkReply::NetworkError error_type, QString &error_str)
void getIntersectionInfoError (const OAIIntersection_info &res, QNetworkReply::NetworkError error_type, QString &error_str)
void listDepartureLaneletsError (const QList< OAILanelet_info > &res, QNetworkReply::NetworkError error_type, QString &error_str)
void listEntryLaneletsError (const QList< OAILanelet_info > &res, QNetworkReply::NetworkError error_type, QString &error_str)
void listLinkLaneletsError (const QList< OAILanelet_info > &res, QNetworkReply::NetworkError error_type, QString &error_str)
void sendCustomResponse (QByteArray &res, QNetworkReply::NetworkError error_type)
void sendCustomResponse (QIODevice *res, QNetworkReply::NetworkError error_type)
QMap< QString, QString > getRequestHeaders () const
QHttpEngine::Socket * getRawSocket ()
void setResponseHeaders (const QMultiMap< QString, QString > &headers)
Private Member Functions
void setSocketResponseHeaders ()
Private Attributes
QMap< QString, QString > requestHeaders
QMap< QString, QString > responseHeaders
QHttpEngine::Socket * socket
QSharedPointer< OAIDefaultApiHandler > handler
Detailed Description
Definition at line 29 of file OAIDefaultApiRequest.h.
Constructor & Destructor Documentation
OAIDefaultApiRequest()
OpenAPI::OAIDefaultApiRequest::OAIDefaultApiRequest (QHttpEngine::Socket * s, QSharedPointer< OAIDefaultApiHandler > handler)
Definition at line 23 of file OAIDefaultApiRequest.cpp.
                                                                                                         : QObject(s), socket(s), handler(hdl) {
    auto headers = s->headers();
    for(auto itr = headers.begin(); itr != headers.end(); itr++) {
        requestHeaders.insert(QString(itr.key()), QString(itr.value()));
    }
}
References requestHeaders.
 OAIDefaultApiRequest()
OpenAPI::OAIDefaultApiRequest::~OAIDefaultApiRequest () [virtual]
Definition at line 30 of file OAIDefaultApiRequest.cpp.
                                           {
    disconnect(this, nullptr, nullptr, nullptr);
    qDebug() << "OAIDefaultApiRequest::~OAIDefaultApiRequest()";
}
Member Function Documentation
getConflictLanelets
void OpenAPI::OAIDefaultApiRequest::getConflictLanelets (qint32 link_lanelet_id) [signal]
Referenced by getConflictLaneletsRequest().
getConflictLaneletsError()
void OpenAPI::OAIDefaultApiRequest::getConflictLaneletsError (const QList< OAILanelet_info > & res, QNetworkReply::NetworkError error_type, QString & error_str)
Definition at line 156 of file OAIDefaultApiRequest.cpp.
                                                                                                                                              {
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str); // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
getConflictLaneletsRequest()
void OpenAPI::OAIDefaultApiRequest::getConflictLaneletsRequest (const QString & link_lanelet_id)
Definition at line 52 of file OAIDefaultApiRequest.cpp.
                                                                                      {
    qDebug() << "/intersection_model/v1/get_conflict_lanelets/{link_lanelet_id}";
    connect(this, &OAIDefaultApiRequest::getConflictLanelets, handler.data(), &OAIDefaultApiHandler::getConflictLanelets);
    
    qint32 link_lanelet_id;
    fromStringValue(link_lanelet_idstr, link_lanelet_id);
    
    emit getConflictLanelets(link_lanelet_id);
}
References OpenAPI::fromStringValue(), OpenAPI::OAIDefaultApiHandler::getConflictLanelets(), getConflictLanelets(), and handler.
getConflictLaneletsResponse()
void OpenAPI::OAIDefaultApiRequest::getConflictLaneletsResponse (const QList< OAILanelet_info > & res)
Definition at line 110 of file OAIDefaultApiRequest.cpp.
                                                                                       {
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
getIntersectionInfo
void OpenAPI::OAIDefaultApiRequest::getIntersectionInfo () [signal]
Referenced by getIntersectionInfoRequest().
getIntersectionInfoError()
void OpenAPI::OAIDefaultApiRequest::getIntersectionInfoError (const OAIIntersection_info & res, QNetworkReply::NetworkError error_type, QString & error_str)
Definition at line 167 of file OAIDefaultApiRequest.cpp.
                                                                                                                                            {
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str); // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
getIntersectionInfoRequest()
void OpenAPI::OAIDefaultApiRequest::getIntersectionInfoRequest ()
Definition at line 65 of file OAIDefaultApiRequest.cpp.
                                                     {
    qDebug() << "/intersection_model/v1/info";
    connect(this, &OAIDefaultApiRequest::getIntersectionInfo, handler.data(), &OAIDefaultApiHandler::getIntersectionInfo);
    
    emit getIntersectionInfo();
}
References OpenAPI::OAIDefaultApiHandler::getIntersectionInfo(), getIntersectionInfo(), and handler.
getIntersectionInfoResponse()
void OpenAPI::OAIDefaultApiRequest::getIntersectionInfoResponse (const OAIIntersection_info & res)
Definition at line 119 of file OAIDefaultApiRequest.cpp.
                                                                                     {
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
getRawSocket()
QHttpEngine::Socket * OpenAPI::OAIDefaultApiRequest::getRawSocket ()
Definition at line 47 of file OAIDefaultApiRequest.cpp.
                                                     {
    return socket;
}
References socket.
getRequestHeaders()
QMap< QString, QString > OpenAPI::OAIDefaultApiRequest::getRequestHeaders () const
Definition at line 36 of file OAIDefaultApiRequest.cpp.
                                              {
    return requestHeaders;
}
References requestHeaders.
listDepartureLanelets
void OpenAPI::OAIDefaultApiRequest::listDepartureLanelets () [signal]
Referenced by listDepartureLaneletsRequest().
listDepartureLaneletsError()
void OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsError (const QList< OAILanelet_info > & res, QNetworkReply::NetworkError error_type, QString & error_str)
Definition at line 178 of file OAIDefaultApiRequest.cpp.
                                                                                                                                                {
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str); // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
listDepartureLaneletsRequest()
void OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsRequest ()
Definition at line 76 of file OAIDefaultApiRequest.cpp.
                                                       {
    qDebug() << "/intersection_model/v1/departure_lanelets";
    connect(this, &OAIDefaultApiRequest::listDepartureLanelets, handler.data(), &OAIDefaultApiHandler::listDepartureLanelets);
    
    emit listDepartureLanelets();
}
References handler, OpenAPI::OAIDefaultApiHandler::listDepartureLanelets(), and listDepartureLanelets().
listDepartureLaneletsResponse()
void OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsResponse (const QList< OAILanelet_info > & res)
Definition at line 128 of file OAIDefaultApiRequest.cpp.
                                                                                         {
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
listEntryLanelets
void OpenAPI::OAIDefaultApiRequest::listEntryLanelets () [signal]
Referenced by listEntryLaneletsRequest().
listEntryLaneletsError()
void OpenAPI::OAIDefaultApiRequest::listEntryLaneletsError (const QList< OAILanelet_info > & res, QNetworkReply::NetworkError error_type, QString & error_str)
Definition at line 189 of file OAIDefaultApiRequest.cpp.
                                                                                                                                            {
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str); // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
listEntryLaneletsRequest()
void OpenAPI::OAIDefaultApiRequest::listEntryLaneletsRequest ()
Definition at line 87 of file OAIDefaultApiRequest.cpp.
                                                   {
    qDebug() << "/intersection_model/v1/entry_lanelets";
    connect(this, &OAIDefaultApiRequest::listEntryLanelets, handler.data(), &OAIDefaultApiHandler::listEntryLanelets);
    
    emit listEntryLanelets();
}
References handler, OpenAPI::OAIDefaultApiHandler::listEntryLanelets(), and listEntryLanelets().
listEntryLaneletsResponse()
void OpenAPI::OAIDefaultApiRequest::listEntryLaneletsResponse (const QList< OAILanelet_info > & res)
Definition at line 137 of file OAIDefaultApiRequest.cpp.
                                                                                     {
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
listLinkLanelets
void OpenAPI::OAIDefaultApiRequest::listLinkLanelets () [signal]
Referenced by listLinkLaneletsRequest().
listLinkLaneletsError()
void OpenAPI::OAIDefaultApiRequest::listLinkLaneletsError (const QList< OAILanelet_info > & res, QNetworkReply::NetworkError error_type, QString & error_str)
Definition at line 200 of file OAIDefaultApiRequest.cpp.
                                                                                                                                           {
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str); // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
listLinkLaneletsRequest()
void OpenAPI::OAIDefaultApiRequest::listLinkLaneletsRequest ()
Definition at line 98 of file OAIDefaultApiRequest.cpp.
                                                  {
    qDebug() << "/intersection_model/v1/link_lanelets";
    connect(this, &OAIDefaultApiRequest::listLinkLanelets, handler.data(), &OAIDefaultApiHandler::listLinkLanelets);
    
    emit listLinkLanelets();
}
References handler, OpenAPI::OAIDefaultApiHandler::listLinkLanelets(), and listLinkLanelets().
listLinkLaneletsResponse()
void OpenAPI::OAIDefaultApiRequest::listLinkLaneletsResponse (const QList< OAILanelet_info > & res)
Definition at line 146 of file OAIDefaultApiRequest.cpp.
                                                                                    {
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toArray());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}
References setSocketResponseHeaders(), socket, and OpenAPI::toJsonValue().
sendCustomResponse() [1/2]
void OpenAPI::OAIDefaultApiRequest::sendCustomResponse (QByteArray & res, QNetworkReply::NetworkError error_type)
Definition at line 212 of file OAIDefaultApiRequest.cpp.
                                                                                                   {
    Q_UNUSED(error_type); // TODO
    socket->write(res);
    if(socket->isOpen()){
        socket->close();
    }
}
References socket.
sendCustomResponse() [2/2]
void OpenAPI::OAIDefaultApiRequest::sendCustomResponse (QIODevice * res, QNetworkReply::NetworkError error_type)
Definition at line 220 of file OAIDefaultApiRequest.cpp.
                                                                                                 {
    Q_UNUSED(error_type); // TODO
    socket->write(res->readAll());
    if(socket->isOpen()){
        socket->close();
    }
}
References socket.
setResponseHeaders()
void OpenAPI::OAIDefaultApiRequest::setResponseHeaders (const QMultiMap< QString, QString > & headers)
Definition at line 40 of file OAIDefaultApiRequest.cpp.
                                                                                       {
    for(auto itr = headers.begin(); itr != headers.end(); ++itr) {
        responseHeaders.insert(itr.key(), itr.value());
    }
}
References responseHeaders.
setSocketResponseHeaders()
void OpenAPI::OAIDefaultApiRequest::setSocketResponseHeaders () [inline], [private]
Definition at line 82 of file OAIDefaultApiRequest.h.
                                          {
        QHttpEngine::Socket::HeaderMap resHeaders;
        for(auto itr = responseHeaders.begin(); itr != responseHeaders.end(); ++itr) {
            resHeaders.insert(itr.key().toUtf8(), itr.value().toUtf8());
        }
        socket->setHeaders(resHeaders);
    }
References responseHeaders, and socket.
Referenced by getConflictLaneletsError(), getConflictLaneletsResponse(), getIntersectionInfoError(), getIntersectionInfoResponse(), listDepartureLaneletsError(), listDepartureLaneletsResponse(), listEntryLaneletsError(), listEntryLaneletsResponse(), listLinkLaneletsError(), and listLinkLaneletsResponse().
Member Data Documentation
handler
QSharedPointer<OAIDefaultApiHandler> OpenAPI::OAIDefaultApiRequest::handler [private]
Definition at line 80 of file OAIDefaultApiRequest.h.
Referenced by getConflictLaneletsRequest(), getIntersectionInfoRequest(), listDepartureLaneletsRequest(), listEntryLaneletsRequest(), and listLinkLaneletsRequest().
requestHeaders
QMap<QString, QString> OpenAPI::OAIDefaultApiRequest::requestHeaders [private]
Definition at line 77 of file OAIDefaultApiRequest.h.
Referenced by OAIDefaultApiRequest(), and getRequestHeaders().
responseHeaders
QMap<QString, QString> OpenAPI::OAIDefaultApiRequest::responseHeaders [private]
Definition at line 78 of file OAIDefaultApiRequest.h.
Referenced by setResponseHeaders(), and setSocketResponseHeaders().
socket
QHttpEngine::Socket* OpenAPI::OAIDefaultApiRequest::socket [private]
Definition at line 79 of file OAIDefaultApiRequest.h.
Referenced by getConflictLaneletsError(), getConflictLaneletsResponse(), getIntersectionInfoError(), getIntersectionInfoResponse(), getRawSocket(), listDepartureLaneletsError(), listDepartureLaneletsResponse(), listEntryLaneletsError(), listEntryLaneletsResponse(), listLinkLaneletsError(), listLinkLaneletsResponse(), sendCustomResponse(), and setSocketResponseHeaders().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_server_api/src/requests/OAIDefaultApiRequest.h
streets_utils/streets_api/intersection_server_api/src/requests/OAIDefaultApiRequest.cpp