ntcip::ntcip_1202_ext Struct Reference
#include <ntcip_1202_ext.h>
Public Member Functions
bool get_phase_red_status (const int phase_number) const
Returns red state of phase.
bool get_phase_yellow_status (const int phase_number) const
Returns yellow state of phase.
bool get_phase_green_status (const int phase_number) const
Returns green state of phase.
bool get_phase_dont_walk (const int phase_number) const
Returns dont walk state of phase. Only applies to pedestrian phases.
bool get_phase_ped_clear (const int phase_number) const
Returns pedestrian clear state of phase. Only applies to pedestrian phases.
bool get_phase_walk (const int phase_number) const
Returns walk state of phase. Only applies to pedestrian phases.
bool get_overlap_red_status (const int phase_number) const
Returns red overlap state of phase.
bool get_overlap_yellow_status (const int phase_number) const
Returns yellow overlap state of phase.
bool get_overlap_green_status (const int phase_number) const
Returns green overlap state of phase.
bool get_phase_flashing_status (const int phase_number) const
Returns flashing state of phase.
bool get_overlap_flashing_status (const int phase_number) const
Returns flashing state of overlap phase.
bool get_spat_pedestrian_call (const int phase_number) const
Returns state of pedestrian calls on phase.
bool get_spat_pedestrian_detect (const int phase_number) const
Returns state of pedestrian detect on phase.
uint32_t get_timestamp_seconds_of_day () const
Returns 3 bytes translated into seconds of the UTC day message timestamp.
ntcip_1202_ext_phasetime & get_phasetime (const int phase_number)
Returns reference to ntcip_1202_ext_phasetime of phase.
std::string to_string () const
Returns std::string representation of ntcip_1202_ext message including phase_times array.
Public Attributes
int8_t header = 0
header
int8_t num_of_phases = 0
number of phases
ntcip_1202_ext_phasetime phase_times [16]
phase_time object for each phase
uint16_t phase_status_group_reds = 0
int where each bit indicates whether that phase is red (1-16)
uint16_t phase_status_group_yellows = 0
int where each bit indicates whether that phase is yellow (1-16)
uint16_t phase_status_group_greens = 0
int where each bit indicates whether that phase is green (1-16)
uint16_t phase_status_group_dont_walks = 0
int where each bit indicates whether that phase is dont walk (Pedestrian Phases) (1-16)
uint16_t phase_status_group_ped_clears = 0
int where each bit indicates whether that phase is pedestrian clear (Pedestrian Phases) (1-16)
uint16_t phase_status_group_walks = 0
int where each bit indicates whether that phase is walk (Pedestrian Phases) (1-16)
uint16_t overlap_status_group_reds = 0
int where each bit indicates whether that overlap is red (1-16)
uint16_t overlap_status_group_yellows = 0
int where each bit indicates whether that overlap is yellow (1-16)
uint16_t overlap_status_group_greens = 0
int where each bit indicates whether that overlap is green (1-16)
uint16_t flashing_output_phase_status = 0
int where each bit indicates whether that phase is flashing (1-16)
uint16_t flashing_output_overlap_status = 0
int where each bit indicates whether that overlap is flashing (1-16)
uint8_t spat_intersection_status = 0
bit string for intersection status
uint8_t timebase_asc_action_status = 0
current action plan
uint8_t spat_discontinuous_change_flag = 0
upper 5 bits are msg version
uint8_t spat_message_seq_counter = 0
lower byte of up-time in deciseconds
u_char spat_timestamp_second_byte1 = 0
u_char spat_timestamp_second_byte2 = 0
u_char spat_timestamp_second_byte3 = 0
uint16_t spat_timestamp_msec = 0
milliseconds of current second
uint16_t spat_pedestrian_call = 0
int where each bit indicates whether there is a pedestrian call on a phase (Pedestrian Phases) (1-16)
uint16_t spat_pedestrian_detect = 0
int where each bit indicates whether there is a pedestrian detect on a phase (Pedestrian Phases) (1-16)
Detailed Description
Definition at line 12 of file ntcip_1202_ext.h.
Member Function Documentation
get_overlap_flashing_status()
bool ntcip::ntcip_1202_ext::get_overlap_flashing_status (const int phase_number) const
Returns flashing state of overlap phase.
Parameters
phase_number
Returns
true
false
Definition at line 78 of file ntcip_1202_ext.cpp.
                                                                                 {
        return (bool)((ntohs(flashing_output_overlap_status) >> (phase_number -1)) &0x01);
    }
References flashing_output_overlap_status, and phase_number.
Referenced by to_string().
get_overlap_green_status()
bool ntcip::ntcip_1202_ext::get_overlap_green_status (const int phase_number) const
Returns green overlap state of phase.
Parameters
phase_number
Returns
true
false
Definition at line 70 of file ntcip_1202_ext.cpp.
                                                                              {
        return (bool)((ntohs(overlap_status_group_greens) >> (phase_number - 1)) & 0x01);
    }
References overlap_status_group_greens, and phase_number.
Referenced by to_string().
get_overlap_red_status()
bool ntcip::ntcip_1202_ext::get_overlap_red_status (const int phase_number) const
Returns red overlap state of phase.
Parameters
phase_number
Returns
true
false
Definition at line 62 of file ntcip_1202_ext.cpp.
                                                                            {
        return (bool)((ntohs(overlap_status_group_reds) >> (phase_number - 1)) & 0x01);
    }
References overlap_status_group_reds, and phase_number.
Referenced by to_string().
get_overlap_yellow_status()
bool ntcip::ntcip_1202_ext::get_overlap_yellow_status (const int phase_number) const
Returns yellow overlap state of phase.
Parameters
phase_number
Returns
true
false
Definition at line 66 of file ntcip_1202_ext.cpp.
                                                                               {
        return (bool)((ntohs(overlap_status_group_yellows) >> (phase_number - 1)) & 0x01);
    }
References overlap_status_group_yellows, and phase_number.
Referenced by to_string().
get_phase_dont_walk()
bool ntcip::ntcip_1202_ext::get_phase_dont_walk (const int phase_number) const
Returns dont walk state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase.
Returns
true if phase is dont walk.
false if phase is not dont walk.
Definition at line 50 of file ntcip_1202_ext.cpp.
                                                                         {
        return (bool)((ntohs(phase_status_group_dont_walks) >> (phase_number - 1)) & 0x01);
    }
References phase_number, and phase_status_group_dont_walks.
Referenced by to_string().
get_phase_flashing_status()
bool ntcip::ntcip_1202_ext::get_phase_flashing_status (const int phase_number) const
Returns flashing state of phase.
Parameters
phase_number of phase.
Returns
true if phase is flashing.
false if phase is not flashing.
Definition at line 74 of file ntcip_1202_ext.cpp.
                                                                               {
        return (bool)((ntohs(flashing_output_phase_status) >> (phase_number -1)) &0x01);
    }
References flashing_output_phase_status, and phase_number.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
get_phase_green_status()
bool ntcip::ntcip_1202_ext::get_phase_green_status (const int phase_number) const
Returns green state of phase.
Parameters
phase_number of phase.
Returns
true if phase is green.
false if phase is not green.
Definition at line 46 of file ntcip_1202_ext.cpp.
                                                                            {
        return (bool)((ntohs(phase_status_group_greens) >> (phase_number - 1)) & 0x01);
    }
References phase_number, and phase_status_group_greens.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
get_phase_ped_clear()
bool ntcip::ntcip_1202_ext::get_phase_ped_clear (const int phase_number) const
Returns pedestrian clear state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase.
Returns
true if phase is pedestrian clear.
false if phase is not pedestrian clear.
Definition at line 54 of file ntcip_1202_ext.cpp.
                                                                         {
        return (bool)((ntohs(phase_status_group_ped_clears) >> (phase_number - 1)) & 0x01);
    }
References phase_number, and phase_status_group_ped_clears.
Referenced by to_string().
get_phase_red_status()
bool ntcip::ntcip_1202_ext::get_phase_red_status (const int phase_number) const
Returns red state of phase.
Parameters
phase_number of phase.
Returns
true if phase is red.
false if phase is not red.
Definition at line 38 of file ntcip_1202_ext.cpp.
                                                                          {
        return (bool)((ntohs(phase_status_group_reds) >> (phase_number - 1)) & 0x01);
    }
References phase_number, and phase_status_group_reds.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
get_phase_walk()
bool ntcip::ntcip_1202_ext::get_phase_walk (const int phase_number) const
Returns walk state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase/
Returns
true if phase is walk.
false if phase is not walk.
Definition at line 58 of file ntcip_1202_ext.cpp.
                                                                    {
        return (bool)((ntohs(phase_status_group_walks) >> (phase_number - 1)) & 0x01);
    }
References phase_number, and phase_status_group_walks.
Referenced by to_string().
get_phase_yellow_status()
bool ntcip::ntcip_1202_ext::get_phase_yellow_status (const int phase_number) const
Returns yellow state of phase.
Parameters
phase_number of phase.
Returns
true if phase is yellow.
false if phase is not yellow.
Definition at line 42 of file ntcip_1202_ext.cpp.
                                                                             {
        return (bool)((ntohs(phase_status_group_yellows) >> (phase_number - 1))& 0x01);
    }
References phase_number, and phase_status_group_yellows.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
get_phasetime()
ntcip_1202_ext_phasetime & ntcip::ntcip_1202_ext::get_phasetime (const int phase_number)
Returns reference to ntcip_1202_ext_phasetime of phase.
Parameters
phase_number of phase
Returns
ntcip_1202_ext_phasetime&
Definition at line 94 of file ntcip_1202_ext.cpp.
                                                                                  {
        for (auto i = 0 ; i < 16; i++) {
            if (phase_times[i].phase_number == phase_number) {
                return phase_times[i];
            }
        }
        throw signal_phase_and_timing::signal_phase_and_timing_exception("Could not find phasetime for phase number " + std::to_string(phase_number) + "!");
    }
References simulate_bsm::i, phase_number, phase_times, and to_string().
Referenced by signal_phase_and_timing::intersection_state::update_movement_state().
get_spat_pedestrian_call()
bool ntcip::ntcip_1202_ext::get_spat_pedestrian_call (const int phase_number) const
Returns state of pedestrian calls on phase.
Parameters
phase_number
Returns
true
false
Definition at line 82 of file ntcip_1202_ext.cpp.
                                                                              {
        return (bool)((ntohs(spat_pedestrian_call) >> (phase_number -1)) &0x01);
    }
References phase_number, and spat_pedestrian_call.
Referenced by to_string().
get_spat_pedestrian_detect()
bool ntcip::ntcip_1202_ext::get_spat_pedestrian_detect (const int phase_number) const
Returns state of pedestrian detect on phase.
Parameters
phase_number
Returns
true
false
Definition at line 86 of file ntcip_1202_ext.cpp.
                                                                                {
        return (bool)((ntohs(spat_pedestrian_detect) >> (phase_number -1)) &0x01);
    }
References phase_number, and spat_pedestrian_detect.
Referenced by to_string().
get_timestamp_seconds_of_day()
uint32_t ntcip::ntcip_1202_ext::get_timestamp_seconds_of_day () const
Returns 3 bytes translated into seconds of the UTC day message timestamp.
Returns
uint32_t message timestamp in seconds of UTC day
Definition at line 90 of file ntcip_1202_ext.cpp.
                                                                {
        return (uint32_t)(spat_timestamp_second_byte1 << 16) | (spat_timestamp_second_byte2 << 8) | spat_timestamp_second_byte3;
    }
References spat_timestamp_second_byte1, spat_timestamp_second_byte2, and spat_timestamp_second_byte3.
Referenced by to_string(), and signal_phase_and_timing::spat::update().
to_string()
std::string ntcip::ntcip_1202_ext::to_string () const
Returns std::string representation of ntcip_1202_ext message including phase_times array.
Returns
std::string
Definition at line 5 of file ntcip_1202_ext.cpp.
                                             {
        std::string message;
        message.append("header:" + std::to_string(header) + "\n");
        message.append("num_of_phases: " + std::to_string(num_of_phases) + "\n");
        for (const auto &phase_time : phase_times) {
            message.append(phase_time.to_string());
            message.append("phase_status_red: " + std::to_string(get_phase_red_status(phase_time.phase_number)) + "\n");
            message.append("phase_status_yellow: " + std::to_string(get_phase_yellow_status(phase_time.phase_number)) + "\n");
            message.append("phase_status_green: " + std::to_string(get_phase_green_status(phase_time.phase_number)) + "\n");
            message.append("phase_status_dont_walk: " + std::to_string(get_phase_dont_walk(phase_time.phase_number)) + "\n");
            message.append("phase_status_ped_clear: " + std::to_string(get_phase_ped_clear(phase_time.phase_number)) + "\n");
            message.append("phase_status_walk: " + std::to_string(get_phase_walk(phase_time.phase_number)) + "\n");
            message.append("overlap_status_red: " + std::to_string(get_overlap_red_status(phase_time.phase_number)) + "\n");
            message.append("overlap_status_yellow: " + std::to_string(get_overlap_yellow_status(phase_time.phase_number)) + "\n");
            message.append("overlap_status_green: " + std::to_string(get_overlap_green_status(phase_time.phase_number)) + "\n");
            message.append("flashing_phase_status: " + std::to_string(get_phase_flashing_status(phase_time.phase_number)) + "\n");
            message.append("flashing_overlap_status: " + std::to_string(get_overlap_flashing_status(phase_time.phase_number)) + "\n");
            message.append("spat_pedestrian_call: " + std::to_string(get_spat_pedestrian_call(phase_time.phase_number)) + "\n");
            message.append("spat_pedestrian_detect: " + std::to_string(get_spat_pedestrian_detect(phase_time.phase_number)) + "\n");
        }
        
        message.append("spat_intersection_status: " + std::to_string(spat_intersection_status) + "\n");
        message.append("timebase_asc_action_status: " + std::to_string(timebase_asc_action_status) + "\n");
        message.append("spat_discontinuous_change_flag: " + std::to_string(spat_discontinuous_change_flag) + "\n");
        message.append("spat_message_seq_counter: " + std::to_string(spat_message_seq_counter) + "\n");
        message.append("spat_timestamp_second_of_day: " + std::to_string(get_timestamp_seconds_of_day()) + "\n");
        message.append("spat_timestamp_msec: " + std::to_string(ntohs(spat_timestamp_msec)) + "\n");
        
        return message;
    }
References get_overlap_flashing_status(), get_overlap_green_status(), get_overlap_red_status(), get_overlap_yellow_status(), get_phase_dont_walk(), get_phase_flashing_status(), get_phase_green_status(), get_phase_ped_clear(), get_phase_red_status(), get_phase_walk(), get_phase_yellow_status(), get_spat_pedestrian_call(), get_spat_pedestrian_detect(), get_timestamp_seconds_of_day(), header, num_of_phases, phase_times, spat_discontinuous_change_flag, spat_intersection_status, spat_message_seq_counter, spat_timestamp_msec, timebase_asc_action_status, and to_string().
Member Data Documentation
flashing_output_overlap_status
uint16_t ntcip::ntcip_1202_ext::flashing_output_overlap_status = 0
int where each bit indicates whether that overlap is flashing (1-16)
Definition at line 41 of file ntcip_1202_ext.h.
Referenced by get_overlap_flashing_status().
flashing_output_phase_status
uint16_t ntcip::ntcip_1202_ext::flashing_output_phase_status = 0
int where each bit indicates whether that phase is flashing (1-16)
Definition at line 39 of file ntcip_1202_ext.h.
Referenced by get_phase_flashing_status().
header
int8_t ntcip::ntcip_1202_ext::header = 0
header
Definition at line 15 of file ntcip_1202_ext.h.
Referenced by to_string().
num_of_phases
int8_t ntcip::ntcip_1202_ext::num_of_phases = 0
number of phases
Definition at line 17 of file ntcip_1202_ext.h.
Referenced by to_string().
overlap_status_group_greens
uint16_t ntcip::ntcip_1202_ext::overlap_status_group_greens = 0
int where each bit indicates whether that overlap is green (1-16)
Definition at line 37 of file ntcip_1202_ext.h.
Referenced by get_overlap_green_status().
overlap_status_group_reds
uint16_t ntcip::ntcip_1202_ext::overlap_status_group_reds = 0
int where each bit indicates whether that overlap is red (1-16)
Definition at line 33 of file ntcip_1202_ext.h.
Referenced by get_overlap_red_status().
overlap_status_group_yellows
uint16_t ntcip::ntcip_1202_ext::overlap_status_group_yellows = 0
int where each bit indicates whether that overlap is yellow (1-16)
Definition at line 35 of file ntcip_1202_ext.h.
Referenced by get_overlap_yellow_status().
phase_status_group_dont_walks
uint16_t ntcip::ntcip_1202_ext::phase_status_group_dont_walks = 0
int where each bit indicates whether that phase is dont walk (Pedestrian Phases) (1-16)
Definition at line 27 of file ntcip_1202_ext.h.
Referenced by get_phase_dont_walk().
phase_status_group_greens
uint16_t ntcip::ntcip_1202_ext::phase_status_group_greens = 0
int where each bit indicates whether that phase is green (1-16)
Definition at line 25 of file ntcip_1202_ext.h.
Referenced by get_phase_green_status().
phase_status_group_ped_clears
uint16_t ntcip::ntcip_1202_ext::phase_status_group_ped_clears = 0
int where each bit indicates whether that phase is pedestrian clear (Pedestrian Phases) (1-16)
Definition at line 29 of file ntcip_1202_ext.h.
Referenced by get_phase_ped_clear().
phase_status_group_reds
uint16_t ntcip::ntcip_1202_ext::phase_status_group_reds = 0
int where each bit indicates whether that phase is red (1-16)
Definition at line 21 of file ntcip_1202_ext.h.
Referenced by get_phase_red_status().
phase_status_group_walks
uint16_t ntcip::ntcip_1202_ext::phase_status_group_walks = 0
int where each bit indicates whether that phase is walk (Pedestrian Phases) (1-16)
Definition at line 31 of file ntcip_1202_ext.h.
Referenced by get_phase_walk().
phase_status_group_yellows
uint16_t ntcip::ntcip_1202_ext::phase_status_group_yellows = 0
int where each bit indicates whether that phase is yellow (1-16)
Definition at line 23 of file ntcip_1202_ext.h.
Referenced by get_phase_yellow_status().
phase_times
ntcip_1202_ext_phasetime ntcip::ntcip_1202_ext::phase_times[16]
phase_time object for each phase
Definition at line 19 of file ntcip_1202_ext.h.
Referenced by get_phasetime(), and to_string().
spat_discontinuous_change_flag
uint8_t ntcip::ntcip_1202_ext::spat_discontinuous_change_flag = 0
upper 5 bits are msg version
Definition at line 47 of file ntcip_1202_ext.h.
Referenced by to_string().
spat_intersection_status
uint8_t ntcip::ntcip_1202_ext::spat_intersection_status = 0
bit string for intersection status
Definition at line 43 of file ntcip_1202_ext.h.
Referenced by to_string(), and signal_phase_and_timing::spat::update_intersection_state().
spat_message_seq_counter
uint8_t ntcip::ntcip_1202_ext::spat_message_seq_counter = 0
lower byte of up-time in deciseconds
Definition at line 49 of file ntcip_1202_ext.h.
Referenced by to_string().
spat_pedestrian_call
uint16_t ntcip::ntcip_1202_ext::spat_pedestrian_call = 0
int where each bit indicates whether there is a pedestrian call on a phase (Pedestrian Phases) (1-16)
Definition at line 57 of file ntcip_1202_ext.h.
Referenced by get_spat_pedestrian_call().
spat_pedestrian_detect
uint16_t ntcip::ntcip_1202_ext::spat_pedestrian_detect = 0
int where each bit indicates whether there is a pedestrian detect on a phase (Pedestrian Phases) (1-16)
Definition at line 59 of file ntcip_1202_ext.h.
Referenced by get_spat_pedestrian_detect().
spat_timestamp_msec
uint16_t ntcip::ntcip_1202_ext::spat_timestamp_msec = 0
milliseconds of current second
Definition at line 55 of file ntcip_1202_ext.h.
Referenced by to_string(), and signal_phase_and_timing::spat::update().
spat_timestamp_second_byte1
u_char ntcip::ntcip_1202_ext::spat_timestamp_second_byte1 = 0
3 bytes for second of the UTC day
Definition at line 51 of file ntcip_1202_ext.h.
Referenced by get_timestamp_seconds_of_day().
spat_timestamp_second_byte2
u_char ntcip::ntcip_1202_ext::spat_timestamp_second_byte2 = 0
Definition at line 52 of file ntcip_1202_ext.h.
Referenced by get_timestamp_seconds_of_day().
spat_timestamp_second_byte3
u_char ntcip::ntcip_1202_ext::spat_timestamp_second_byte3 = 0
Definition at line 53 of file ntcip_1202_ext.h.
Referenced by get_timestamp_seconds_of_day().
timebase_asc_action_status
uint8_t ntcip::ntcip_1202_ext::timebase_asc_action_status = 0
current action plan
Definition at line 45 of file ntcip_1202_ext.h.
Referenced by to_string().
The documentation for this struct was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/ntcip_1202_ext.h
streets_utils/streets_signal_phase_and_timing/src/models/ntcip_1202_ext.cpp