message_services::models::vehicle_status_intent Class Reference
#include <vehicle_status_intent.h>
Public Member Functions
vehicle_status_intent ()
virtual ~vehicle_status_intent ()
virtual void fromJsonObject (const rapidjson::Value &obj)
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const
std::string getVehicle_id () const
void setVehicle_id (std::string vehicle_id)
double getCur_speed () const
void setCur_speed (double cur_speed)
double getCur_accel () const
void setCur_accel (double cur_accel)
std::vector< est_path_t > getEst_path_v () const
void setEst_path_v (std::vector< est_path_t > est_path_v)
long getActual_enter_timestamp () const
void setActual_enter_timestamp (long actual_enter_timestamp)
long getActual_stop_timestamp () const
void setActual_stop_timestamp (long actual_stop_timestamp)
long getEarliest_stop_timestamp () const
void setEarliest_stop_timestamp (long earliest_stop_timestamp)
int64_t getLink_lanelet_id () const
void setLink_lanelet_id (int64_t link_lanelet_id)
int64_t getDest_lanelet_id () const
void setDest_lanelet_id (int64_t dest_lanelet_id)
int64_t getEnter_lanelet_id () const
void setEnter_lanelet_id (int64_t enter_lanelet_id)
double getCur_distance () const
void setCur_distance (double cur_distance)
int64_t getCur_lanelet_id () const
void setCur_lanelet_id (int64_t cur_lanelet_id)
bool getIs_allowed () const
void setIs_allowed (bool is_allowed)
long getDepart_position () const
void setDepart_position (long depart_position)
double getMinimum_gap () const
void setMinimum_gap (double minimum_gap)
uint32_t getVehicle_length () const
void setVehicle_length (uint32_t vehicle_length)
double getMax_decel () const
void setMax_decel (double max_decel)
double getMax_accel () const
void setMax_accel (double max_accel)
double getReact_timestamp () const
void setReact_timestamp (double react_timestamp)
long getActual_depart_timestamp () const
void setActual_depart_timestamp (long actual_depart_timestamp)
long getCur_timestamp () const
void setCur_timestamp (long cur_timestamp)
std::string getBsm_id ()
void setBsm_id (std::string bsm_id)
std::string GetTurn_direction () const
void SetTurn_direction (std::string turn_direction)
Private Attributes
std::string vehicle_id
std::string bsm_id
std::string turn_direction = `NA`
double cur_speed
double cur_accel
long cur_timestamp
double react_timestamp
double max_accel
double max_decel
uint32_t vehicle_length
double minimum_gap
long depart_position
bool is_allowed
int64_t cur_lanelet_id
double cur_distance
int64_t enter_lanelet_id
int64_t dest_lanelet_id
int64_t link_lanelet_id
long earliest_stop_timestamp
long actual_stop_timestamp
long actual_enter_timestamp
long actual_depart_timestamp
std::vector< est_path_t > est_path_v
Friends
std::ostream & operator<< (std::ostream &out, vehicle_status_intent &vehicle_status_intent_obj)
Detailed Description
Definition at line 22 of file vehicle_status_intent.h.
Constructor & Destructor Documentation
vehicle_status_intent()
message_services::models::vehicle_status_intent::vehicle_status_intent ()
Definition at line 12 of file vehicle_status_intent.cpp.
                                                     : vehicle_id(""), vehicle_length(0), is_allowed(false), cur_accel(0),
                                                         cur_distance(0), cur_lanelet_id(0), cur_speed(0), react_timestamp(0),
                                                         max_accel(0), max_decel(0), minimum_gap(0), depart_position(0), cur_timestamp(0),
                                                         enter_lanelet_id(0), dest_lanelet_id(0), link_lanelet_id(0), actual_stop_timestamp(0),
                                                         earliest_stop_timestamp(0), actual_enter_timestamp(0), actual_depart_timestamp(0)
        {
        }
 vehicle_status_intent()
message_services::models::vehicle_status_intent::~vehicle_status_intent () [virtual]
Definition at line 20 of file vehicle_status_intent.cpp.
{}
Member Function Documentation
asJsonObject()
bool message_services::models::vehicle_status_intent::asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > * writer) const [virtual]
Implements message_services::models::baseMessage.
Definition at line 84 of file vehicle_status_intent.cpp.
        {
            try
            {
                writer->StartObject();
                writer->String("metadata");
                writer->StartObject();
                writer->String("timestamp");
                writer->Uint64(this->getCur_timestamp());
                writer->EndObject();
                writer->String("payload");
                writer->StartObject();
                writer->String("v_id");
                writer->String(this->getVehicle_id().c_str());
                writer->String("v_length");
                writer->Uint64(this->getVehicle_length());
                writer->String("cur_speed");
                writer->Double(this->getCur_speed());
                writer->String("cur_accel");
                writer->Double(this->getCur_accel());
                writer->String("react_t");
                writer->Double(this->getReact_timestamp());
                writer->String("max_accel");
                writer->Double(this->getMax_accel());
                writer->String("max_decel");
                writer->Double(this->getMax_decel());
                writer->String("min_gap");
                writer->Double(this->getMinimum_gap());
                writer->String("depart_pos");
                writer->Uint64(this->getDepart_position());
                writer->String("is_allowed");
                writer->Bool(this->getIs_allowed());
                writer->String("cur_lane_id");
                writer->Int64(this->getCur_lanelet_id());
                writer->String("cur_ds");
                writer->Double(this->getCur_distance());
                writer->String("entry_lane_id");
                writer->Int64(this->getEnter_lanelet_id());
                writer->String("dest_lane_id");
                writer->Int64(this->getDest_lanelet_id());
                writer->String("link_lane_id");
                writer->Int64(this->getLink_lanelet_id());
                //Vehicle turn direction at the intersection
                writer->String("direction");
                writer->String(this->GetTurn_direction().c_str());
                if (this->est_path_v.size() > 0)
                {
                    writer->String("est_paths");
                    writer->StartArray();
                    for (auto est_path_item : this->getEst_path_v())
                    {
                        writer->StartObject();
                        //Lanelet id
                        writer->String("id");
                        writer->Int64(est_path_item.lanelet_id);
                        //Distance to the end of the lanelet where the future position is
                        writer->String("ds");
                        writer->Double(est_path_item.distance);
                        //Timestamp when the future position is
                        writer->String("ts");
                        writer->Uint64(est_path_item.timestamp);
                        writer->EndObject();
                    }
                    writer->EndArray();
                }
                writer->EndObject();
                writer->EndObject();
                return true;
            }
            catch (std::exception &ex)
            {
                SPDLOG_INFO("vehicle_status_intent model: asJsonObject error. ", ex.what());
                return false;
            }
        }
References est_path_v, getCur_accel(), getCur_distance(), getCur_lanelet_id(), getCur_speed(), getCur_timestamp(), getDepart_position(), getDest_lanelet_id(), getEnter_lanelet_id(), getEst_path_v(), getIs_allowed(), getLink_lanelet_id(), getMax_accel(), getMax_decel(), getMinimum_gap(), getReact_timestamp(), GetTurn_direction(), getVehicle_id(), and getVehicle_length().
fromJsonObject()
void message_services::models::vehicle_status_intent::fromJsonObject (const rapidjson::Value & obj) [virtual]
Implements message_services::models::baseMessage.
Definition at line 22 of file vehicle_status_intent.cpp.
        {
            if (obj.IsObject())
            {
                for (rapidjson::Value::ConstMemberIterator obj_itr = obj.MemberBegin(); obj_itr != obj.MemberEnd(); obj_itr++)
                {
                    if (obj_itr->value.IsObject() && std::string(obj_itr->name.GetString()) == std::string("temprary_id"))
                    {
                        for (rapidjson::Value::ConstMemberIterator obj_itr = obj_itr->value.MemberBegin(); obj_itr != obj_itr->value.MemberEnd(); obj_itr++)
                        {
                            if (std::string(obj_itr->name.GetString()) == std::string("v_id"))
                            {
                                setVehicle_id(obj_itr->value.GetString());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("cur_speed"))
                            {
                                setCur_speed(obj_itr->value.GetDouble());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("cur_timestamp"))
                            {
                                setCur_timestamp(obj_itr->value.GetDouble());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("is_allowed_int"))
                            {
                                setIs_allowed(obj_itr->value.GetBool());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("min_gap"))
                            {
                                setMinimum_gap(obj_itr->value.GetDouble());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("v_length"))
                            {
                                setVehicle_length(obj_itr->value.GetUint());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("cur_accel"))
                            {
                                setCur_accel(obj_itr->value.GetDouble());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("max_decel"))
                            {
                                setMax_decel(obj_itr->value.GetDouble());
                            }
                            if (std::string(obj_itr->name.GetString()) == std::string("max_accel"))
                            {
                                setMax_accel(obj_itr->value.GetDouble());
                            }
                            //Todo: Complete my other fields
                        }
                    }
                }
            }
        }
References setCur_accel(), setCur_speed(), setCur_timestamp(), setIs_allowed(), setMax_accel(), setMax_decel(), setMinimum_gap(), setVehicle_id(), and setVehicle_length().
getActual_depart_timestamp()
long message_services::models::vehicle_status_intent::getActual_depart_timestamp () const
Definition at line 185 of file vehicle_status_intent.cpp.
        {
            return this->actual_depart_timestamp;
        }
References actual_depart_timestamp.
getActual_enter_timestamp()
long message_services::models::vehicle_status_intent::getActual_enter_timestamp () const
Definition at line 210 of file vehicle_status_intent.cpp.
        {
            return this->actual_enter_timestamp;
        }
References actual_enter_timestamp.
getActual_stop_timestamp()
long message_services::models::vehicle_status_intent::getActual_stop_timestamp () const
Definition at line 219 of file vehicle_status_intent.cpp.
        {
            return this->actual_stop_timestamp;
        }
References actual_stop_timestamp.
getBsm_id()
std::string message_services::models::vehicle_status_intent::getBsm_id ()
Definition at line 352 of file vehicle_status_intent.cpp.
        {
            return this->bsm_id;
        }
References bsm_id.
getCur_accel()
double message_services::models::vehicle_status_intent::getCur_accel () const
Definition at line 193 of file vehicle_status_intent.cpp.
        {
            return this->cur_accel;
        }
References cur_accel.
Referenced by asJsonObject().
getCur_distance()
double message_services::models::vehicle_status_intent::getCur_distance () const
Definition at line 271 of file vehicle_status_intent.cpp.
        {
            return this->cur_distance;
        }
References cur_distance.
Referenced by asJsonObject().
getCur_lanelet_id()
int64_t message_services::models::vehicle_status_intent::getCur_lanelet_id () const
Definition at line 280 of file vehicle_status_intent.cpp.
        {
            return this->cur_lanelet_id;
        }
References cur_lanelet_id.
Referenced by asJsonObject().
getCur_speed()
double message_services::models::vehicle_status_intent::getCur_speed () const
Definition at line 176 of file vehicle_status_intent.cpp.
        {
            return this->cur_speed;
        }
References cur_speed.
Referenced by asJsonObject().
getCur_timestamp()
long message_services::models::vehicle_status_intent::getCur_timestamp () const
Definition at line 245 of file vehicle_status_intent.cpp.
        {
            return this->cur_timestamp;
        }
References cur_timestamp.
Referenced by asJsonObject().
getDepart_position()
long message_services::models::vehicle_status_intent::getDepart_position () const
Definition at line 298 of file vehicle_status_intent.cpp.
        {
            return this->depart_position;
        }
References depart_position.
Referenced by asJsonObject().
getDest_lanelet_id()
int64_t message_services::models::vehicle_status_intent::getDest_lanelet_id () const
Definition at line 253 of file vehicle_status_intent.cpp.
        {
            return this->dest_lanelet_id;
        }
References dest_lanelet_id.
Referenced by asJsonObject().
getEarliest_stop_timestamp()
long message_services::models::vehicle_status_intent::getEarliest_stop_timestamp () const
Definition at line 228 of file vehicle_status_intent.cpp.
        {
            return this->earliest_stop_timestamp;
        }
References earliest_stop_timestamp.
getEnter_lanelet_id()
int64_t message_services::models::vehicle_status_intent::getEnter_lanelet_id () const
Definition at line 262 of file vehicle_status_intent.cpp.
        {
            return this->enter_lanelet_id;
        }
References enter_lanelet_id.
Referenced by asJsonObject().
getEst_path_v()
std::vector< est_path_t > message_services::models::vehicle_status_intent::getEst_path_v () const
Definition at line 201 of file vehicle_status_intent.cpp.
        {
            return this->est_path_v;
        }
References est_path_v.
Referenced by asJsonObject().
getIs_allowed()
bool message_services::models::vehicle_status_intent::getIs_allowed () const
Definition at line 289 of file vehicle_status_intent.cpp.
        {
            return this->is_allowed;
        }
References is_allowed.
Referenced by asJsonObject().
getLink_lanelet_id()
int64_t message_services::models::vehicle_status_intent::getLink_lanelet_id () const
Definition at line 237 of file vehicle_status_intent.cpp.
        {
            return this->link_lanelet_id;
        }
References link_lanelet_id.
Referenced by asJsonObject().
getMax_accel()
double message_services::models::vehicle_status_intent::getMax_accel () const
Definition at line 334 of file vehicle_status_intent.cpp.
        {
            return this->max_accel;
        }
References max_accel.
Referenced by asJsonObject().
getMax_decel()
double message_services::models::vehicle_status_intent::getMax_decel () const
Definition at line 325 of file vehicle_status_intent.cpp.
        {
            return this->max_decel;
        }
References max_decel.
Referenced by asJsonObject().
getMinimum_gap()
double message_services::models::vehicle_status_intent::getMinimum_gap () const
Definition at line 307 of file vehicle_status_intent.cpp.
        {
            return this->minimum_gap;
        }
References minimum_gap.
Referenced by asJsonObject().
getReact_timestamp()
double message_services::models::vehicle_status_intent::getReact_timestamp () const
Definition at line 343 of file vehicle_status_intent.cpp.
        {
            return this->react_timestamp;
        }
References react_timestamp.
Referenced by asJsonObject().
GetTurn_direction()
std::string message_services::models::vehicle_status_intent::GetTurn_direction () const
Definition at line 362 of file vehicle_status_intent.cpp.
        {
            return this->turn_direction;
        }
References turn_direction.
Referenced by asJsonObject().
getVehicle_id()
std::string message_services::models::vehicle_status_intent::getVehicle_id () const
Definition at line 168 of file vehicle_status_intent.cpp.
        {
            return this->vehicle_id;
        }
References vehicle_id.
Referenced by asJsonObject().
getVehicle_length()
uint32_t message_services::models::vehicle_status_intent::getVehicle_length () const
Definition at line 316 of file vehicle_status_intent.cpp.
        {
            return this->vehicle_length;
        }
References vehicle_length.
Referenced by asJsonObject().
setActual_depart_timestamp()
void message_services::models::vehicle_status_intent::setActual_depart_timestamp (long actual_depart_timestamp)
Definition at line 189 of file vehicle_status_intent.cpp.
        {
            this->actual_depart_timestamp = actual_depart_timestamp;
        }
References actual_depart_timestamp.
setActual_enter_timestamp()
void message_services::models::vehicle_status_intent::setActual_enter_timestamp (long actual_enter_timestamp)
Definition at line 214 of file vehicle_status_intent.cpp.
        {
            this->actual_enter_timestamp = actual_enter_timestamp;
        }
References actual_enter_timestamp.
setActual_stop_timestamp()
void message_services::models::vehicle_status_intent::setActual_stop_timestamp (long actual_stop_timestamp)
Definition at line 223 of file vehicle_status_intent.cpp.
        {
            this->actual_stop_timestamp = actual_stop_timestamp;
        }
References actual_stop_timestamp.
setBsm_id()
void message_services::models::vehicle_status_intent::setBsm_id (std::string bsm_id)
Definition at line 357 of file vehicle_status_intent.cpp.
        {
            this->bsm_id = bsm_id;
        }
References bsm_id.
Referenced by message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilityoperation_msg(), and message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilitypath_msg().
setCur_accel()
void message_services::models::vehicle_status_intent::setCur_accel (double cur_accel)
Definition at line 197 of file vehicle_status_intent.cpp.
        {
            this->cur_accel = cur_accel;
        }
References cur_accel.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
setCur_distance()
void message_services::models::vehicle_status_intent::setCur_distance (double cur_distance)
Definition at line 275 of file vehicle_status_intent.cpp.
        {
            this->cur_distance = cur_distance;
        }
References cur_distance.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setCur_lanelet_id()
void message_services::models::vehicle_status_intent::setCur_lanelet_id (int64_t cur_lanelet_id)
Definition at line 284 of file vehicle_status_intent.cpp.
        {
            this->cur_lanelet_id = cur_lanelet_id;
        }
References cur_lanelet_id.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setCur_speed()
void message_services::models::vehicle_status_intent::setCur_speed (double cur_speed)
Definition at line 180 of file vehicle_status_intent.cpp.
        {
            this->cur_speed = cur_speed;
        }
References cur_speed.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
setCur_timestamp()
void message_services::models::vehicle_status_intent::setCur_timestamp (long cur_timestamp)
Definition at line 249 of file vehicle_status_intent.cpp.
        {
            this->cur_timestamp = cur_timestamp;
        }
References cur_timestamp.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), fromJsonObject(), message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilityoperation_msg(), and message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilitypath_msg().
setDepart_position()
void message_services::models::vehicle_status_intent::setDepart_position (long depart_position)
Definition at line 302 of file vehicle_status_intent.cpp.
        {
            this->depart_position = depart_position;
        }
References depart_position.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setDest_lanelet_id()
void message_services::models::vehicle_status_intent::setDest_lanelet_id (int64_t dest_lanelet_id)
Definition at line 257 of file vehicle_status_intent.cpp.
        {
            this->dest_lanelet_id = dest_lanelet_id;
        }
References dest_lanelet_id.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setEarliest_stop_timestamp()
void message_services::models::vehicle_status_intent::setEarliest_stop_timestamp (long earliest_stop_timestamp)
Definition at line 232 of file vehicle_status_intent.cpp.
        {
            this->earliest_stop_timestamp = earliest_stop_timestamp;
        }
References earliest_stop_timestamp.
setEnter_lanelet_id()
void message_services::models::vehicle_status_intent::setEnter_lanelet_id (int64_t enter_lanelet_id)
Definition at line 266 of file vehicle_status_intent.cpp.
        {
            this->enter_lanelet_id = enter_lanelet_id;
        }
References enter_lanelet_id.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setEst_path_v()
void message_services::models::vehicle_status_intent::setEst_path_v (std::vector< est_path_t > est_path_v)
Definition at line 205 of file vehicle_status_intent.cpp.
        {
            this->est_path_v = est_path_v;
        }
References est_path_v.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setIs_allowed()
void message_services::models::vehicle_status_intent::setIs_allowed (bool is_allowed)
Definition at line 293 of file vehicle_status_intent.cpp.
        {
            this->is_allowed = is_allowed;
        }
References is_allowed.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), fromJsonObject(), and message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilityoperation_msg().
setLink_lanelet_id()
void message_services::models::vehicle_status_intent::setLink_lanelet_id (int64_t link_lanelet_id)
Definition at line 241 of file vehicle_status_intent.cpp.
        {
            this->link_lanelet_id = link_lanelet_id;
        }
References link_lanelet_id.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setMax_accel()
void message_services::models::vehicle_status_intent::setMax_accel (double max_accel)
Definition at line 338 of file vehicle_status_intent.cpp.
        {
            this->max_accel = max_accel;
        }
References max_accel.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
setMax_decel()
void message_services::models::vehicle_status_intent::setMax_decel (double max_decel)
Definition at line 329 of file vehicle_status_intent.cpp.
        {
            this->max_decel = max_decel;
        }
References max_decel.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
setMinimum_gap()
void message_services::models::vehicle_status_intent::setMinimum_gap (double minimum_gap)
Definition at line 311 of file vehicle_status_intent.cpp.
        {
            this->minimum_gap = minimum_gap;
        }
References minimum_gap.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
setReact_timestamp()
void message_services::models::vehicle_status_intent::setReact_timestamp (double react_timestamp)
Definition at line 347 of file vehicle_status_intent.cpp.
        {
            this->react_timestamp = react_timestamp;
        }
References react_timestamp.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
SetTurn_direction()
void message_services::models::vehicle_status_intent::SetTurn_direction (std::string turn_direction)
Definition at line 367 of file vehicle_status_intent.cpp.
        {
            this->turn_direction = turn_direction;
        }
References turn_direction.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setVehicle_id()
void message_services::models::vehicle_status_intent::setVehicle_id (std::string vehicle_id)
Definition at line 172 of file vehicle_status_intent.cpp.
        {
            this->vehicle_id = vehicle_id;
        }
References vehicle_id.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), fromJsonObject(), message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilityoperation_msg(), and message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilitypath_msg().
setVehicle_length()
void message_services::models::vehicle_status_intent::setVehicle_length (uint32_t vehicle_length)
Definition at line 320 of file vehicle_status_intent.cpp.
        {
            this->vehicle_length = vehicle_length;
        }
References vehicle_length.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and fromJsonObject().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, vehicle_status_intent & vehicle_status_intent_obj) [friend]
Definition at line 160 of file vehicle_status_intent.cpp.
        {
            out << "vehicle_status_intent model: vehicle_id = " << vehicle_status_intent_obj.vehicle_id << ", current_timestamp = " << vehicle_status_intent_obj.cur_timestamp << ", bsm_id =" << vehicle_status_intent_obj.bsm_id << ", current speed= " << vehicle_status_intent_obj.cur_speed << std::endl;
            return out;
        }
Member Data Documentation
actual_depart_timestamp
long message_services::models::vehicle_status_intent::actual_depart_timestamp [private]
Definition at line 53 of file vehicle_status_intent.h.
Referenced by getActual_depart_timestamp(), and setActual_depart_timestamp().
actual_enter_timestamp
long message_services::models::vehicle_status_intent::actual_enter_timestamp [private]
Definition at line 52 of file vehicle_status_intent.h.
Referenced by getActual_enter_timestamp(), and setActual_enter_timestamp().
actual_stop_timestamp
long message_services::models::vehicle_status_intent::actual_stop_timestamp [private]
Definition at line 51 of file vehicle_status_intent.h.
Referenced by getActual_stop_timestamp(), and setActual_stop_timestamp().
bsm_id
std::string message_services::models::vehicle_status_intent::bsm_id [private]
Definition at line 33 of file vehicle_status_intent.h.
Referenced by getBsm_id(), and setBsm_id().
cur_accel
double message_services::models::vehicle_status_intent::cur_accel [private]
Definition at line 36 of file vehicle_status_intent.h.
Referenced by getCur_accel(), and setCur_accel().
cur_distance
double message_services::models::vehicle_status_intent::cur_distance [private]
Definition at line 46 of file vehicle_status_intent.h.
Referenced by getCur_distance(), and setCur_distance().
cur_lanelet_id
int64_t message_services::models::vehicle_status_intent::cur_lanelet_id [private]
Definition at line 45 of file vehicle_status_intent.h.
Referenced by getCur_lanelet_id(), and setCur_lanelet_id().
cur_speed
double message_services::models::vehicle_status_intent::cur_speed [private]
Definition at line 35 of file vehicle_status_intent.h.
Referenced by getCur_speed(), and setCur_speed().
cur_timestamp
long message_services::models::vehicle_status_intent::cur_timestamp [private]
Definition at line 37 of file vehicle_status_intent.h.
Referenced by getCur_timestamp(), and setCur_timestamp().
depart_position
long message_services::models::vehicle_status_intent::depart_position [private]
Definition at line 43 of file vehicle_status_intent.h.
Referenced by getDepart_position(), and setDepart_position().
dest_lanelet_id
int64_t message_services::models::vehicle_status_intent::dest_lanelet_id [private]
Definition at line 48 of file vehicle_status_intent.h.
Referenced by getDest_lanelet_id(), and setDest_lanelet_id().
earliest_stop_timestamp
long message_services::models::vehicle_status_intent::earliest_stop_timestamp [private]
Definition at line 50 of file vehicle_status_intent.h.
Referenced by getEarliest_stop_timestamp(), and setEarliest_stop_timestamp().
enter_lanelet_id
int64_t message_services::models::vehicle_status_intent::enter_lanelet_id [private]
Definition at line 47 of file vehicle_status_intent.h.
Referenced by getEnter_lanelet_id(), and setEnter_lanelet_id().
est_path_v
std::vector<est_path_t> message_services::models::vehicle_status_intent::est_path_v [private]
Definition at line 54 of file vehicle_status_intent.h.
Referenced by asJsonObject(), getEst_path_v(), and setEst_path_v().
is_allowed
bool message_services::models::vehicle_status_intent::is_allowed [private]
Definition at line 44 of file vehicle_status_intent.h.
Referenced by getIs_allowed(), and setIs_allowed().
link_lanelet_id
int64_t message_services::models::vehicle_status_intent::link_lanelet_id [private]
Definition at line 49 of file vehicle_status_intent.h.
Referenced by getLink_lanelet_id(), and setLink_lanelet_id().
max_accel
double message_services::models::vehicle_status_intent::max_accel [private]
Definition at line 39 of file vehicle_status_intent.h.
Referenced by getMax_accel(), and setMax_accel().
max_decel
double message_services::models::vehicle_status_intent::max_decel [private]
Definition at line 40 of file vehicle_status_intent.h.
Referenced by getMax_decel(), and setMax_decel().
minimum_gap
double message_services::models::vehicle_status_intent::minimum_gap [private]
Definition at line 42 of file vehicle_status_intent.h.
Referenced by getMinimum_gap(), and setMinimum_gap().
react_timestamp
double message_services::models::vehicle_status_intent::react_timestamp [private]
Definition at line 38 of file vehicle_status_intent.h.
Referenced by getReact_timestamp(), and setReact_timestamp().
turn_direction
std::string message_services::models::vehicle_status_intent::turn_direction = `NA` [private]
Definition at line 34 of file vehicle_status_intent.h.
Referenced by GetTurn_direction(), and SetTurn_direction().
vehicle_id
std::string message_services::models::vehicle_status_intent::vehicle_id [private]
Definition at line 27 of file vehicle_status_intent.h.
Referenced by getVehicle_id(), and setVehicle_id().
vehicle_length
uint32_t message_services::models::vehicle_status_intent::vehicle_length [private]
Definition at line 41 of file vehicle_status_intent.h.
Referenced by getVehicle_length(), and setVehicle_length().
The documentation for this class was generated from the following files:
message_services/src/models/vehicle_status_intent.h
message_services/src/models/vehicle_status_intent.cpp