message_services::models::bsm Class Reference
#include <bsm.h>
Public Member Functions
bsm ()
virtual ~bsm ()
void setCore_data (bsmCoreData_t core_data)
bsmCoreData_t getCore_data () const
std::string generate_hash_bsm_msg_id (std::string temprary_id, long msg_count, long sec_mark)
virtual void fromJsonObject (const rapidjson::Value &obj)
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const
Public Attributes
std::time_t msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Private Attributes
bsmCoreData_t core_data
Friends
std::ostream & operator<< (std::ostream &out, bsm &bsm_obj)
Detailed Description
Definition at line 15 of file bsm.h.
Constructor & Destructor Documentation
bsm()
message_services::models::bsm::bsm ()
Definition at line 14 of file bsm.cpp.
                 : core_data()
        {
        }
 bsm()
message_services::models::bsm::~bsm () [virtual]
Definition at line 18 of file bsm.cpp.
        {
        }
Member Function Documentation
asJsonObject()
bool message_services::models::bsm::asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > * writer) const [virtual]
Implements message_services::models::baseMessage.
Definition at line 176 of file bsm.cpp.
        {
            try
            {
                rapidjson::Value val_core_data;
                writer->Key("bsmCoreData");
                writer->StartObject();
                writer->Key("temprary_id");
                writer->String(this->getCore_data().temprary_id.c_str());
                writer->String("secMark");
                writer->String(std::to_string(this->getCore_data().sec_mark).c_str());
                writer->String("latitude");
                writer->String(std::to_string(this->getCore_data().latitude).c_str());
                writer->String("longitude");
                writer->String(std::to_string(this->getCore_data().longitude).c_str());
                writer->String("elev");
                writer->String(std::to_string(this->getCore_data().elev).c_str());
                writer->String("heading");
                writer->String(std::to_string(this->getCore_data().heading).c_str());
                writer->String("transmission");
                writer->String(this->getCore_data().transmission.c_str());
                writer->String("speed");
                writer->String(std::to_string(this->getCore_data().speed).c_str());
                writer->EndObject();
                writer->EndObject();
                return true;
            }
            catch (std::exception &ex)
            {
                SPDLOG_CRITICAL("BSM model: asJsonObject error.: ", ex.what());
                return false;
            }
        }
References getCore_data(), and to_string().
fromJsonObject()
void message_services::models::bsm::fromJsonObject (const rapidjson::Value & obj) [virtual]
Implements message_services::models::baseMessage.
Definition at line 22 of file bsm.cpp.
        {
            if (obj.IsObject())
            {
                for (rapidjson::Value::ConstMemberIterator obj_itr = obj.MemberBegin(); obj_itr != obj.MemberEnd(); obj_itr++)
                {
                    if (obj_itr->value.IsObject() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("core_data")))
                    {
                        bsmCoreData_t core_data;
                        for (rapidjson::Value::ConstMemberIterator core_data_itr = obj_itr->value.MemberBegin(); core_data_itr != obj_itr->value.MemberEnd(); core_data_itr++)
                        {
                            if (std::string(core_data_itr->name.GetString()) == std::string("id"))
                            {
                                core_data.temprary_id = (core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("angle"))
                            {
                                core_data.angle = std::stof(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("sec_mark"))
                            {
                                core_data.sec_mark = std::stol(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("lat"))
                            {
                                core_data.latitude = std::stod(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("msg_count"))
                            {
                                core_data.msg_count = std::stol(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("long"))
                            {
                                core_data.longitude = std::stod(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("elev"))
                            {
                                core_data.elev = std::stof(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("heading"))
                            {
                                core_data.heading = std::stof(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("transmission"))
                            {
                                core_data.transmission = (core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("speed"))
                            {
                                core_data.speed = std::stof(core_data_itr->value.GetString());
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("size"))
                            {
                                for (rapidjson::Value::ConstMemberIterator size_itr = core_data_itr->value.MemberBegin(); size_itr != core_data_itr->value.MemberEnd(); size_itr++)
                                {
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("length")))
                                    {
                                        core_data.size.length = std::stol(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("width")))
                                    {
                                        core_data.size.width = std::stol(size_itr->value.GetString());
                                    }
                                }
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("accuracy"))
                            {
                                for (rapidjson::Value::ConstMemberIterator size_itr = core_data_itr->value.MemberBegin(); size_itr != core_data_itr->value.MemberEnd(); size_itr++)
                                {
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("orientation")))
                                    {
                                        core_data.accuracy.orientation = std::stof(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("semi_major")))
                                    {
                                        core_data.accuracy.semiMajor = std::stof(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("semi_minor")))
                                    {
                                        core_data.accuracy.semiMinor = std::stof(size_itr->value.GetString());
                                    }
                                }
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("accel_set"))
                            {
                                for (rapidjson::Value::ConstMemberIterator size_itr = core_data_itr->value.MemberBegin(); size_itr != core_data_itr->value.MemberEnd(); size_itr++)
                                {
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("lat")))
                                    {
                                        core_data.accelSet.lat = std::stof(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("long")))
                                    {
                                        core_data.accelSet.Long = std::stof(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("vert")))
                                    {
                                        core_data.accelSet.vert = std::stof(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("yaw")))
                                    {
                                        core_data.accelSet.yaw = std::stof(size_itr->value.GetString());
                                    }
                                }
                            }
                            if (std::string(core_data_itr->name.GetString()) == std::string("brakes"))
                            {
                                for (rapidjson::Value::ConstMemberIterator size_itr = core_data_itr->value.MemberBegin(); size_itr != core_data_itr->value.MemberEnd(); size_itr++)
                                {
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("abs")))
                                    {
                                        core_data.brakes.abs = std::stol(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("aux_brakes")))
                                    {
                                        core_data.brakes.auxBrakes = std::stol(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("brake_boost")))
                                    {
                                        core_data.brakes.brakeBoost = std::stol(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("scs")))
                                    {
                                        core_data.brakes.scs = std::stol(size_itr->value.GetString());
                                    }
                                    if (boost::iequals(std::string(size_itr->name.GetString()), std::string("traction")))
                                    {
                                        core_data.brakes.traction = std::stol(size_itr->value.GetString());
                                    }
                                }
                            }
                        }
                        setCore_data(core_data);
                    }
                }
            }
        }
References message_services::models::BrakeSystemStatus::abs, message_services::models::bsmCoreData::accelSet, message_services::models::bsmCoreData::accuracy, message_services::models::bsmCoreData::angle, message_services::models::BrakeSystemStatus::auxBrakes, message_services::models::BrakeSystemStatus::brakeBoost, message_services::models::bsmCoreData::brakes, core_data, message_services::models::bsmCoreData::elev, message_services::models::bsmCoreData::heading, message_services::models::AccelerationSet4Way::lat, message_services::models::bsmCoreData::latitude, message_services::models::VehicleSize::length, message_services::models::AccelerationSet4Way::Long, message_services::models::bsmCoreData::longitude, message_services::models::bsmCoreData::msg_count, message_services::models::PositionalAccuracy::orientation, message_services::models::BrakeSystemStatus::scs, message_services::models::bsmCoreData::sec_mark, message_services::models::PositionalAccuracy::semiMajor, message_services::models::PositionalAccuracy::semiMinor, setCore_data(), message_services::models::bsmCoreData::size, message_services::models::bsmCoreData::speed, message_services::models::bsmCoreData::temprary_id, message_services::models::BrakeSystemStatus::traction, message_services::models::bsmCoreData::transmission, message_services::models::AccelerationSet4Way::vert, message_services::models::VehicleSize::width, and message_services::models::AccelerationSet4Way::yaw.
generate_hash_bsm_msg_id()
std::string message_services::models::bsm::generate_hash_bsm_msg_id (std::string temprary_id, long msg_count, long sec_mark)
Definition at line 220 of file bsm.cpp.
        {
            std::stringstream hash_ss;
            hash_ss << temprary_id << msg_count << sec_mark;
            return hash_ss.str();
        }
Referenced by message_services::workers::bsm_worker::process_incoming_msg().
getCore_data()
bsmCoreData_t message_services::models::bsm::getCore_data () const
Definition at line 227 of file bsm.cpp.
        {
            return this->core_data;
        }
References core_data.
Referenced by asJsonObject(), message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), message_services::workers::bsm_worker::process_incoming_msg(), and message_services::workers::vehicle_status_intent_worker::update_by_incoming_bsm_msg().
setCore_data()
void message_services::models::bsm::setCore_data (bsmCoreData_t core_data)
Definition at line 232 of file bsm.cpp.
        {
            this->core_data = core_data;
        }
References core_data.
Referenced by fromJsonObject().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, bsm & bsm_obj) [friend]
Definition at line 210 of file bsm.cpp.
        {
            out << std::fixed;
            out << std::setprecision(6);
            out << "bsm model: core_data: { temprary_id = " << bsm_obj.core_data.temprary_id << ", sec_mark = " << bsm_obj.core_data.sec_mark
                      << ", latitude= " << bsm_obj.core_data.latitude << ", longitude = " << bsm_obj.core_data.longitude
                      << ", size: {length = " << bsm_obj.core_data.size.length << "}, speed = " << bsm_obj.core_data.speed << "}" << std::endl;
            return out;
        }
Member Data Documentation
core_data
bsmCoreData_t message_services::models::bsm::core_data [private]
Definition at line 20 of file bsm.h.
Referenced by fromJsonObject(), getCore_data(), and setCore_data().
msg_received_timestamp_
std::time_t message_services::models::bsm::msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Definition at line 33 of file bsm.h.
Referenced by message_services::services::vehicle_status_intent_service::run().
The documentation for this class was generated from the following files:
message_services/src/models/bsm.h
message_services/src/models/bsm.cpp