traffic_signal_controller_service::tsc_state Class Reference
#include <monitor_tsc_state.h>
Public Member Functions
tsc_state (std::shared_ptr< snmp_client > snmp_client)
Constructor for the tsc_state class.
std::unordered_map< int, signal_group_state > & get_signal_group_state_map ()
Return reference to signal group state map.
const std::unordered_map< int, int > & get_ped_phase_map ()
Returns a map of pedestrian phases to signal group ids.
const std::unordered_map< int, int > & get_vehicle_phase_map ()
Returns a map of pedestrian phases to signal group ids.
bool initialize ()
Initialize tsc_state by making SNMP calls to TSC for phase sequence and timing information.
void add_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr)
Updates spat with future movement events for vehicle phases.
Private Member Functions
void get_phase_channels (int max_channels, std::vector< int > &vehicle_phase_channels, std::vector< int > &ped_phase_channels) const
Creates vectors of channels associated with a vehicle phase and a pedestrian. Ignores overlap, ped Overlap, queueJump and other (types defined in NTCIP1202 v03)
void map_phase_and_signalgroup (const std::vector< int > &phase_channels, bool is_source_vehicle_channel)
Constructs a map between phase number and signal group ids.
int get_max_channels () const
Method for getting maximum channels for the traffic signal controller.
int get_min_green (int phase_num) const
Get minimum green time for a phase.
int get_max_green (int phase_num) const
Get maximum green time for a phase.
int get_yellow_duration (int phase_num) const
Get yellow duration time for a phase.
int get_red_clearance (int phase_num) const
Get red clearance time for a phase.
int get_red_duration (int phase_num)
Get red duration for a phase.
std::vector< int > get_following_phases (int phase_num)
Get a sequence of phases following the given phase.
std::vector< int > phase_seq (int ring_num)
Get a sequence of phases in the given ring.
std::vector< int > get_concurrent_phases (int phase_num) const
The concurrent phases that the given phase can be green along with.
uint16_t convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const
Helper function to convert epoch time to hour-tenths time.
uint64_t convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const
Helper function to convert hour-tenths time to epoch time.
signal_phase_and_timing::movement_event get_following_event (const signal_phase_and_timing::movement_event &current_event, uint64_t current_event_end_time, const signal_group_state &phase_state) const
Get predicted next movement event given a current event.
FRIEND_TEST (traffic_signal_controller_service, test_get_following_movement_events)
Private Attributes
std::shared_ptr< snmp_client > snmp_client_worker_
std::unordered_map< int, signal_group_state > signal_group_state_map_
std::unordered_map< int, int > signal_group_phase_map_
std::unordered_map< int, int > vehicle_phase_num_map_
std::unordered_map< int, int > ped_phase_num_map_
std::vector< int > phase_seq_ring1_
std::vector< int > phase_seq_ring2_
int required_following_movements_ = 3
int HOUR_TO_SECONDS_ = 3600
int SECOND_TO_MILLISECONDS_ = 1000
Detailed Description
Definition at line 38 of file monitor_tsc_state.h.
Constructor & Destructor Documentation
tsc_state()
traffic_signal_controller_service::tsc_state::tsc_state (std::shared_ptr< snmp_client > snmp_client) [explicit]
Constructor for the tsc_state class.
Parameters
snmp_client A pointer to an snmp_client worker with a connection established to a traffic signal controller
Definition at line 5 of file monitor_tsc_state.cpp.
                                                               : snmp_client_worker_(snmp_client)
    {
        
    }
Member Function Documentation
add_future_movement_events()
void traffic_signal_controller_service::tsc_state::add_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr)
Updates spat with future movement events for vehicle phases.
Parameters
spat_ptr pointer to spat message to update
Returns
true if update was successful, false if it failed
Definition at line 117 of file monitor_tsc_state.cpp.
    {
        // Modify spat according to phase configuration
        // Note: Only first intersection is populated
        for (auto movement : spat_ptr->intersections.front().states)
        {
            int signal_group_id = movement.signal_group;
            // Assumption here is that the movement states have only one event, since this method adds future events to the list.
            //Throw exception is list size is great than 1
            if (movement.state_time_speed.size() > 1)
            {
                SPDLOG_ERROR("Event list has more than one events, not usable when adding future movement events. Associated with Signal Group: {0}", signal_group_id);
                throw monitor_states_exception("Event list has more than one events, not usable when adding future movement events. Associated with Signal Group:" + std::to_string(signal_group_id));
            }
            // Get movement_state by reference
            auto& current_movement = spat_ptr->intersections.front().get_movement(signal_group_id);
            // Get start time as epoch time
            uint64_t start_time = movement.state_time_speed.front().timing.get_epoch_start_time();
            
            // Check if signal_group_id is associated with a vehicle phase : Only vehicle phases mapped to signal_group_states
            signal_group_state phase_state;
            if(signal_group_state_map_.find(signal_group_id) == signal_group_state_map_.end()){
                continue;
            }
            
            phase_state = signal_group_state_map_[signal_group_id];
            uint64_t current_event_end_time_epoch = 0;
            signal_phase_and_timing::movement_event current_event = current_movement.state_time_speed.front();
            switch(current_event.event_state){
                case signal_phase_and_timing::movement_phase_state::stop_and_remain : //Red
                    current_event_end_time_epoch = start_time + phase_state.red_duration;
                    break;
                case signal_phase_and_timing::movement_phase_state::protected_movement_allowed : //Green
                    current_event_end_time_epoch = start_time + phase_state.green_duration;
                    break;
                case signal_phase_and_timing::movement_phase_state::protected_clearance : //Yellow
                    current_event_end_time_epoch = start_time + phase_state.yellow_duration;
                    break;
                default:
                    SPDLOG_DEBUG("This movement phase is not supported. Movement phase type: {0}", int(current_movement.state_time_speed.front().event_state));
                    throw monitor_states_exception("This movement phase is not supported. Movement phase type: " + std::to_string(int(current_movement.state_time_speed.front().event_state)));
            }
            // Update end_time for current_event
            current_movement.state_time_speed.front().timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time_epoch);
            current_movement.state_time_speed.front().timing.max_end_time = current_movement.state_time_speed.front().timing.min_end_time;
            for(int i = 0; i < required_following_movements_; ++i)
            {
                signal_phase_and_timing::movement_event next_event = get_following_event(current_event, current_event_end_time_epoch, phase_state);
                current_event = next_event;
                current_event_end_time_epoch = convert_hour_tenth_secs2epoch_ts(current_event.timing.min_end_time);
                //Add events to list
                current_movement.state_time_speed.push_back(next_event);
            }
            
        }
        
    }
References convert_hour_tenth_secs2epoch_ts(), convert_msepoch_to_hour_tenth_secs(), signal_phase_and_timing::movement_event::event_state, get_following_event(), traffic_signal_controller_service::signal_group_state::green_duration, simulate_bsm::i, signal_phase_and_timing::time_change_details::min_end_time, signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, traffic_signal_controller_service::signal_group_state::red_duration, required_following_movements_, signal_group_state_map_, signal_phase_and_timing::stop_and_remain, signal_phase_and_timing::movement_event::timing, to_string(), and traffic_signal_controller_service::signal_group_state::yellow_duration.
convert_hour_tenth_secs2epoch_ts()
uint64_t traffic_signal_controller_service::tsc_state::convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const [private]
Helper function to convert hour-tenths time to epoch time.
Parameters
hour_tenth_secs tenths of a second in current or next hour
Returns
epoch time in milliseconds
Definition at line 468 of file monitor_tsc_state.cpp.
                                                                                      {
        auto tp = std::chrono::system_clock::now();
        auto duration = tp.time_since_epoch();
        auto hours_since_epoch = std::chrono::duration_cast<std::chrono::hours>(duration).count();
        auto epoch_start_time = hours_since_epoch * HOUR_TO_SECONDS_ * SECOND_TO_MILLISECONDS_ + hour_tenth_secs * 100;
        return epoch_start_time;
    }
References HOUR_TO_SECONDS_, and SECOND_TO_MILLISECONDS_.
Referenced by add_future_movement_events().
convert_msepoch_to_hour_tenth_secs()
uint16_t traffic_signal_controller_service::tsc_state::convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const [private]
Helper function to convert epoch time to hour-tenths time.
Parameters
epoch_time_ms epoch time in milliseconds
Returns
tenths of a second in current or next hour
Definition at line 460 of file monitor_tsc_state.cpp.
                                                                                      {
        auto system_time = std::chrono::system_clock::now();
        auto duration = system_time.time_since_epoch();
        auto hours_since_epoch = std::chrono::duration_cast<std::chrono::hours>(duration).count();
        auto hour_tenth_secs = (epoch_time_ms - (hours_since_epoch * HOUR_TO_SECONDS_ * SECOND_TO_MILLISECONDS_))/100;
        return static_cast<uint16_t>(hour_tenth_secs);
    }
References HOUR_TO_SECONDS_, and SECOND_TO_MILLISECONDS_.
Referenced by add_future_movement_events(), and get_following_event().
FRIEND_TEST()
traffic_signal_controller_service::tsc_state::FRIEND_TEST (traffic_signal_controller_service , test_get_following_movement_events) [private]
get_concurrent_phases()
std::vector< int > traffic_signal_controller_service::tsc_state::get_concurrent_phases (int phase_num) const [private]
The concurrent phases that the given phase can be green along with.
Parameters
ring_num The phase for which the concurrent phases needs to be obtained
Returns
a vector of phases that may be concurrent with the given phase
Definition at line 419 of file monitor_tsc_state.cpp.
    {
        std::vector<int> concurrent_phases;
        std::string concurrent_phases_oid = ntcip_oids::PHASE_CONCURRENCY + "." + std::to_string(phase_num);
        snmp_response_obj concurrent_phase_data;
        request_type request_type = request_type::GET;
        concurrent_phase_data.type = snmp_response_obj::response_type::STRING;
        snmp_client_worker_->process_snmp_request(concurrent_phases_oid, request_type, concurrent_phase_data);
        //extract phase numbers from strings
        for(auto con_phase : concurrent_phase_data.val_string)
        {
            concurrent_phases.push_back(int(con_phase));
            
        }
        if(concurrent_phases.empty())
        {
            SPDLOG_WARN("No phases found in sequence for phase {0}", phase_num);
        }
        return concurrent_phases;
    }
References traffic_signal_controller_service::GET, ntcip_oids::PHASE_CONCURRENCY, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::STRING, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_string.
Referenced by initialize().
get_following_event()
signal_phase_and_timing::movement_event traffic_signal_controller_service::tsc_state::get_following_event (const signal_phase_and_timing::movement_event & current_event, uint64_t current_event_end_time, const signal_group_state & phase_state) const [private]
Get predicted next movement event given a current event.
Parameters
current_event movement_event from the next movement needs to be predicted
current_event_end_time End time of the current event in epoch time (milliseconds)
phase_state signal_group_state for the phase of which the movement events are a part
Returns
predicted next movement event
Definition at line 83 of file monitor_tsc_state.cpp.
    {
        signal_phase_and_timing::movement_event next_event;
        switch (current_event.event_state){
            case signal_phase_and_timing::movement_phase_state::protected_movement_allowed: //Green
                // Create next movement - yellow
                next_event.event_state = signal_phase_and_timing::movement_phase_state::protected_clearance;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.yellow_duration);
                break;
            case signal_phase_and_timing::movement_phase_state::protected_clearance: //Yellow
                // Create next movement - red
                next_event.event_state = signal_phase_and_timing::movement_phase_state::stop_and_remain;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.red_duration);
                break;
            case signal_phase_and_timing::movement_phase_state::stop_and_remain: //Red
                // Create next movement - green
                next_event.event_state = signal_phase_and_timing::movement_phase_state::protected_movement_allowed;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.green_duration);
                break;
            default:
                SPDLOG_ERROR("This movement phase is not supported. Movement phase type: {0}", int(current_event.event_state));
                throw snmp_client_exception("Failed request for unsupported movement phase type: " + std::to_string(int(current_event.event_state)));
        }
        next_event.timing.max_end_time = next_event.timing.min_end_time;
        return next_event;
    }
References convert_msepoch_to_hour_tenth_secs(), signal_phase_and_timing::movement_event::event_state, traffic_signal_controller_service::signal_group_state::green_duration, signal_phase_and_timing::time_change_details::max_end_time, signal_phase_and_timing::time_change_details::min_end_time, signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, traffic_signal_controller_service::signal_group_state::red_duration, signal_phase_and_timing::time_change_details::start_time, signal_phase_and_timing::stop_and_remain, signal_phase_and_timing::movement_event::timing, to_string(), and traffic_signal_controller_service::signal_group_state::yellow_duration.
Referenced by add_future_movement_events().
get_following_phases()
std::vector< int > traffic_signal_controller_service::tsc_state::get_following_phases (int phase_num) [private]
Get a sequence of phases following the given phase.
Parameters
phase_num The phase for which the sequence needs to be obtained
Returns
a vector as a sequence of phases starting from the given phase
Definition at line 184 of file monitor_tsc_state.cpp.
    {
        std::vector<int> sequence;
        // Add phase sequence to signal group state
        for(size_t i = 0; i < phase_seq_ring1_.size();++i)
        {
            if(phase_seq_ring1_[i] == phase_num)
            {
                sequence.insert(sequence.begin(), phase_seq_ring1_.begin() + i, phase_seq_ring1_.end());
                sequence.insert(sequence.end(), phase_seq_ring1_.begin(), phase_seq_ring1_.begin() + i);
                return sequence;
            }
        }
        for(size_t i = 0; i < phase_seq_ring2_.size();++i)
        {
            if(phase_seq_ring2_[i] == phase_num)
            {
                sequence.insert(sequence.begin(), phase_seq_ring2_.begin() + i, phase_seq_ring2_.end());
                sequence.insert(sequence.end(), phase_seq_ring2_.begin(), phase_seq_ring2_.begin() + i);
                return sequence;
            }
        }
        // No following phase information found
        throw snmp_client_exception("No following phases found");
    }
References simulate_bsm::i, phase_seq_ring1_, and phase_seq_ring2_.
Referenced by initialize().
get_max_channels()
int traffic_signal_controller_service::tsc_state::get_max_channels () const [private]
Method for getting maximum channels for the traffic signal controller.
Returns
number of maximum channels in the traffic signal controller
Definition at line 214 of file monitor_tsc_state.cpp.
                                          {
        request_type request_type = request_type::GET;
        snmp_response_obj max_channels_in_tsc;
        max_channels_in_tsc.type = snmp_response_obj::response_type::INTEGER;
        if(!snmp_client_worker_->process_snmp_request(ntcip_oids::MAX_CHANNELS, request_type, max_channels_in_tsc))
        {
            throw snmp_client_exception("Failed to get max channels!");
        }
        return (int) max_channels_in_tsc.val_int;
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MAX_CHANNELS, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_max_green()
int traffic_signal_controller_service::tsc_state::get_max_green (int phase_num) const [private]
Get maximum green time for a phase.
Parameters
phase_num The phase for which the maximum green needs to be requested
Returns
maximum green time in milliseconds
Definition at line 309 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string max_green_parameter_oid = ntcip_oids::MAXIMUM_GREEN + "." + std::to_string(phase_num);
        snmp_response_obj max_green;
        max_green.type = snmp_response_obj::response_type::INTEGER;
        
        snmp_client_worker_->process_snmp_request(max_green_parameter_oid, request_type, max_green);
        return (int) max_green.val_int * 1000; //Convert seconds to milliseconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MAXIMUM_GREEN, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_min_green()
int traffic_signal_controller_service::tsc_state::get_min_green (int phase_num) const [private]
Get minimum green time for a phase.
Parameters
phase_num The phase for which the min green needs to be requested
Returns
minimum green time in milliseconds
Definition at line 296 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string min_green_parameter_oid = ntcip_oids::MINIMUM_GREEN + "." + std::to_string(phase_num);
        snmp_response_obj min_green;
        min_green.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_->process_snmp_request(min_green_parameter_oid, request_type, min_green);
        return (int) min_green.val_int * 1000; //Convert seconds to milliseconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MINIMUM_GREEN, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_ped_phase_map()
const std::unordered_map< int, int > & traffic_signal_controller_service::tsc_state::get_ped_phase_map ()
Returns a map of pedestrian phases to signal group ids.
Returns
a map of pedestrian phases to signal group ids
Definition at line 445 of file monitor_tsc_state.cpp.
    {
        return ped_phase_num_map_;
    }
References ped_phase_num_map_.
get_phase_channels()
void traffic_signal_controller_service::tsc_state::get_phase_channels (int max_channels, std::vector< int > & vehicle_phase_channels, std::vector< int > & ped_phase_channels) const [private]
Creates vectors of channels associated with a vehicle phase and a pedestrian. Ignores overlap, ped Overlap, queueJump and other (types defined in NTCIP1202 v03)
Parameters
max_channels The maximum number of channels in the traffic signal controller.
vehicle_phase_channels a vector of active vehicle phases associated with a channel
ped_phase_channels a vector of active pedestrian phases associated with a channel
Definition at line 227 of file monitor_tsc_state.cpp.
                                                                                                                                        {
        
        // Loop through channel control types and add channels with vehicle phase to list
        snmp_response_obj control_type;
        control_type.type = snmp_response_obj::response_type::INTEGER;
        
        request_type request_type = request_type::GET;
        for(int channel_num = 1; channel_num <= max_channels; ++channel_num)
        {
            std::string control_type_parameter_oid = ntcip_oids::CHANNEL_CONTROL_TYPE_PARAMETER + "." + std::to_string(channel_num);
            if(!snmp_client_worker_->process_snmp_request(control_type_parameter_oid, request_type, control_type))
            {
                throw snmp_client_exception("Failed to get channel control type");
            }
            if(control_type.val_int == 2)
            {
                vehicle_phase_channels.push_back(channel_num);
            }
            else if(control_type.val_int == 3)
            {
                ped_phase_channels.push_back(channel_num);
            }
        }
        if(vehicle_phase_channels.empty()){
            SPDLOG_WARN("Found no active vehicle phases");
        }
        if(ped_phase_channels.empty()){
            SPDLOG_DEBUG("Found no active ped phases");
        }
        
        SPDLOG_DEBUG("Number of vehicle phase channels found: {0}", vehicle_phase_channels.size());
        SPDLOG_DEBUG("Number of ped phase channels found: {0}", ped_phase_channels.size());
        
    }
References ntcip_oids::CHANNEL_CONTROL_TYPE_PARAMETER, traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_red_clearance()
int traffic_signal_controller_service::tsc_state::get_red_clearance (int phase_num) const [private]
Get red clearance time for a phase.
Parameters
phase_num The phase for which the red clearance needs to be requested
Returns
red clearance time in milliseconds
Definition at line 335 of file monitor_tsc_state.cpp.
    {
        request_type get_request = request_type::GET;
        std::string red_clearance_oid = ntcip_oids::RED_CLEAR_PARAMETER + "." + std::to_string(phase_num);
        snmp_response_obj red_clearance;
        red_clearance.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_->process_snmp_request(red_clearance_oid, get_request, red_clearance);
        return (int) red_clearance.val_int * 100; //Convert to milliseconds. NTCIP returned value is in tenths of seconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::RED_CLEAR_PARAMETER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_red_duration()
int traffic_signal_controller_service::tsc_state::get_red_duration (int phase_num) [private]
Get red duration for a phase.
Parameters
phase_num The phase for which the red duration needs to be requested
Returns
red duration time in milliseconds
Definition at line 348 of file monitor_tsc_state.cpp.
    {
        //red duration is calculated as red_clearance time for current phase + (green duration + yellow duration + red_clearance) for other phases in sequence
        // Find signal state associated with phase num
        int current_signal_group;
        if(vehicle_phase_num_map_.find(phase_num) != vehicle_phase_num_map_.end())
        {
            current_signal_group = vehicle_phase_num_map_[phase_num];
        }
        else{
            throw snmp_client_exception("No signal state associated with phase " + std::to_string(phase_num) + ".");
        }
        auto current_signal_group_state = signal_group_state_map_[current_signal_group];
        // Only add clearance time for current phase
        int red_duration = current_signal_group_state.red_clearance;
        
        for(auto phase : current_signal_group_state.phase_seq)
        {
            // Find state params for each phase in seq
            int seq_signal_group;
            if(vehicle_phase_num_map_.find(phase_num) != vehicle_phase_num_map_.end())
            {
                seq_signal_group = vehicle_phase_num_map_[phase];
            }
            else{
                throw snmp_client_exception("No signal state associated with phase " + std::to_string(phase) + ".");
            }
            auto seq_signal_group_state = signal_group_state_map_[seq_signal_group];
            if(phase == phase_num)
            {
                continue;
            }
            else{
                red_duration += seq_signal_group_state.green_duration + seq_signal_group_state.yellow_duration + seq_signal_group_state.red_clearance;
            }
        }
        
        return red_duration;
    }
References signal_group_state_map_, to_string(), and vehicle_phase_num_map_.
Referenced by initialize().
get_signal_group_state_map()
std::unordered_map< int, signal_group_state > & traffic_signal_controller_service::tsc_state::get_signal_group_state_map ()
Return reference to signal group state map.
Returns
std::unordered_map<int, signal_group_state>&
Definition at line 455 of file monitor_tsc_state.cpp.
    {
        return signal_group_state_map_;
    }
References signal_group_state_map_.
get_vehicle_phase_map()
const std::unordered_map< int, int > & traffic_signal_controller_service::tsc_state::get_vehicle_phase_map ()
Returns a map of pedestrian phases to signal group ids.
Returns
a map of pedestrian phases to signal group ids
Definition at line 450 of file monitor_tsc_state.cpp.
    {
        return vehicle_phase_num_map_;
    }
References vehicle_phase_num_map_.
get_yellow_duration()
int traffic_signal_controller_service::tsc_state::get_yellow_duration (int phase_num) const [private]
Get yellow duration time for a phase.
Parameters
phase_num The phase for which the yellow duration needs to be requested
Returns
yellow duration time in milliseconds
Definition at line 322 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string yellow_duration_oid = ntcip_oids::YELLOW_CHANGE_PARAMETER + "." + std::to_string(phase_num);
        snmp_response_obj yellow_duration;
        yellow_duration.type = snmp_response_obj::response_type::INTEGER;
        
        snmp_client_worker_ ->process_snmp_request(yellow_duration_oid, request_type, yellow_duration);
        return (int) yellow_duration.val_int * 100; //Convert to milliseconds. NTCIP returned value is in tenths of seconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, traffic_signal_controller_service::snmp_response_obj::val_int, and ntcip_oids::YELLOW_CHANGE_PARAMETER.
Referenced by initialize().
initialize()
bool traffic_signal_controller_service::tsc_state::initialize ()
Initialize tsc_state by making SNMP calls to TSC for phase sequence and timing information.
Returns
true if initialization is successful.
Definition at line 10 of file monitor_tsc_state.cpp.
                               {
        try {
            // Map signal group ids and phase nums
            //Get phase number given a signal group id
            int max_channels_in_tsc = get_max_channels();
            std::vector<int> vehicle_phase_channels;
            std::vector<int> ped_phase_channels;
            get_phase_channels(max_channels_in_tsc, vehicle_phase_channels, ped_phase_channels);
            map_phase_and_signalgroup(vehicle_phase_channels, true);
            map_phase_and_signalgroup(ped_phase_channels, false);
            // Get phase sequences for ring 1 and ring 2
            phase_seq_ring1_ = phase_seq(1);
            phase_seq_ring2_ = phase_seq(2);
            // Define state of each signal group
            for (const auto& signal_group : signal_group_phase_map_)
            {
                int phase_num = signal_group.second;
                signal_group_state state;
                state.phase_num = phase_num;
                state.max_green = get_max_green(phase_num);
                state.min_green = get_min_green(phase_num);
                state.yellow_duration = get_yellow_duration(phase_num);
                // Define green duration as min/max as decided
                state.green_duration = state.min_green;
                state.red_clearance = get_red_clearance(phase_num);
                state.phase_seq = get_following_phases(phase_num);
                state.concurrent_phases = get_concurrent_phases(phase_num);
                signal_group_state_map_.insert(std::make_pair(signal_group.first, state));
            }
        
            // Loop through states once other state parameters are defined to get the red duration
            for(auto& [signal_group, state] : signal_group_state_map_)
            {
                
                state.red_duration = get_red_duration(state.phase_num);
            }
            
            // Print signal_group map
            for (const auto& [signal_group, phase] : signal_group_phase_map_)
            {
                SPDLOG_DEBUG("Signal group id: {0} phase: {1}", signal_group, phase);
            }
            // Print state map
            for (const auto& [signal_group, state] : signal_group_state_map_)
            {
                SPDLOG_DEBUG("Signal group id: {0}", signal_group);
                SPDLOG_DEBUG("Phase num: {0}", state.phase_num);
                SPDLOG_DEBUG("Max green: {0}", state.max_green);
                SPDLOG_DEBUG("Min green: {0}", state.min_green);
                SPDLOG_DEBUG("Green Duration: {0}", state.green_duration);
                SPDLOG_DEBUG("yellow duration: {0}", state.yellow_duration);
                SPDLOG_DEBUG("Red clearance: {0}", state.red_clearance);
                SPDLOG_DEBUG("Red duration: {0}", state.red_duration);
                SPDLOG_DEBUG("Phase sequence:");
                for(auto phase : state.phase_seq){
                    SPDLOG_DEBUG("{0}", phase);
                }
                SPDLOG_DEBUG("Concurrent Phases:");
                for(auto phase : state.concurrent_phases){
                    SPDLOG_DEBUG("{0}", phase);
                }
            }
            return true;
        }catch (const snmp_client_exception &e) {
            SPDLOG_ERROR("Exception encounters during initialization: \n {0}",e.what());
            return false;
        }
    }
References traffic_signal_controller_service::signal_group_state::concurrent_phases, get_concurrent_phases(), get_following_phases(), get_max_channels(), get_max_green(), get_min_green(), get_phase_channels(), get_red_clearance(), get_red_duration(), get_yellow_duration(), traffic_signal_controller_service::signal_group_state::green_duration, map_phase_and_signalgroup(), traffic_signal_controller_service::signal_group_state::max_green, traffic_signal_controller_service::signal_group_state::min_green, traffic_signal_controller_service::signal_group_state::phase_num, traffic_signal_controller_service::signal_group_state::phase_seq, phase_seq(), phase_seq_ring1_, phase_seq_ring2_, traffic_signal_controller_service::signal_group_state::red_clearance, signal_group_phase_map_, signal_group_state_map_, and traffic_signal_controller_service::signal_group_state::yellow_duration.
map_phase_and_signalgroup()
void traffic_signal_controller_service::tsc_state::map_phase_and_signalgroup (const std::vector< int > & phase_channels, bool is_source_vehicle_channel) [private]
Constructs a map between phase number and signal group ids.
Parameters
phase_channels a vector of channel numbers in the traffic signal controller associated with a phase
is_source_vehicle_channel a boolean that indicates whether the phase_channels arg is for channels associated with vehicle phases. In case they are not its assumed that they are pedestrian phases According to the NTCIP 1202 v03 documentation signal group ids in the SPAT message are the channel numbers in the TSC
Definition at line 266 of file monitor_tsc_state.cpp.
    {
        // According to NTCIP 1202 v03 documentation Signal Group ID in a SPAT message is the Channel Number from TSC
        // Get phases associated with vehicle phase channels
        request_type request_type = request_type::GET;
        for(int channel : phase_channels)
        {
            snmp_response_obj phase_num;
            phase_num.type = snmp_response_obj::response_type::INTEGER;
            std::string control_source_parameter_oid = ntcip_oids::CHANNEL_CONTROL_SOURCE_PARAMETER + "." + std::to_string(channel);
            snmp_client_worker_->process_snmp_request(control_source_parameter_oid, request_type, phase_num);
            // According to NTCIP 1202 v03 returned value of 0 here would mean a phase is not associated with the channel
            if(phase_num.val_int != 0)
            {
                if(is_source_vehicle_channel){
                    vehicle_phase_num_map_.insert(std::make_pair(phase_num.val_int, channel));
                    signal_group_phase_map_.insert(std::make_pair(channel, phase_num.val_int));
                }
                else{
                    ped_phase_num_map_.insert(std::make_pair(phase_num.val_int, channel));
                }
                SPDLOG_DEBUG("Found mapping between signal group: {0} and phase num: {1}", channel , phase_num.val_int);
            }
        }
        
    }
References ntcip_oids::CHANNEL_CONTROL_SOURCE_PARAMETER, traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ped_phase_num_map_, signal_group_phase_map_, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, traffic_signal_controller_service::snmp_response_obj::val_int, and vehicle_phase_num_map_.
Referenced by initialize().
phase_seq()
std::vector< int > traffic_signal_controller_service::tsc_state::phase_seq (int ring_num) [private]
Get a sequence of phases in the given ring.
Parameters
ring_num The phase for which the sequence needs to be obtained
Returns
a vector as a sequence of phases in the ring
Definition at line 389 of file monitor_tsc_state.cpp.
    {
        std::vector<int> phase_seq;
        // Read sequence 1 data for first 2 rings
        request_type request_type = request_type::GET;
        std::string phase_seq_oid= ntcip_oids::SEQUENCE_DATA + "." + "1" + "." + std::to_string(ring_num); //Sequence 1 for ring
        snmp_response_obj seq_data;
        seq_data.type = snmp_response_obj::response_type::STRING;
        snmp_client_worker_->process_snmp_request(phase_seq_oid, request_type, seq_data);
        
        //extract phase numbers from strings
        for(auto seq_val : seq_data.val_string)
        {
            auto phase = int(seq_val);
            if(vehicle_phase_num_map_.find(phase)!= vehicle_phase_num_map_.end() && phase != 0){
                phase_seq.push_back(phase);
            }
            
        }
        if(phase_seq.empty())
        {
            SPDLOG_WARN("No phases found in sequence 1 for ring {0}", ring_num);
        }
        return phase_seq;
    }
References traffic_signal_controller_service::GET, phase_seq(), ntcip_oids::SEQUENCE_DATA, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::STRING, to_string(), traffic_signal_controller_service::snmp_response_obj::type, traffic_signal_controller_service::snmp_response_obj::val_string, and vehicle_phase_num_map_.
Referenced by initialize(), and phase_seq().
Member Data Documentation
HOUR_TO_SECONDS_
int traffic_signal_controller_service::tsc_state::HOUR_TO_SECONDS_ = 3600 [private]
Definition at line 65 of file monitor_tsc_state.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
ped_phase_num_map_
std::unordered_map<int,int> traffic_signal_controller_service::tsc_state::ped_phase_num_map_ [private]
Definition at line 54 of file monitor_tsc_state.h.
Referenced by get_ped_phase_map(), and map_phase_and_signalgroup().
phase_seq_ring1_
std::vector<int> traffic_signal_controller_service::tsc_state::phase_seq_ring1_ [private]
Definition at line 57 of file monitor_tsc_state.h.
Referenced by get_following_phases(), and initialize().
phase_seq_ring2_
std::vector<int> traffic_signal_controller_service::tsc_state::phase_seq_ring2_ [private]
Definition at line 59 of file monitor_tsc_state.h.
Referenced by get_following_phases(), and initialize().
required_following_movements_
int traffic_signal_controller_service::tsc_state::required_following_movements_ = 3 [private]
Definition at line 62 of file monitor_tsc_state.h.
Referenced by add_future_movement_events().
SECOND_TO_MILLISECONDS_
int traffic_signal_controller_service::tsc_state::SECOND_TO_MILLISECONDS_ = 1000 [private]
Definition at line 66 of file monitor_tsc_state.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
signal_group_phase_map_
std::unordered_map<int, int> traffic_signal_controller_service::tsc_state::signal_group_phase_map_ [private]
Definition at line 48 of file monitor_tsc_state.h.
Referenced by initialize(), and map_phase_and_signalgroup().
signal_group_state_map_
std::unordered_map<int, signal_group_state> traffic_signal_controller_service::tsc_state::signal_group_state_map_ [private]
Definition at line 45 of file monitor_tsc_state.h.
Referenced by add_future_movement_events(), get_red_duration(), get_signal_group_state_map(), and initialize().
snmp_client_worker_
std::shared_ptr<snmp_client> traffic_signal_controller_service::tsc_state::snmp_client_worker_ [private]
Definition at line 42 of file monitor_tsc_state.h.
Referenced by get_concurrent_phases(), get_max_channels(), get_max_green(), get_min_green(), get_phase_channels(), get_red_clearance(), get_yellow_duration(), map_phase_and_signalgroup(), and phase_seq().
vehicle_phase_num_map_
std::unordered_map<int,int> traffic_signal_controller_service::tsc_state::vehicle_phase_num_map_ [private]
Definition at line 51 of file monitor_tsc_state.h.
Referenced by get_red_duration(), get_vehicle_phase_map(), map_phase_and_signalgroup(), and phase_seq().
The documentation for this class was generated from the following files:
tsc_client_service/include/monitor_tsc_state.h
tsc_client_service/src/monitor_tsc_state.cpp