OpenAPI::OAIObject Class Reference
#include <OAIObject.h>
Public Member Functions
OAIObject ()
OAIObject (QString jsonString)
virtual ~OAIObject ()
virtual QJsonObject asJsonObject () const
virtual QString asJson () const
virtual void fromJson (QString jsonString)
virtual void fromJsonObject (QJsonObject json)
virtual bool isSet () const
virtual bool isValid () const
OAIObject ()
OAIObject (QString jsonString)
virtual ~OAIObject ()
virtual QJsonObject asJsonObject () const
virtual QString asJson () const
virtual void fromJson (QString jsonString)
virtual void fromJsonObject (QJsonObject json)
virtual bool isSet () const
virtual bool isValid () const
Private Attributes
QJsonObject jObj
Detailed Description
Definition at line 21 of file OAIObject.h.
Constructor & Destructor Documentation
OAIObject() [1/4]
OpenAPI::OAIObject::OAIObject () [inline]
Definition at line 23 of file OAIObject.h.
{}
OAIObject() [2/4]
OpenAPI::OAIObject::OAIObject (QString jsonString) [inline]
Definition at line 25 of file OAIObject.h.
                                  {
        fromJson(jsonString);
    }
References fromJson().
 OAIObject() [1/2]
virtual OpenAPI::OAIObject::~OAIObject () [inline], [virtual]
Definition at line 29 of file OAIObject.h.
{}
OAIObject() [3/4]
OpenAPI::OAIObject::OAIObject () [inline]
Definition at line 23 of file OAIObject.h.
{}
OAIObject() [4/4]
OpenAPI::OAIObject::OAIObject (QString jsonString) [inline]
Definition at line 25 of file OAIObject.h.
                                  {
        fromJson(jsonString);
    }
References fromJson().
 OAIObject() [2/2]
virtual OpenAPI::OAIObject::~OAIObject () [inline], [virtual]
Definition at line 29 of file OAIObject.h.
{}
Member Function Documentation
asJson() [1/2]
virtual QString OpenAPI::OAIObject::asJson () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 35 of file OAIObject.h.
                                   {
        QJsonDocument doc(jObj);
        return doc.toJson(QJsonDocument::Compact);
    }
References jObj.
asJson() [2/2]
virtual QString OpenAPI::OAIObject::asJson () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 35 of file OAIObject.h.
                                   {
        QJsonDocument doc(jObj);
        return doc.toJson(QJsonDocument::Compact);
    }
References jObj.
asJsonObject() [1/2]
virtual QJsonObject OpenAPI::OAIObject::asJsonObject () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 31 of file OAIObject.h.
                                             {
        return jObj;
    }
References jObj.
asJsonObject() [2/2]
virtual QJsonObject OpenAPI::OAIObject::asJsonObject () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 31 of file OAIObject.h.
                                             {
        return jObj;
    }
References jObj.
fromJson() [1/2]
virtual void OpenAPI::OAIObject::fromJson (QString jsonString) [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 40 of file OAIObject.h.
                                              {
        QJsonDocument doc = QJsonDocument::fromJson(jsonString.toUtf8());
        jObj = doc.object();
    }
References jObj.
Referenced by OAIObject().
fromJson() [2/2]
virtual void OpenAPI::OAIObject::fromJson (QString jsonString) [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 40 of file OAIObject.h.
                                              {
        QJsonDocument doc = QJsonDocument::fromJson(jsonString.toUtf8());
        jObj = doc.object();
    }
References jObj.
fromJsonObject() [1/2]
virtual void OpenAPI::OAIObject::fromJsonObject (QJsonObject json) [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 45 of file OAIObject.h.
                                                  {
        jObj = json;
    }
References jObj.
fromJsonObject() [2/2]
virtual void OpenAPI::OAIObject::fromJsonObject (QJsonObject json) [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 45 of file OAIObject.h.
                                                  {
        jObj = json;
    }
References jObj.
isSet() [1/2]
virtual bool OpenAPI::OAIObject::isSet () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 49 of file OAIObject.h.
                               {
        return false;
    }
isSet() [2/2]
virtual bool OpenAPI::OAIObject::isSet () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 49 of file OAIObject.h.
                               {
        return false;
    }
isValid() [1/2]
virtual bool OpenAPI::OAIObject::isValid () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 53 of file OAIObject.h.
                                 {
        return true;
    }
isValid() [2/2]
virtual bool OpenAPI::OAIObject::isValid () const [inline], [virtual]
Reimplemented in OpenAPI::OAIIntersection_info, OpenAPI::OAILanelet_info, OpenAPI::OAIIntersection_info, and OpenAPI::OAILanelet_info.
Definition at line 53 of file OAIObject.h.
                                 {
        return true;
    }
Member Data Documentation
jObj
QJsonObject OpenAPI::OAIObject::jObj [private]
Definition at line 58 of file OAIObject.h.
Referenced by asJson(), asJsonObject(), fromJson(), and fromJsonObject().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIObject.h
streets_utils/streets_api/intersection_server_api/src/models/OAIObject.h