OpenAPI::OAIHttpFileElement Class Reference
#include <OAIHttpFileElement.h>
Public Member Functions
void setMimeType (const QString &mime)
void setFileName (const QString &name)
void setVariableName (const QString &name)
void setRequestFileName (const QString &name)
bool isSet () const
bool fromStringValue (const QString &instr)
bool fromJsonValue (const QJsonValue &jval)
bool fromByteArray (const QByteArray &bytes)
bool saveToFile (const QString &variable_name, const QString &local_filename, const QString &request_filename, const QString &mime, const QByteArray &bytes)
QString asJson () const
QJsonValue asJsonValue () const
QByteArray asByteArray () const
QByteArray loadFromFile (const QString &variable_name, const QString &local_filename, const QString &request_filename, const QString &mime)
void setMimeType (const QString &mime)
void setFileName (const QString &name)
void setVariableName (const QString &name)
void setRequestFileName (const QString &name)
bool isSet () const
bool fromStringValue (const QString &instr)
bool fromJsonValue (const QJsonValue &jval)
bool fromByteArray (const QByteArray &bytes)
bool saveToFile (const QString &variable_name, const QString &local_filename, const QString &request_filename, const QString &mime, const QByteArray &bytes)
QString asJson () const
QJsonValue asJsonValue () const
QByteArray asByteArray () const
QByteArray loadFromFile (const QString &variable_name, const QString &local_filename, const QString &request_filename, const QString &mime)
Public Attributes
QString variable_name
QString local_filename
QString request_filename
QString mime_type
Detailed Description
Definition at line 21 of file OAIHttpFileElement.h.
Member Function Documentation
asByteArray() [1/2]
QByteArray OpenAPI::OAIHttpFileElement::asByteArray () const
Definition at line 109 of file OAIHttpFileElement.cpp.
                                                 {
    QFile file(local_filename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << local_filename;
    }
    return bArray;
}
References local_filename.
Referenced by loadFromFile().
asByteArray() [2/2]
QByteArray OpenAPI::OAIHttpFileElement::asByteArray () const
asJson() [1/2]
QString OpenAPI::OAIHttpFileElement::asJson () const
Definition at line 41 of file OAIHttpFileElement.cpp.
                                         {
    QFile file(local_filename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << local_filename;
    }
    return QString(bArray);
}
References local_filename.
asJson() [2/2]
QString OpenAPI::OAIHttpFileElement::asJson () const
asJsonValue() [1/2]
QJsonValue OpenAPI::OAIHttpFileElement::asJsonValue () const
Definition at line 56 of file OAIHttpFileElement.cpp.
                                                 {
    QFile file(local_filename);
    QByteArray bArray;
    bool result = false;
    if (file.exists()) {
        result = file.open(QIODevice::ReadOnly);
        bArray = file.readAll();
        file.close();
    }
    if (!result) {
        qDebug() << "Error opening file " << local_filename;
    }
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    return QJsonDocument::fromJson(bArray.data()).object();
#else
    return QJsonDocument::fromBinaryData(bArray.data()).object();
#endif
}
References local_filename.
asJsonValue() [2/2]
QJsonValue OpenAPI::OAIHttpFileElement::asJsonValue () const
fromByteArray() [1/2]
bool OpenAPI::OAIHttpFileElement::fromByteArray (const QByteArray & bytes)
Definition at line 124 of file OAIHttpFileElement.cpp.
                                                              {
    QFile file(local_filename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
    file.write(bytes);
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << local_filename;
    }
    return result;
}
References local_filename.
Referenced by saveToFile().
fromByteArray() [2/2]
bool OpenAPI::OAIHttpFileElement::fromByteArray (const QByteArray & bytes)
fromJsonValue() [1/2]
bool OpenAPI::OAIHttpFileElement::fromJsonValue (const QJsonValue & jval)
Definition at line 90 of file OAIHttpFileElement.cpp.
                                                             {
    QFile file(local_filename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    file.write(QJsonDocument(jval.toObject()).toJson());
#else
    file.write(QJsonDocument(jval.toObject()).toBinaryData());
#endif
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << local_filename;
    }
    return result;
}
References local_filename.
fromJsonValue() [2/2]
bool OpenAPI::OAIHttpFileElement::fromJsonValue (const QJsonValue & jval)
fromStringValue() [1/2]
bool OpenAPI::OAIHttpFileElement::fromStringValue (const QString & instr)
Definition at line 75 of file OAIHttpFileElement.cpp.
                                                             {
    QFile file(local_filename);
    bool result = false;
    if (file.exists()) {
        file.remove();
    }
    result = file.open(QIODevice::WriteOnly);
    file.write(instr.toUtf8());
    file.close();
    if (!result) {
        qDebug() << "Error creating file " << local_filename;
    }
    return result;
}
References local_filename.
fromStringValue() [2/2]
bool OpenAPI::OAIHttpFileElement::fromStringValue (const QString & instr)
isSet() [1/2]
bool OpenAPI::OAIHttpFileElement::isSet () const
Definition at line 37 of file OAIHttpFileElement.cpp.
                                     {
    return !local_filename.isEmpty() || !request_filename.isEmpty();
}
References local_filename, and request_filename.
isSet() [2/2]
bool OpenAPI::OAIHttpFileElement::isSet () const
loadFromFile() [1/2]
QByteArray OpenAPI::OAIHttpFileElement::loadFromFile (const QString & variable_name, const QString & local_filename, const QString & request_filename, const QString & mime)
Definition at line 147 of file OAIHttpFileElement.cpp.
                                                                                                                                           {
    setMimeType(mime);
    setFileName(localFName);
    setVariableName(varName);
    setRequestFileName(reqFname);
    return asByteArray();
}
References asByteArray(), setFileName(), setMimeType(), setRequestFileName(), and setVariableName().
loadFromFile() [2/2]
QByteArray OpenAPI::OAIHttpFileElement::loadFromFile (const QString & variable_name, const QString & local_filename, const QString & request_filename, const QString & mime)
saveToFile() [1/2]
bool OpenAPI::OAIHttpFileElement::saveToFile (const QString & variable_name, const QString & local_filename, const QString & request_filename, const QString & mime, const QByteArray & bytes)
Definition at line 139 of file OAIHttpFileElement.cpp.
                                                                                                                                                            {
    setMimeType(mime);
    setFileName(localFName);
    setVariableName(varName);
    setRequestFileName(reqFname);
    return fromByteArray(bytes);
}
References fromByteArray(), setFileName(), setMimeType(), setRequestFileName(), and setVariableName().
Referenced by OpenAPI::OAIHttpRequestWorker::process_response().
saveToFile() [2/2]
bool OpenAPI::OAIHttpFileElement::saveToFile (const QString & variable_name, const QString & local_filename, const QString & request_filename, const QString & mime, const QByteArray & bytes)
setFileName() [1/2]
void OpenAPI::OAIHttpFileElement::setFileName (const QString & name)
Definition at line 25 of file OAIHttpFileElement.cpp.
                                                        {
    local_filename = name;
}
References local_filename.
Referenced by loadFromFile(), and saveToFile().
setFileName() [2/2]
void OpenAPI::OAIHttpFileElement::setFileName (const QString & name)
setMimeType() [1/2]
void OpenAPI::OAIHttpFileElement::setMimeType (const QString & mime)
Definition at line 21 of file OAIHttpFileElement.cpp.
                                                        {
    mime_type = mime;
}
References mime_type.
Referenced by loadFromFile(), and saveToFile().
setMimeType() [2/2]
void OpenAPI::OAIHttpFileElement::setMimeType (const QString & mime)
setRequestFileName() [1/2]
void OpenAPI::OAIHttpFileElement::setRequestFileName (const QString & name)
Definition at line 33 of file OAIHttpFileElement.cpp.
                                                               {
    request_filename = name;
}
References request_filename.
Referenced by loadFromFile(), and saveToFile().
setRequestFileName() [2/2]
void OpenAPI::OAIHttpFileElement::setRequestFileName (const QString & name)
setVariableName() [1/2]
void OpenAPI::OAIHttpFileElement::setVariableName (const QString & name)
Definition at line 29 of file OAIHttpFileElement.cpp.
                                                            {
    variable_name = name;
}
References variable_name.
Referenced by loadFromFile(), and saveToFile().
setVariableName() [2/2]
void OpenAPI::OAIHttpFileElement::setVariableName (const QString & name)
Member Data Documentation
local_filename
QString OpenAPI::OAIHttpFileElement::local_filename
Definition at line 25 of file OAIHttpFileElement.h.
Referenced by OpenAPI::OAIHttpRequestInput::add_file(), asByteArray(), asJson(), asJsonValue(), fromByteArray(), fromJsonValue(), fromStringValue(), isSet(), and setFileName().
mime_type
QString OpenAPI::OAIHttpFileElement::mime_type
Definition at line 27 of file OAIHttpFileElement.h.
Referenced by OpenAPI::OAIHttpRequestInput::add_file(), and setMimeType().
request_filename
QString OpenAPI::OAIHttpFileElement::request_filename
Definition at line 26 of file OAIHttpFileElement.h.
Referenced by OpenAPI::OAIHttpRequestInput::add_file(), isSet(), and setRequestFileName().
variable_name
QString OpenAPI::OAIHttpFileElement::variable_name
Definition at line 24 of file OAIHttpFileElement.h.
Referenced by OpenAPI::OAIHttpRequestInput::add_file(), and setVariableName().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIHttpFileElement.h
streets_utils/streets_api/intersection_server_api/src/models/OAIHttpFileElement.h
streets_utils/streets_api/intersection_client_api/OAIHttpFileElement.cpp
streets_utils/streets_api/intersection_server_api/src/models/OAIHttpFileElement.cpp