OpenAPI::OAIDefaultApiHandler Class Reference
#include <OAIDefaultApiHandler.h>
Public Slots
virtual void getConflictLanelets (qint32 link_lanelet_id)
virtual void getIntersectionInfo ()
virtual void listDepartureLanelets ()
virtual void listEntryLanelets ()
virtual void listLinkLanelets ()
Public Member Functions
OAIDefaultApiHandler ()
virtual ~OAIDefaultApiHandler ()
Detailed Description
Definition at line 23 of file OAIDefaultApiHandler.h.
Constructor & Destructor Documentation
OAIDefaultApiHandler()
OpenAPI::OAIDefaultApiHandler::OAIDefaultApiHandler ()
Definition at line 23 of file OAIDefaultApiHandler.cpp.
                                          {
}
 OAIDefaultApiHandler()
OpenAPI::OAIDefaultApiHandler::~OAIDefaultApiHandler () [virtual]
Definition at line 27 of file OAIDefaultApiHandler.cpp.
                                           {
}
Member Function Documentation
getConflictLanelets
void OpenAPI::OAIDefaultApiHandler::getConflictLanelets (qint32 link_lanelet_id) [virtual], [slot]
Definition at line 31 of file OAIDefaultApiHandler.cpp.
                                                                     {
    Q_UNUSED(link_lanelet_id);
    auto reqObj = qobject_cast<OAIDefaultApiRequest*>(sender());
    if(reqObj != nullptr)
    {
        QList<OAILanelet_info> res;
        reqObj->getConflictLaneletsResponse(res);
    }
}
Referenced by OpenAPI::OAIDefaultApiRequest::getConflictLaneletsRequest().
getIntersectionInfo
void OpenAPI::OAIDefaultApiHandler::getIntersectionInfo () [virtual], [slot]
Definition at line 40 of file OAIDefaultApiHandler.cpp.
                                               {
    auto reqObj = qobject_cast<OAIDefaultApiRequest*>(sender());
    if(reqObj != nullptr)
    {
        OAIIntersection_info res;
        reqObj->getIntersectionInfoResponse(res);
    }
}
Referenced by OpenAPI::OAIDefaultApiRequest::getIntersectionInfoRequest().
listDepartureLanelets
void OpenAPI::OAIDefaultApiHandler::listDepartureLanelets () [virtual], [slot]
Definition at line 48 of file OAIDefaultApiHandler.cpp.
                                                 {
    auto reqObj = qobject_cast<OAIDefaultApiRequest*>(sender());
    if(reqObj != nullptr)
    {
        QList<OAILanelet_info> res;
        reqObj->listDepartureLaneletsResponse(res);
    }
}
Referenced by OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsRequest().
listEntryLanelets
void OpenAPI::OAIDefaultApiHandler::listEntryLanelets () [virtual], [slot]
Definition at line 56 of file OAIDefaultApiHandler.cpp.
                                             {
    auto reqObj = qobject_cast<OAIDefaultApiRequest*>(sender());
    if(reqObj != nullptr)
    {
        QList<OAILanelet_info> res;
        reqObj->listEntryLaneletsResponse(res);
    }
}
Referenced by OpenAPI::OAIDefaultApiRequest::listEntryLaneletsRequest().
listLinkLanelets
void OpenAPI::OAIDefaultApiHandler::listLinkLanelets () [virtual], [slot]
Definition at line 64 of file OAIDefaultApiHandler.cpp.
                                            {
    auto reqObj = qobject_cast<OAIDefaultApiRequest*>(sender());
    if(reqObj != nullptr)
    {
        QList<OAILanelet_info> res;
        reqObj->listLinkLaneletsResponse(res);
    }
}
Referenced by OpenAPI::OAIDefaultApiRequest::listLinkLaneletsRequest().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_server_api/src/handlers/OAIDefaultApiHandler.h
streets_utils/streets_api/intersection_server_api/src/handlers/OAIDefaultApiHandler.cpp