message_services::models::mobilitypath Class Reference
#include <mobilitypath.h>
Public Member Functions
mobilitypath ()
virtual ~mobilitypath ()
virtual void fromJsonObject (const rapidjson::Value &obj)
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const
std::string generate_hash_sender_timestamp_id (std::string sender_bsm_id, uint64_t timestamp)
trajectory_t getTrajectory () const
void setTrajectory (trajectory_t trajectory)
mobility_header_t getHeader () const
void setHeader (mobility_header_t header)
Public Attributes
std::time_t msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Private Attributes
mobility_header_t header
trajectory_t trajectory
Friends
std::ostream & operator<< (std::ostream &out, mobilitypath &mobilitypath_obj)
Detailed Description
Definition at line 17 of file mobilitypath.h.
Constructor & Destructor Documentation
mobilitypath()
message_services::models::mobilitypath::mobilitypath ()
Definition at line 13 of file mobilitypath.cpp.
: header(), trajectory() {}
 mobilitypath()
message_services::models::mobilitypath::~mobilitypath () [virtual]
Definition at line 15 of file mobilitypath.cpp.
{}
Member Function Documentation
asJsonObject()
bool message_services::models::mobilitypath::asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > * writer) const [virtual]
Implements message_services::models::baseMessage.
Definition at line 119 of file mobilitypath.cpp.
        {
            try
            {
                writer->StartObject();
                writer->Key("header");
                writer->StartObject();
                writer->Key("sender_id");
                writer->String(this->getHeader().sender_id.c_str());
                writer->Key("recipient_id");
                writer->String(this->getHeader().recipient_id.c_str());
                writer->Key("plan_id");
                writer->String(this->getHeader().plan_id.c_str());
                writer->Key("timestamp");
                writer->Uint64(this->getHeader().timestamp);
                writer->EndObject();
                writer->Key("trajectory");
                writer->StartObject();
                writer->Key("location");
                writer->StartObject();
                writer->Key("ecef_x");
                writer->Uint64(this->getTrajectory().location.ecef_x);
                writer->Key("ecef_y");
                writer->Uint64(this->getTrajectory().location.ecef_y);
                writer->Key("ecef_z");
                writer->Uint64(this->getTrajectory().location.ecef_z);
                writer->Key("timestamp");
                writer->Uint64(this->getTrajectory().location.timestamp);
                writer->EndObject();
                writer->Key("offsets");
                for (int i = 0; i < this->getTrajectory().MAX_POINTS_IN_MESSAGE; i++)
                {
                    writer->StartObject();
                    writer->Key("offset_x");
                    writer->Uint64(this->getTrajectory().offsets[i].offset_z);
                    writer->Key("offset_y");
                    writer->Uint64(this->getTrajectory().offsets[i].offset_z);
                    writer->Key("offset_z");
                    writer->Uint64(this->getTrajectory().offsets[i].offset_z);
                    writer->EndObject();
                }
                writer->EndObject();
                writer->EndObject();
                return true;
            }
            catch (std::exception &ex)
            {
                SPDLOG_CRITICAL("mobilitypath model: ", ex.what());
                return false;
            }
        }
References getHeader(), getTrajectory(), simulate_bsm::i, message_services::models::trajectory::MAX_POINTS_IN_MESSAGE, message_services::models::trajectory::offsets, and simulate_mobilityoperation::timestamp.
fromJsonObject()
void message_services::models::mobilitypath::fromJsonObject (const rapidjson::Value & obj) [virtual]
Implements message_services::models::baseMessage.
Definition at line 17 of file mobilitypath.cpp.
        {
            if (obj.IsObject())
            {
                for (rapidjson::Value::ConstMemberIterator obj_itr = obj.MemberBegin(); obj_itr != obj.MemberEnd(); obj_itr++)
                {
                    if (obj_itr->value.IsObject() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("metadata")))
                    {
                        mobility_header_t header;
                        for (rapidjson::Value::ConstMemberIterator header_itr = obj_itr->value.MemberBegin(); header_itr != obj_itr->value.MemberEnd(); header_itr++)
                        {
                            if (std::string(header_itr->name.GetString()) == std::string("hostStaticId"))
                            {
                                header.sender_id = header_itr->value.GetString();
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("targetStaticId"))
                            {
                                header.recipient_id = (header_itr->value.GetString());
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("hostBSMId"))
                            {
                                header.sender_bsm_id = (header_itr->value.GetString());
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("planId"))
                            {
                                header.plan_id = (header_itr->value.GetString());
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("timestamp"))
                            {
                                header.timestamp = std::stol(header_itr->value.GetString());
                            }
                        }
                        setHeader(header);
                    }
                    if (obj_itr->value.IsObject() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("trajectory")))
                    {
                        // trajectory_t trajectory;
                        for (rapidjson::Value::ConstMemberIterator tr_itr = obj_itr->value.MemberBegin(); tr_itr != obj_itr->value.MemberEnd(); tr_itr++)
                        {
                            if (tr_itr->value.IsObject() && boost::iequals(std::string(tr_itr->name.GetString()), std::string("location")))
                            {
                                for (rapidjson::Value::ConstMemberIterator loc_itr = tr_itr->value.MemberBegin(); loc_itr != tr_itr->value.MemberEnd(); loc_itr++)
                                {
                                    if (std::string(loc_itr->name.GetString()) == std::string("ecefX"))
                                    {
                                        this->trajectory.location.ecef_x = (loc_itr->value.GetInt64());
                                    }
                                    if (std::string(loc_itr->name.GetString()) == std::string("ecefY"))
                                    {
                                        this->trajectory.location.ecef_y = (loc_itr->value.GetInt64());
                                    }
                                    if (std::string(loc_itr->name.GetString()) == std::string("ecefZ"))
                                    {
                                        this->trajectory.location.ecef_z = (loc_itr->value.GetInt64());
                                    }
                                    if (std::string(loc_itr->name.GetString()) == std::string("timestamp"))
                                    {
                                        this->trajectory.location.timestamp = std::stol(loc_itr->value.GetString());
                                    }
                                }
                            }
                            if (boost::iequals(std::string(tr_itr->name.GetString()), std::string("offsets")) && tr_itr->value.IsArray())
                            {
                                for (rapidjson::Value::ConstValueIterator offset_itr = tr_itr->value.Begin(); offset_itr != tr_itr->value.End(); offset_itr++)
                                {
                                    models::locationOffsetECEF offset;
                                    const rapidjson::Value &offset_value = *offset_itr;
                                    for (rapidjson::Value::ConstMemberIterator each_offset_itr = offset_value.MemberBegin(); each_offset_itr != offset_value.MemberEnd(); each_offset_itr++)
                                    {
                                        if (std::string(each_offset_itr->name.GetString()) == std::string("offsetX"))
                                        {
                                            offset.offset_x = (each_offset_itr->value.GetInt());
                                        }
                                        if (std::string(each_offset_itr->name.GetString()) == std::string("offsetY"))
                                        {
                                            offset.offset_y = (each_offset_itr->value.GetInt());
                                        }
                                        if (std::string(each_offset_itr->name.GetString()) == std::string("offsetZ"))
                                        {
                                            offset.offset_z = (each_offset_itr->value.GetInt());
                                        }
                                    }
                                    this->trajectory.offsets.push_back(offset);
                                }
                            }
                        }
                    }
                }
            }
        }
References message_services::models::locationECEF::ecef_x, message_services::models::locationECEF::ecef_y, message_services::models::locationECEF::ecef_z, header, message_services::models::trajectory::location, message_services::models::locationOffsetECEF::offset_x, message_services::models::locationOffsetECEF::offset_y, message_services::models::locationOffsetECEF::offset_z, message_services::models::trajectory::offsets, message_services::models::mobility_header::plan_id, message_services::models::mobility_header::recipient_id, message_services::models::mobility_header::sender_bsm_id, message_services::models::mobility_header::sender_id, setHeader(), message_services::models::locationECEF::timestamp, and message_services::models::mobility_header::timestamp.
generate_hash_sender_timestamp_id()
std::string message_services::models::mobilitypath::generate_hash_sender_timestamp_id (std::string sender_bsm_id, uint64_t timestamp)
Definition at line 186 of file mobilitypath.cpp.
        {
            std::stringstream hash_ss;
            hash_ss << sender_bsm_id << timestamp;
            return hash_ss.str();
        }
References simulate_mobilityoperation::timestamp.
Referenced by message_services::workers::mobilitypath_worker::process_incoming_msg().
getHeader()
mobility_header_t message_services::models::mobilitypath::getHeader () const
Definition at line 192 of file mobilitypath.cpp.
        {
            return this->header;
        }
References header.
Referenced by asJsonObject(), message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), message_services::workers::mobilitypath_worker::process_incoming_msg(), and message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilitypath_msg().
getTrajectory()
trajectory_t message_services::models::mobilitypath::getTrajectory () const
Definition at line 201 of file mobilitypath.cpp.
        {
            return this->trajectory;
        }
References trajectory.
Referenced by asJsonObject(), and message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent().
setHeader()
void message_services::models::mobilitypath::setHeader (mobility_header_t header)
Definition at line 196 of file mobilitypath.cpp.
        {
            this->header = header;
        }
References header.
Referenced by fromJsonObject().
setTrajectory()
void message_services::models::mobilitypath::setTrajectory (trajectory_t trajectory)
Definition at line 205 of file mobilitypath.cpp.
        {
            this->trajectory = trajectory;
        }
References trajectory.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, mobilitypath & mobilitypath_obj) [friend]
Definition at line 173 of file mobilitypath.cpp.
        {
            out << std::fixed;
            out << std::setprecision(6);
            out << "mobilitypath model: sender_id = " << mobilitypath_obj.header.sender_id
                      << ", sender_bsm_id =" << mobilitypath_obj.header.sender_bsm_id
                      << ", timestamp = " << mobilitypath_obj.header.timestamp
                      << ", location = { ecef_x= " << mobilitypath_obj.trajectory.location.ecef_x << ", ecef_y= "
                      << mobilitypath_obj.trajectory.location.ecef_y << ", ecef_z= " << mobilitypath_obj.trajectory.offsets[0].offset_x << ", offsets = { offset_x= " << mobilitypath_obj.trajectory.location.ecef_x << ", ecef_y= "
                      << mobilitypath_obj.trajectory.offsets[0].offset_y << ", offset_z= " << mobilitypath_obj.trajectory.offsets[0].offset_z << "}" << std::endl;
            return out;
        }
Member Data Documentation
header
mobility_header_t message_services::models::mobilitypath::header [private]
Definition at line 22 of file mobilitypath.h.
Referenced by fromJsonObject(), getHeader(), and setHeader().
msg_received_timestamp_
std::time_t message_services::models::mobilitypath::msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Definition at line 30 of file mobilitypath.h.
trajectory
trajectory_t message_services::models::mobilitypath::trajectory [private]
Definition at line 23 of file mobilitypath.h.
Referenced by getTrajectory(), and setTrajectory().
The documentation for this class was generated from the following files:
message_services/src/models/mobilitypath.h
message_services/src/models/mobilitypath.cpp