OpenAPI::OAIDefaultApi Class Reference
#include <OAIDefaultApi.h>
Signals
void getConflictLaneletsSignal (QList< OAILanelet_info > summary)
void getIntersectionInfoSignal (OAIIntersection_info summary)
void listDepartureLaneletsSignal (QList< OAILanelet_info > summary)
void listEntryLaneletsSignal (QList< OAILanelet_info > summary)
void listLinkLaneletsSignal (QList< OAILanelet_info > summary)
void getConflictLaneletsSignalFull (OAIHttpRequestWorker *worker, QList< OAILanelet_info > summary)
void getIntersectionInfoSignalFull (OAIHttpRequestWorker *worker, OAIIntersection_info summary)
void listDepartureLaneletsSignalFull (OAIHttpRequestWorker *worker, QList< OAILanelet_info > summary)
void listEntryLaneletsSignalFull (OAIHttpRequestWorker *worker, QList< OAILanelet_info > summary)
void listLinkLaneletsSignalFull (OAIHttpRequestWorker *worker, QList< OAILanelet_info > summary)
void getConflictLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str)
void getIntersectionInfoSignalE (OAIIntersection_info summary, QNetworkReply::NetworkError error_type, QString error_str)
void listDepartureLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str)
void listEntryLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str)
void listLinkLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str)
void getConflictLaneletsSignalEFull (OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str)
void getIntersectionInfoSignalEFull (OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str)
void listDepartureLaneletsSignalEFull (OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str)
void listEntryLaneletsSignalEFull (OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str)
void listLinkLaneletsSignalEFull (OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str)
void abortRequestsSignal ()
void allPendingRequestsCompleted ()
Public Member Functions
OAIDefaultApi (const int timeOut=0)
~OAIDefaultApi ()
void initializeServerConfigs ()
int setDefaultServerValue (int serverIndex, const QString &operation, const QString &variable, const QString &val)
void setServerIndex (const QString &operation, int serverIndex)
void setApiKey (const QString &apiKeyName, const QString &apiKey)
void setBearerToken (const QString &token)
void setUsername (const QString &username)
void setPassword (const QString &password)
void setTimeOut (const int timeOut)
void setWorkingDirectory (const QString &path)
void setNetworkAccessManager (QNetworkAccessManager *manager)
int addServerConfiguration (const QString &operation, const QUrl &url, const QString &description=``, const QMap< QString, OAIServerVariable > &variables=QMap< QString, OAIServerVariable >())
void setNewServerForAllOperations (const QUrl &url, const QString &description=``, const QMap< QString, OAIServerVariable > &variables=QMap< QString, OAIServerVariable >())
void setNewServer (const QString &operation, const QUrl &url, const QString &description=``, const QMap< QString, OAIServerVariable > &variables=QMap< QString, OAIServerVariable >())
void addHeaders (const QString &key, const QString &value)
void enableRequestCompression ()
void enableResponseCompression ()
void abortRequests ()
QString getParamStylePrefix (const QString &style)
QString getParamStyleSuffix (const QString &style)
QString getParamStyleDelimiter (const QString &style, const QString &name, bool isExplode)
void getConflictLanelets (const qint32 &link_lanelet_id)
void getIntersectionInfo ()
void listDepartureLanelets ()
void listEntryLanelets ()
void listLinkLanelets ()
Private Member Functions
void getConflictLaneletsCallback (OAIHttpRequestWorker *worker)
void getIntersectionInfoCallback (OAIHttpRequestWorker *worker)
void listDepartureLaneletsCallback (OAIHttpRequestWorker *worker)
void listEntryLaneletsCallback (OAIHttpRequestWorker *worker)
void listLinkLaneletsCallback (OAIHttpRequestWorker *worker)
Private Attributes
QMap< QString, int > _serverIndices
QMap< QString, QList< OAIServerConfiguration > > _serverConfigs
QMap< QString, QString > _apiKeys
QString _bearerToken
QString _username
QString _password
int _timeOut
QString _workingDirectory
QNetworkAccessManager * _manager
QMap< QString, QString > _defaultHeaders
bool _isResponseCompressionEnabled
bool _isRequestCompressionEnabled
Detailed Description
Definition at line 31 of file OAIDefaultApi.h.
Constructor & Destructor Documentation
OAIDefaultApi()
OpenAPI::OAIDefaultApi::OAIDefaultApi (const int timeOut = 0)
Definition at line 19 of file OAIDefaultApi.cpp.
    : _timeOut(timeOut),
      _manager(nullptr),
      _isResponseCompressionEnabled(false),
      _isRequestCompressionEnabled(false) {
    initializeServerConfigs();
}
References initializeServerConfigs().
 OAIDefaultApi()
OpenAPI::OAIDefaultApi::~OAIDefaultApi ()
Definition at line 27 of file OAIDefaultApi.cpp.
                              {
}
Member Function Documentation
abortRequests()
void OpenAPI::OAIDefaultApi::abortRequests ()
Definition at line 156 of file OAIDefaultApi.cpp.
                                  {
    emit abortRequestsSignal();
}
References abortRequestsSignal().
abortRequestsSignal
void OpenAPI::OAIDefaultApi::abortRequestsSignal () [signal]
Referenced by abortRequests(), getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), and listLinkLanelets().
addHeaders()
void OpenAPI::OAIDefaultApi::addHeaders (const QString & key, const QString & value)
Definition at line 144 of file OAIDefaultApi.cpp.
                                                                       {
    _defaultHeaders.insert(key, value);
}
References _defaultHeaders, and simulate_bsm::value.
addServerConfiguration()
int OpenAPI::OAIDefaultApi::addServerConfiguration (const QString & operation, const QUrl & url, const QString & description = ``, const QMap< QString, OAIServerVariable > & variables = QMap<QString, OAIServerVariable>())
Appends a new ServerConfiguration to the config map for a specific operation.
Parameters
operation The id to the target operation.
url A string that contains the URL of the server
description A String that describes the server
variables A map between a variable name and its value. The value is used for substitution in the server's URL template. returns the index of the new server config on success and -1 if the operation is not found
Definition at line 104 of file OAIDefaultApi.cpp.
                                                                                                                                                                  {
    if (_serverConfigs.contains(operation)) {
        _serverConfigs[operation].append(OAIServerConfiguration(
                    url,
                    description,
                    variables));
        return _serverConfigs[operation].size()-1;
    } else {
        return -1;
    }
}
References _serverConfigs.
Referenced by setNewServer(), and setNewServerForAllOperations().
allPendingRequestsCompleted
void OpenAPI::OAIDefaultApi::allPendingRequestsCompleted () [signal]
Referenced by getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), and listLinkLanelets().
enableRequestCompression()
void OpenAPI::OAIDefaultApi::enableRequestCompression ()
Definition at line 148 of file OAIDefaultApi.cpp.
                                             {
    _isRequestCompressionEnabled = true;
}
References _isRequestCompressionEnabled.
enableResponseCompression()
void OpenAPI::OAIDefaultApi::enableResponseCompression ()
Definition at line 152 of file OAIDefaultApi.cpp.
                                              {
    _isResponseCompressionEnabled = true;
}
References _isResponseCompressionEnabled.
getConflictLanelets()
void OpenAPI::OAIDefaultApi::getConflictLanelets (const qint32 & link_lanelet_id)
Parameters
 in link_lanelet_id qint32 [required]
Definition at line 223 of file OAIDefaultApi.cpp.
                                                                     {
    QString fullPath = QString(_serverConfigs["getConflictLanelets"][_serverIndices.value("getConflictLanelets")].URL()+"/get_conflict_lanelets/{link_lanelet_id}");
    
    
    {
        QString link_lanelet_idPathParam("{");
        link_lanelet_idPathParam.append("link_lanelet_id").append("}");
        QString pathPrefix, pathSuffix, pathDelimiter;
        QString pathStyle = "simple";
        if (pathStyle == "")
            pathStyle = "simple";
        pathPrefix = getParamStylePrefix(pathStyle);
        pathSuffix = getParamStyleSuffix(pathStyle);
        pathDelimiter = getParamStyleDelimiter(pathStyle, "link_lanelet_id", false);
        QString paramString = (pathStyle == "matrix") ? pathPrefix+"link_lanelet_id"+pathSuffix : pathPrefix;
        fullPath.replace(link_lanelet_idPathParam, paramString+QUrl::toPercentEncoding(::OpenAPI::toStringValue(link_lanelet_id)));
    }
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    OAIHttpRequestInput input(fullPath, "GET");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }
#else
    for (auto key : _defaultHeaders.keys()) {
        input.headers.insert(key, _defaultHeaders[key]);
    }
#endif
    connect(worker, &OAIHttpRequestWorker::on_execution_finished, this, &OAIDefaultApi::getConflictLaneletsCallback);
    connect(this, &OAIDefaultApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this]() {
        if (findChildren<OAIHttpRequestWorker*>().count() == 0) {
            emit allPendingRequestsCompleted();
        }
    });
    worker->execute(&input);
}
References _defaultHeaders, _manager, _serverConfigs, _serverIndices, _timeOut, _workingDirectory, abortRequestsSignal(), allPendingRequestsCompleted(), simulate_bsm::count, OpenAPI::OAIHttpRequestWorker::execute(), getConflictLaneletsCallback(), getParamStyleDelimiter(), getParamStylePrefix(), getParamStyleSuffix(), OpenAPI::OAIHttpRequestInput::headers, OpenAPI::OAIHttpRequestWorker::on_execution_finished(), OpenAPI::OAIHttpRequestWorker::setTimeOut(), OpenAPI::OAIHttpRequestWorker::setWorkingDirectory(), and OpenAPI::toStringValue().
getConflictLaneletsCallback()
void OpenAPI::OAIDefaultApi::getConflictLaneletsCallback (OAIHttpRequestWorker * worker) [private]
Definition at line 267 of file OAIDefaultApi.cpp.
                                                                            {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;
    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    QList<OAILanelet_info> output;
    QString json(worker->response);
    QByteArray array(json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();
    foreach (QJsonValue obj, jsonArray) {
        OAILanelet_info val;
        ::OpenAPI::fromJsonValue(val, obj);
        output.append(val);
    }
    worker->deleteLater();
    if (worker->error_type == QNetworkReply::NoError) {
        emit getConflictLaneletsSignal(output);
        emit getConflictLaneletsSignalFull(worker, output);
    } else {
        emit getConflictLaneletsSignalE(output, error_type, error_str);
        emit getConflictLaneletsSignalEFull(worker, error_type, error_str);
    }
}
References OpenAPI::OAIHttpRequestWorker::error_str, OpenAPI::OAIHttpRequestWorker::error_type, OpenAPI::fromJsonValue(), getConflictLaneletsSignal(), getConflictLaneletsSignalE(), getConflictLaneletsSignalEFull(), getConflictLaneletsSignalFull(), and OpenAPI::OAIHttpRequestWorker::response.
Referenced by getConflictLanelets().
getConflictLaneletsSignal
void OpenAPI::OAIDefaultApi::getConflictLaneletsSignal (QList< OAILanelet_info > summary) [signal]
Referenced by getConflictLaneletsCallback().
getConflictLaneletsSignalE
void OpenAPI::OAIDefaultApi::getConflictLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by getConflictLaneletsCallback().
getConflictLaneletsSignalEFull
void OpenAPI::OAIDefaultApi::getConflictLaneletsSignalEFull (OAIHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by getConflictLaneletsCallback().
getConflictLaneletsSignalFull
void OpenAPI::OAIDefaultApi::getConflictLaneletsSignalFull (OAIHttpRequestWorker * worker, QList< OAILanelet_info > summary) [signal]
Referenced by getConflictLaneletsCallback().
getIntersectionInfo()
void OpenAPI::OAIDefaultApi::getIntersectionInfo ()
Definition at line 295 of file OAIDefaultApi.cpp.
                                        {
    QString fullPath = QString(_serverConfigs["getIntersectionInfo"][_serverIndices.value("getIntersectionInfo")].URL()+"/info");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    OAIHttpRequestInput input(fullPath, "GET");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }
#else
    for (auto key : _defaultHeaders.keys()) {
        input.headers.insert(key, _defaultHeaders[key]);
    }
#endif
    connect(worker, &OAIHttpRequestWorker::on_execution_finished, this, &OAIDefaultApi::getIntersectionInfoCallback);
    connect(this, &OAIDefaultApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this]() {
        if (findChildren<OAIHttpRequestWorker*>().count() == 0) {
            emit allPendingRequestsCompleted();
        }
    });
    worker->execute(&input);
}
References _defaultHeaders, _manager, _serverConfigs, _serverIndices, _timeOut, _workingDirectory, abortRequestsSignal(), allPendingRequestsCompleted(), simulate_bsm::count, OpenAPI::OAIHttpRequestWorker::execute(), getIntersectionInfoCallback(), OpenAPI::OAIHttpRequestInput::headers, OpenAPI::OAIHttpRequestWorker::on_execution_finished(), OpenAPI::OAIHttpRequestWorker::setTimeOut(), and OpenAPI::OAIHttpRequestWorker::setWorkingDirectory().
Referenced by intersection_client::call(), scheduling_service::intersection_client::request_intersection_info(), signal_opt_service::signal_opt_messages_worker::request_intersection_info(), and traffic_signal_controller_service::intersection_client::request_intersection_info().
getIntersectionInfoCallback()
void OpenAPI::OAIDefaultApi::getIntersectionInfoCallback (OAIHttpRequestWorker * worker) [private]
Definition at line 325 of file OAIDefaultApi.cpp.
                                                                            {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;
    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    OAIIntersection_info output(QString(worker->response));
    worker->deleteLater();
    if (worker->error_type == QNetworkReply::NoError) {
        emit getIntersectionInfoSignal(output);
        emit getIntersectionInfoSignalFull(worker, output);
    } else {
        emit getIntersectionInfoSignalE(output, error_type, error_str);
        emit getIntersectionInfoSignalEFull(worker, error_type, error_str);
    }
}
References OpenAPI::OAIHttpRequestWorker::error_str, OpenAPI::OAIHttpRequestWorker::error_type, getIntersectionInfoSignal(), getIntersectionInfoSignalE(), getIntersectionInfoSignalEFull(), getIntersectionInfoSignalFull(), and OpenAPI::OAIHttpRequestWorker::response.
Referenced by getIntersectionInfo().
getIntersectionInfoSignal
void OpenAPI::OAIDefaultApi::getIntersectionInfoSignal (OAIIntersection_info summary) [signal]
Referenced by getIntersectionInfoCallback(), scheduling_service::intersection_client::request_intersection_info(), signal_opt_service::signal_opt_messages_worker::request_intersection_info(), and traffic_signal_controller_service::intersection_client::request_intersection_info().
getIntersectionInfoSignalE
void OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE (OAIIntersection_info summary, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by getIntersectionInfoCallback(), scheduling_service::intersection_client::request_intersection_info(), signal_opt_service::signal_opt_messages_worker::request_intersection_info(), and traffic_signal_controller_service::intersection_client::request_intersection_info().
getIntersectionInfoSignalEFull
void OpenAPI::OAIDefaultApi::getIntersectionInfoSignalEFull (OAIHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by getIntersectionInfoCallback().
getIntersectionInfoSignalFull
void OpenAPI::OAIDefaultApi::getIntersectionInfoSignalFull (OAIHttpRequestWorker * worker, OAIIntersection_info summary) [signal]
Referenced by getIntersectionInfoCallback().
getParamStyleDelimiter()
QString OpenAPI::OAIDefaultApi::getParamStyleDelimiter (const QString & style, const QString & name, bool isExplode)
Definition at line 196 of file OAIDefaultApi.cpp.
                                                                                                       {
    if (style == "matrix") {
        return (isExplode) ? ";" + name + "=" : ",";
    } else if (style == "label") {
        return (isExplode) ? "." : ",";
    } else if (style == "form") {
        return (isExplode) ? "&" + name + "=" : ",";
    } else if (style == "simple") {
        return ",";
    } else if (style == "spaceDelimited") {
        return (isExplode) ? "&" + name + "=" : " ";
    } else if (style == "pipeDelimited") {
        return (isExplode) ? "&" + name + "=" : "|";
    } else if (style == "deepObject") {
        return (isExplode) ? "&" : "none";
    } else {
        return "none";
    }
}
Referenced by getConflictLanelets().
getParamStylePrefix()
QString OpenAPI::OAIDefaultApi::getParamStylePrefix (const QString & style)
Definition at line 160 of file OAIDefaultApi.cpp.
                                                               {
    if (style == "matrix") {
        return ";";
    } else if (style == "label") {
        return ".";
    } else if (style == "form") {
        return "&";
    } else if (style == "simple") {
        return "";
    } else if (style == "spaceDelimited") {
        return "&";
    } else if (style == "pipeDelimited") {
        return "&";
    } else {
        return "none";
    }
}
Referenced by getConflictLanelets().
getParamStyleSuffix()
QString OpenAPI::OAIDefaultApi::getParamStyleSuffix (const QString & style)
Definition at line 178 of file OAIDefaultApi.cpp.
                                                               {
    if (style == "matrix") {
        return "=";
    } else if (style == "label") {
        return "";
    } else if (style == "form") {
        return "=";
    } else if (style == "simple") {
        return "";
    } else if (style == "spaceDelimited") {
        return "=";
    } else if (style == "pipeDelimited") {
        return "=";
    } else {
        return "none";
    }
}
Referenced by getConflictLanelets().
initializeServerConfigs()
void OpenAPI::OAIDefaultApi::initializeServerConfigs ()
Definition at line 30 of file OAIDefaultApi.cpp.
                                            {
    //Default server
    QList<OAIServerConfiguration> defaultConf = QList<OAIServerConfiguration>();
    //varying endpoint server
    defaultConf.append(OAIServerConfiguration(
    QUrl("http://localhost:8080/intersection_model/v1"),
    "No description provided",
    QMap<QString, OAIServerVariable>()));
    _serverConfigs.insert("getConflictLanelets", defaultConf);
    _serverIndices.insert("getConflictLanelets", 0);
    _serverConfigs.insert("getIntersectionInfo", defaultConf);
    _serverIndices.insert("getIntersectionInfo", 0);
    _serverConfigs.insert("listDepartureLanelets", defaultConf);
    _serverIndices.insert("listDepartureLanelets", 0);
    _serverConfigs.insert("listEntryLanelets", defaultConf);
    _serverIndices.insert("listEntryLanelets", 0);
    _serverConfigs.insert("listLinkLanelets", defaultConf);
    _serverIndices.insert("listLinkLanelets", 0);
}
References _serverConfigs, and _serverIndices.
Referenced by OAIDefaultApi().
listDepartureLanelets()
void OpenAPI::OAIDefaultApi::listDepartureLanelets ()
Definition at line 344 of file OAIDefaultApi.cpp.
                                          {
    QString fullPath = QString(_serverConfigs["listDepartureLanelets"][_serverIndices.value("listDepartureLanelets")].URL()+"/departure_lanelets");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    OAIHttpRequestInput input(fullPath, "GET");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }
#else
    for (auto key : _defaultHeaders.keys()) {
        input.headers.insert(key, _defaultHeaders[key]);
    }
#endif
    connect(worker, &OAIHttpRequestWorker::on_execution_finished, this, &OAIDefaultApi::listDepartureLaneletsCallback);
    connect(this, &OAIDefaultApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this]() {
        if (findChildren<OAIHttpRequestWorker*>().count() == 0) {
            emit allPendingRequestsCompleted();
        }
    });
    worker->execute(&input);
}
References _defaultHeaders, _manager, _serverConfigs, _serverIndices, _timeOut, _workingDirectory, abortRequestsSignal(), allPendingRequestsCompleted(), simulate_bsm::count, OpenAPI::OAIHttpRequestWorker::execute(), OpenAPI::OAIHttpRequestInput::headers, listDepartureLaneletsCallback(), OpenAPI::OAIHttpRequestWorker::on_execution_finished(), OpenAPI::OAIHttpRequestWorker::setTimeOut(), and OpenAPI::OAIHttpRequestWorker::setWorkingDirectory().
listDepartureLaneletsCallback()
void OpenAPI::OAIDefaultApi::listDepartureLaneletsCallback (OAIHttpRequestWorker * worker) [private]
Definition at line 374 of file OAIDefaultApi.cpp.
                                                                              {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;
    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    QList<OAILanelet_info> output;
    QString json(worker->response);
    QByteArray array(json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();
    foreach (QJsonValue obj, jsonArray) {
        OAILanelet_info val;
        ::OpenAPI::fromJsonValue(val, obj);
        output.append(val);
    }
    worker->deleteLater();
    if (worker->error_type == QNetworkReply::NoError) {
        emit listDepartureLaneletsSignal(output);
        emit listDepartureLaneletsSignalFull(worker, output);
    } else {
        emit listDepartureLaneletsSignalE(output, error_type, error_str);
        emit listDepartureLaneletsSignalEFull(worker, error_type, error_str);
    }
}
References OpenAPI::OAIHttpRequestWorker::error_str, OpenAPI::OAIHttpRequestWorker::error_type, OpenAPI::fromJsonValue(), listDepartureLaneletsSignal(), listDepartureLaneletsSignalE(), listDepartureLaneletsSignalEFull(), listDepartureLaneletsSignalFull(), and OpenAPI::OAIHttpRequestWorker::response.
Referenced by listDepartureLanelets().
listDepartureLaneletsSignal
void OpenAPI::OAIDefaultApi::listDepartureLaneletsSignal (QList< OAILanelet_info > summary) [signal]
Referenced by listDepartureLaneletsCallback().
listDepartureLaneletsSignalE
void OpenAPI::OAIDefaultApi::listDepartureLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listDepartureLaneletsCallback().
listDepartureLaneletsSignalEFull
void OpenAPI::OAIDefaultApi::listDepartureLaneletsSignalEFull (OAIHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listDepartureLaneletsCallback().
listDepartureLaneletsSignalFull
void OpenAPI::OAIDefaultApi::listDepartureLaneletsSignalFull (OAIHttpRequestWorker * worker, QList< OAILanelet_info > summary) [signal]
Referenced by listDepartureLaneletsCallback().
listEntryLanelets()
void OpenAPI::OAIDefaultApi::listEntryLanelets ()
Definition at line 402 of file OAIDefaultApi.cpp.
                                      {
    QString fullPath = QString(_serverConfigs["listEntryLanelets"][_serverIndices.value("listEntryLanelets")].URL()+"/entry_lanelets");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    OAIHttpRequestInput input(fullPath, "GET");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }
#else
    for (auto key : _defaultHeaders.keys()) {
        input.headers.insert(key, _defaultHeaders[key]);
    }
#endif
    connect(worker, &OAIHttpRequestWorker::on_execution_finished, this, &OAIDefaultApi::listEntryLaneletsCallback);
    connect(this, &OAIDefaultApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this]() {
        if (findChildren<OAIHttpRequestWorker*>().count() == 0) {
            emit allPendingRequestsCompleted();
        }
    });
    worker->execute(&input);
}
References _defaultHeaders, _manager, _serverConfigs, _serverIndices, _timeOut, _workingDirectory, abortRequestsSignal(), allPendingRequestsCompleted(), simulate_bsm::count, OpenAPI::OAIHttpRequestWorker::execute(), OpenAPI::OAIHttpRequestInput::headers, listEntryLaneletsCallback(), OpenAPI::OAIHttpRequestWorker::on_execution_finished(), OpenAPI::OAIHttpRequestWorker::setTimeOut(), and OpenAPI::OAIHttpRequestWorker::setWorkingDirectory().
listEntryLaneletsCallback()
void OpenAPI::OAIDefaultApi::listEntryLaneletsCallback (OAIHttpRequestWorker * worker) [private]
Definition at line 432 of file OAIDefaultApi.cpp.
                                                                          {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;
    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    QList<OAILanelet_info> output;
    QString json(worker->response);
    QByteArray array(json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();
    foreach (QJsonValue obj, jsonArray) {
        OAILanelet_info val;
        ::OpenAPI::fromJsonValue(val, obj);
        output.append(val);
    }
    worker->deleteLater();
    if (worker->error_type == QNetworkReply::NoError) {
        emit listEntryLaneletsSignal(output);
        emit listEntryLaneletsSignalFull(worker, output);
    } else {
        emit listEntryLaneletsSignalE(output, error_type, error_str);
        emit listEntryLaneletsSignalEFull(worker, error_type, error_str);
    }
}
References OpenAPI::OAIHttpRequestWorker::error_str, OpenAPI::OAIHttpRequestWorker::error_type, OpenAPI::fromJsonValue(), listEntryLaneletsSignal(), listEntryLaneletsSignalE(), listEntryLaneletsSignalEFull(), listEntryLaneletsSignalFull(), and OpenAPI::OAIHttpRequestWorker::response.
Referenced by listEntryLanelets().
listEntryLaneletsSignal
void OpenAPI::OAIDefaultApi::listEntryLaneletsSignal (QList< OAILanelet_info > summary) [signal]
Referenced by listEntryLaneletsCallback().
listEntryLaneletsSignalE
void OpenAPI::OAIDefaultApi::listEntryLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listEntryLaneletsCallback().
listEntryLaneletsSignalEFull
void OpenAPI::OAIDefaultApi::listEntryLaneletsSignalEFull (OAIHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listEntryLaneletsCallback().
listEntryLaneletsSignalFull
void OpenAPI::OAIDefaultApi::listEntryLaneletsSignalFull (OAIHttpRequestWorker * worker, QList< OAILanelet_info > summary) [signal]
Referenced by listEntryLaneletsCallback().
listLinkLanelets()
void OpenAPI::OAIDefaultApi::listLinkLanelets ()
Definition at line 460 of file OAIDefaultApi.cpp.
                                     {
    QString fullPath = QString(_serverConfigs["listLinkLanelets"][_serverIndices.value("listLinkLanelets")].URL()+"/link_lanelets");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    OAIHttpRequestInput input(fullPath, "GET");
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }
#else
    for (auto key : _defaultHeaders.keys()) {
        input.headers.insert(key, _defaultHeaders[key]);
    }
#endif
    connect(worker, &OAIHttpRequestWorker::on_execution_finished, this, &OAIDefaultApi::listLinkLaneletsCallback);
    connect(this, &OAIDefaultApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this]() {
        if (findChildren<OAIHttpRequestWorker*>().count() == 0) {
            emit allPendingRequestsCompleted();
        }
    });
    worker->execute(&input);
}
References _defaultHeaders, _manager, _serverConfigs, _serverIndices, _timeOut, _workingDirectory, abortRequestsSignal(), allPendingRequestsCompleted(), simulate_bsm::count, OpenAPI::OAIHttpRequestWorker::execute(), OpenAPI::OAIHttpRequestInput::headers, listLinkLaneletsCallback(), OpenAPI::OAIHttpRequestWorker::on_execution_finished(), OpenAPI::OAIHttpRequestWorker::setTimeOut(), and OpenAPI::OAIHttpRequestWorker::setWorkingDirectory().
listLinkLaneletsCallback()
void OpenAPI::OAIDefaultApi::listLinkLaneletsCallback (OAIHttpRequestWorker * worker) [private]
Definition at line 490 of file OAIDefaultApi.cpp.
                                                                         {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;
    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    QList<OAILanelet_info> output;
    QString json(worker->response);
    QByteArray array(json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();
    foreach (QJsonValue obj, jsonArray) {
        OAILanelet_info val;
        ::OpenAPI::fromJsonValue(val, obj);
        output.append(val);
    }
    worker->deleteLater();
    if (worker->error_type == QNetworkReply::NoError) {
        emit listLinkLaneletsSignal(output);
        emit listLinkLaneletsSignalFull(worker, output);
    } else {
        emit listLinkLaneletsSignalE(output, error_type, error_str);
        emit listLinkLaneletsSignalEFull(worker, error_type, error_str);
    }
}
References OpenAPI::OAIHttpRequestWorker::error_str, OpenAPI::OAIHttpRequestWorker::error_type, OpenAPI::fromJsonValue(), listLinkLaneletsSignal(), listLinkLaneletsSignalE(), listLinkLaneletsSignalEFull(), listLinkLaneletsSignalFull(), and OpenAPI::OAIHttpRequestWorker::response.
Referenced by listLinkLanelets().
listLinkLaneletsSignal
void OpenAPI::OAIDefaultApi::listLinkLaneletsSignal (QList< OAILanelet_info > summary) [signal]
Referenced by listLinkLaneletsCallback().
listLinkLaneletsSignalE
void OpenAPI::OAIDefaultApi::listLinkLaneletsSignalE (QList< OAILanelet_info > summary, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listLinkLaneletsCallback().
listLinkLaneletsSignalEFull
void OpenAPI::OAIDefaultApi::listLinkLaneletsSignalEFull (OAIHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString error_str) [signal]
Referenced by listLinkLaneletsCallback().
listLinkLaneletsSignalFull
void OpenAPI::OAIDefaultApi::listLinkLaneletsSignalFull (OAIHttpRequestWorker * worker, QList< OAILanelet_info > summary) [signal]
Referenced by listLinkLaneletsCallback().
setApiKey()
void OpenAPI::OAIDefaultApi::setApiKey (const QString & apiKeyName, const QString & apiKey)
Definition at line 67 of file OAIDefaultApi.cpp.
                                                                              {
    _apiKeys.insert(apiKeyName,apiKey);
}
References _apiKeys.
setBearerToken()
void OpenAPI::OAIDefaultApi::setBearerToken (const QString & token)
Definition at line 71 of file OAIDefaultApi.cpp.
                                                       {
    _bearerToken = token;
}
References _bearerToken.
setDefaultServerValue()
int OpenAPI::OAIDefaultApi::setDefaultServerValue (int serverIndex, const QString & operation, const QString & variable, const QString & value)
returns 0 on success and -1, -2 or -3 on failure. -1 when the variable does not exist and -2 if the value is not defined in the enum and -3 if the operation or server index is not found
Definition at line 54 of file OAIDefaultApi.cpp.
                                                                                                                                 {
    auto it = _serverConfigs.find(operation);
    if (it != _serverConfigs.end() && serverIndex < it.value().size()) {
      return _serverConfigs[operation][serverIndex].setDefaultValue(variable,value);
    }
    return -3;
}
References _serverConfigs, and simulate_bsm::value.
setNetworkAccessManager()
void OpenAPI::OAIDefaultApi::setNetworkAccessManager (QNetworkAccessManager * manager)
Definition at line 92 of file OAIDefaultApi.cpp.
                                                                          {
    _manager = manager;
}
References _manager.
setNewServer()
void OpenAPI::OAIDefaultApi::setNewServer (const QString & operation, const QUrl & url, const QString & description = ``, const QMap< QString, OAIServerVariable > & variables = QMap<QString, OAIServerVariable>())
Appends a new ServerConfiguration to the config map for an operations and sets the index to that server.
Parameters
URL A string that contains the URL of the server
description A String that describes the server
variables A map between a variable name and its value. The value is used for substitution in the server's URL template.
Definition at line 140 of file OAIDefaultApi.cpp.
                                                                                                                                                         {
    setServerIndex(operation, addServerConfiguration(operation, url, description, variables));
}
References addServerConfiguration(), and setServerIndex().
setNewServerForAllOperations()
void OpenAPI::OAIDefaultApi::setNewServerForAllOperations (const QUrl & url, const QString & description = ``, const QMap< QString, OAIServerVariable > & variables = QMap<QString, OAIServerVariable>())
Appends a new ServerConfiguration to the config map for a all operations and sets the index to that server.
Parameters
url A string that contains the URL of the server
description A String that describes the server
variables A map between a variable name and its value. The value is used for substitution in the server's URL template.
Definition at line 122 of file OAIDefaultApi.cpp.
                                                                                                                                               {
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
    for (auto keyIt = _serverIndices.keyBegin(); keyIt != _serverIndices.keyEnd(); keyIt++) {
        setServerIndex(*keyIt, addServerConfiguration(*keyIt, url, description, variables));
    }
#else
    for (auto &e : _serverIndices.keys()) {
        setServerIndex(e, addServerConfiguration(e, url, description, variables));
    }
#endif
}
References _serverIndices, addServerConfiguration(), and setServerIndex().
setPassword()
void OpenAPI::OAIDefaultApi::setPassword (const QString & password)
Definition at line 79 of file OAIDefaultApi.cpp.
                                                       {
    _password = password;
}
References _password.
setServerIndex()
void OpenAPI::OAIDefaultApi::setServerIndex (const QString & operation, int serverIndex)
Definition at line 61 of file OAIDefaultApi.cpp.
                                                                            {
    if (_serverIndices.contains(operation) && serverIndex < _serverConfigs.find(operation).value().size()) {
        _serverIndices[operation] = serverIndex;
    }
}
References _serverConfigs, and _serverIndices.
Referenced by setNewServer(), and setNewServerForAllOperations().
setTimeOut()
void OpenAPI::OAIDefaultApi::setTimeOut (const int timeOut)
Definition at line 84 of file OAIDefaultApi.cpp.
                                                {
    _timeOut = timeOut;
}
References _timeOut.
setUsername()
void OpenAPI::OAIDefaultApi::setUsername (const QString & username)
Definition at line 75 of file OAIDefaultApi.cpp.
                                                       {
    _username = username;
}
References _username.
setWorkingDirectory()
void OpenAPI::OAIDefaultApi::setWorkingDirectory (const QString & path)
Definition at line 88 of file OAIDefaultApi.cpp.
                                                           {
    _workingDirectory = path;
}
References _workingDirectory.
Member Data Documentation
_apiKeys
QMap<QString, QString> OpenAPI::OAIDefaultApi::_apiKeys [private]
Definition at line 80 of file OAIDefaultApi.h.
Referenced by setApiKey().
_bearerToken
QString OpenAPI::OAIDefaultApi::_bearerToken [private]
Definition at line 81 of file OAIDefaultApi.h.
Referenced by setBearerToken().
_defaultHeaders
QMap<QString, QString> OpenAPI::OAIDefaultApi::_defaultHeaders [private]
Definition at line 87 of file OAIDefaultApi.h.
Referenced by addHeaders(), getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), and listLinkLanelets().
_isRequestCompressionEnabled
bool OpenAPI::OAIDefaultApi::_isRequestCompressionEnabled [private]
Definition at line 89 of file OAIDefaultApi.h.
Referenced by enableRequestCompression().
_isResponseCompressionEnabled
bool OpenAPI::OAIDefaultApi::_isResponseCompressionEnabled [private]
Definition at line 88 of file OAIDefaultApi.h.
Referenced by enableResponseCompression().
_manager
QNetworkAccessManager* OpenAPI::OAIDefaultApi::_manager [private]
Definition at line 86 of file OAIDefaultApi.h.
Referenced by getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), listLinkLanelets(), and setNetworkAccessManager().
_password
QString OpenAPI::OAIDefaultApi::_password [private]
Definition at line 83 of file OAIDefaultApi.h.
Referenced by setPassword().
_serverConfigs
QMap<QString,QList<OAIServerConfiguration> > OpenAPI::OAIDefaultApi::_serverConfigs [private]
Definition at line 79 of file OAIDefaultApi.h.
Referenced by addServerConfiguration(), getConflictLanelets(), getIntersectionInfo(), initializeServerConfigs(), listDepartureLanelets(), listEntryLanelets(), listLinkLanelets(), setDefaultServerValue(), and setServerIndex().
_serverIndices
QMap<QString,int> OpenAPI::OAIDefaultApi::_serverIndices [private]
Definition at line 78 of file OAIDefaultApi.h.
Referenced by getConflictLanelets(), getIntersectionInfo(), initializeServerConfigs(), listDepartureLanelets(), listEntryLanelets(), listLinkLanelets(), setNewServerForAllOperations(), and setServerIndex().
_timeOut
int OpenAPI::OAIDefaultApi::_timeOut [private]
Definition at line 84 of file OAIDefaultApi.h.
Referenced by getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), listLinkLanelets(), and setTimeOut().
_username
QString OpenAPI::OAIDefaultApi::_username [private]
Definition at line 82 of file OAIDefaultApi.h.
Referenced by setUsername().
_workingDirectory
QString OpenAPI::OAIDefaultApi::_workingDirectory [private]
Definition at line 85 of file OAIDefaultApi.h.
Referenced by getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), listLinkLanelets(), and setWorkingDirectory().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIDefaultApi.h
streets_utils/streets_api/intersection_client_api/OAIDefaultApi.cpp