OpenAPI::OAIApiRequestHandler Class Reference
#include <OAIApiRouter.h>
Signals
void requestReceived (QHttpEngine::Socket *socket)
Protected Member Functions
virtual void process (QHttpEngine::Socket *socket, const QString &path)
Detailed Description
Definition at line 32 of file OAIApiRouter.h.
Member Function Documentation
process()
virtual void OpenAPI::OAIApiRequestHandler::process (QHttpEngine::Socket * socket, const QString & path) [inline], [protected], [virtual]
Definition at line 39 of file OAIApiRouter.h.
                                                                        {
        Q_UNUSED(path);
        // If the slot requires all data to be received, check to see if this is
        // already the case, otherwise, wait until the rest of it arrives
        if (socket->bytesAvailable() >= socket->contentLength()) {
            emit requestReceived(socket);
        } else {
            connect(socket, &QHttpEngine::Socket::readChannelFinished, [this, socket]() {
                emit requestReceived(socket);
            });
        }
    }
References requestReceived().
requestReceived
void OpenAPI::OAIApiRequestHandler::requestReceived (QHttpEngine::Socket * socket) [signal]
Referenced by main(), and process().
The documentation for this class was generated from the following file:
streets_utils/streets_api/intersection_server_api/src/handlers/OAIApiRouter.h