traffic_signal_controller_service::intersection_client Class Reference
#include <intersection_client.h>
Public Member Functions
bool request_intersection_info ()
std::string get_intersection_name () const
int get_intersection_id () const
Private Attributes
std::string intersection_name
int intersection_id
Detailed Description
Definition at line 11 of file intersection_client.h.
Member Function Documentation
get_intersection_id()
int intersection_client::get_intersection_id () const
Definition at line 33 of file intersection_client.cpp.
                                                      {
        return intersection_id;
    }
References intersection_id.
get_intersection_name()
std::string intersection_client::get_intersection_name () const
Definition at line 29 of file intersection_client.cpp.
                                                               {
        return intersection_name;
    }
References intersection_name.
request_intersection_info()
bool intersection_client::request_intersection_info ()
Definition at line 5 of file intersection_client.cpp.
                                                        {
        bool successful = false;
        OpenAPI::OAIDefaultApi apiInstance;
        QEventLoop loop;
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignal, [this, &successful, &loop](const OpenAPI::OAIIntersection_info &int_info){
            intersection_name = int_info.getName().toStdString();
            intersection_id = int_info.getId();
            successful = true;
            loop.quit();
        });
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE, [&loop]([[maybe_unused]]const OpenAPI::OAIIntersection_info &int_info, QNetworkReply::NetworkError, QString error_str){
            SPDLOG_ERROR("Error happened while issuing intersection model GET information request : {0}", error_str.toStdString());
            loop.quit();
         });
        apiInstance.getIntersectionInfo();
        QTimer::singleShot(5000, &loop, &QEventLoop::quit);
        loop.exec();
        return successful;
    }
References OpenAPI::OAIIntersection_info::getId(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignal(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE(), OpenAPI::OAIIntersection_info::getName(), intersection_id, and intersection_name.
Member Data Documentation
intersection_id
int traffic_signal_controller_service::intersection_client::intersection_id [private]
Definition at line 14 of file intersection_client.h.
Referenced by get_intersection_id(), and request_intersection_info().
intersection_name
std::string traffic_signal_controller_service::intersection_client::intersection_name [private]
Definition at line 13 of file intersection_client.h.
Referenced by get_intersection_name(), and request_intersection_info().
The documentation for this class was generated from the following files:
tsc_client_service/include/intersection_client.h
tsc_client_service/src/intersection_client.cpp