OpenAPI::OAIHttpRequestWorker Class Reference
#include <OAIHttpRequest.h>
Signals
void on_execution_finished (OAIHttpRequestWorker *worker)
Public Member Functions
OAIHttpRequestWorker (QObject *parent=nullptr, QNetworkAccessManager *manager=nullptr)
virtual ~OAIHttpRequestWorker ()
QMap< QString, QString > getResponseHeaders () const
QString http_attribute_encode (QString attribute_name, QString input)
void execute (OAIHttpRequestInput *input)
void setTimeOut (int timeOutMs)
void setWorkingDirectory (const QString &path)
OAIHttpFileElement getHttpFileElement (const QString &fieldname=QString())
QByteArray * getMultiPartField (const QString &fieldname=QString())
void setResponseCompressionEnabled (bool enable)
void setRequestCompressionEnabled (bool enable)
int getHttpResponseCode () const
Public Attributes
QByteArray response
QNetworkReply::NetworkError error_type
QString error_str
Static Public Attributes
static QSslConfiguration * sslDefaultConfiguration
Private Types
enum OAICompressionType { Zlib
, Gzip
 }
Private Member Functions
void on_reply_timeout (QNetworkReply *reply)
void on_reply_finished (QNetworkReply *reply)
void process_response (QNetworkReply *reply)
QByteArray decompress (const QByteArray &data)
QByteArray compress (const QByteArray &input, int level, OAICompressionType compressType)
Private Attributes
QNetworkAccessManager * manager
QMap< QString, QString > headers
QMap< QString, OAIHttpFileElement > files
QMap< QString, QByteArray * > multiPartFields
QString workingDirectory
QTimer timeOutTimer
bool isResponseCompressionEnabled
bool isRequestCompressionEnabled
int httpResponseCode
QRandomGenerator randomGenerator
Detailed Description
Definition at line 60 of file OAIHttpRequest.h.
Member Enumeration Documentation
OAICompressionType
enum OpenAPI::OAIHttpRequestWorker::OAICompressionType [private]
Enumerator
Zlib
Gzip
Definition at line 87 of file OAIHttpRequest.h.
                           {
        Zlib,
        Gzip
    };
Constructor & Destructor Documentation
OAIHttpRequestWorker()
OpenAPI::OAIHttpRequestWorker::OAIHttpRequestWorker (QObject * parent = nullptr, QNetworkAccessManager * manager = nullptr) [explicit]
Definition at line 59 of file OAIHttpRequest.cpp.
    : QObject(parent), manager(_manager), timeOutTimer(this), isResponseCompressionEnabled(false), isRequestCompressionEnabled(false), httpResponseCode(-1) {
#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
    randomGenerator = QRandomGenerator(QDateTime::currentDateTime().toSecsSinceEpoch());
#else
    qsrand(QDateTime::currentDateTime().toTime_t());
#endif
    if (manager == nullptr) {
        manager = new QNetworkAccessManager(this);
    }
    workingDirectory = QDir::currentPath();
    timeOutTimer.setSingleShot(true);
}
References manager, randomGenerator, timeOutTimer, and workingDirectory.
 OAIHttpRequestWorker()
OpenAPI::OAIHttpRequestWorker::~OAIHttpRequestWorker () [virtual]
Definition at line 75 of file OAIHttpRequest.cpp.
                                            {
    QObject::disconnect(&timeOutTimer, &QTimer::timeout, nullptr, nullptr);
    timeOutTimer.stop();
    for (const auto &item : multiPartFields) {
        if (item != nullptr) {
            delete item;
        }
    }
}
References multiPartFields, and timeOutTimer.
Member Function Documentation
compress()
QByteArray OpenAPI::OAIHttpRequestWorker::compress (const QByteArray & input, int level, OAICompressionType compressType) [private]
Definition at line 495 of file OAIHttpRequest.cpp.
                                                                                                             {
    
    Q_UNUSED(input);
    Q_UNUSED(level);
    Q_UNUSED(compressType);
    return QByteArray();
}
Referenced by execute().
decompress()
QByteArray OpenAPI::OAIHttpRequestWorker::decompress (const QByteArray & data) [private]
Definition at line 489 of file OAIHttpRequest.cpp.
                                                                 {
    
    Q_UNUSED(data);
    return QByteArray();
}
References simulate_bsm::data.
Referenced by process_response().
execute()
void OpenAPI::OAIHttpRequestWorker::execute (OAIHttpRequestInput * input)
Definition at line 177 of file OAIHttpRequest.cpp.
                                                             {
    // reset variables
    QNetworkReply *reply = nullptr;
    QByteArray request_content = "";
    response = "";
    error_type = QNetworkReply::NoError;
    error_str = "";
    bool isFormData = false;
    // decide on the variable layout
    if (input->files.length() > 0) {
        input->var_layout = MULTIPART;
    }
    if (input->var_layout == NOT_SET) {
        input->var_layout = input->http_method == "GET" || input->http_method == "HEAD" ? ADDRESS : URL_ENCODED;
    }
    // prepare request content
    QString boundary = "";
    if (input->var_layout == ADDRESS || input->var_layout == URL_ENCODED) {
        // variable layout is ADDRESS or URL_ENCODED
        if (input->vars.count() > 0) {
            bool first = true;
            isFormData = true;
            foreach (QString key, input->vars.keys()) {
                if (!first) {
                    request_content.append("&");
                }
                first = false;
                request_content.append(QUrl::toPercentEncoding(key));
                request_content.append("=");
                request_content.append(QUrl::toPercentEncoding(input->vars.value(key)));
            }
            if (input->var_layout == ADDRESS) {
                input->url_str += "?" + request_content;
                request_content = "";
            }
        }
    } else {
        // variable layout is MULTIPART
        boundary = QString("__-----------------------%1%2")
                    #if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
                            .arg(QDateTime::currentDateTime().toSecsSinceEpoch())
                            .arg(randomGenerator.generate());
                    #else
                            .arg(QDateTime::currentDateTime().toTime_t())
                            .arg(qrand());
                    #endif
        QString boundary_delimiter = "--";
        QString new_line = "\r\n";
        // add variables
        foreach (QString key, input->vars.keys()) {
            // add boundary
            request_content.append(boundary_delimiter.toUtf8());
            request_content.append(boundary.toUtf8());
            request_content.append(new_line.toUtf8());
            // add header
            request_content.append("Content-Disposition: form-data; ");
            request_content.append(http_attribute_encode("name", key).toUtf8());
            request_content.append(new_line.toUtf8());
            request_content.append("Content-Type: text/plain");
            request_content.append(new_line.toUtf8());
            // add header to body splitter
            request_content.append(new_line.toUtf8());
            // add variable content
            request_content.append(input->vars.value(key).toUtf8());
            request_content.append(new_line.toUtf8());
        }
        // add files
        for (QList<OAIHttpFileElement>::iterator file_info = input->files.begin(); file_info != input->files.end(); file_info++) {
            QFileInfo fi(file_info->local_filename);
            // ensure necessary variables are available
            if (file_info->local_filename == nullptr
                || file_info->local_filename.isEmpty()
                || file_info->variable_name == nullptr
                || file_info->variable_name.isEmpty()
                || !fi.exists()
                || !fi.isFile()
                || !fi.isReadable()) {
                // silent abort for the current file
                continue;
            }
            QFile file(file_info->local_filename);
            if (!file.open(QIODevice::ReadOnly)) {
                // silent abort for the current file
                continue;
            }
            // ensure filename for the request
            if (file_info->request_filename == nullptr || file_info->request_filename.isEmpty()) {
                file_info->request_filename = fi.fileName();
                if (file_info->request_filename.isEmpty()) {
                    file_info->request_filename = "file";
                }
            }
            // add boundary
            request_content.append(boundary_delimiter.toUtf8());
            request_content.append(boundary.toUtf8());
            request_content.append(new_line.toUtf8());
            // add header
            request_content.append(
                QString("Content-Disposition: form-data; %1; %2").arg(http_attribute_encode("name", file_info->variable_name), http_attribute_encode("filename", file_info->request_filename)).toUtf8());
            request_content.append(new_line.toUtf8());
            if (file_info->mime_type != nullptr && !file_info->mime_type.isEmpty()) {
                request_content.append("Content-Type: ");
                request_content.append(file_info->mime_type.toUtf8());
                request_content.append(new_line.toUtf8());
            }
            request_content.append("Content-Transfer-Encoding: binary");
            request_content.append(new_line.toUtf8());
            // add header to body splitter
            request_content.append(new_line.toUtf8());
            // add file content
            request_content.append(file.readAll());
            request_content.append(new_line.toUtf8());
            file.close();
        }
        // add end of body
        request_content.append(boundary_delimiter.toUtf8());
        request_content.append(boundary.toUtf8());
        request_content.append(boundary_delimiter.toUtf8());
    }
    if (input->request_body.size() > 0) {
        qDebug() << "got a request body";
        request_content.clear();
        if(!isFormData && (input->var_layout != MULTIPART) && isRequestCompressionEnabled){
            request_content.append(compress(input->request_body, 7, OAICompressionType::Gzip));
        } else {
            request_content.append(input->request_body);
        }
    }
    // prepare connection
    QNetworkRequest request = QNetworkRequest(QUrl(input->url_str));
    if (OAIHttpRequestWorker::sslDefaultConfiguration != nullptr) {
        request.setSslConfiguration(*OAIHttpRequestWorker::sslDefaultConfiguration);
    }
    request.setRawHeader("User-Agent", "OpenAPI-Generator/1.0.0/cpp-qt");
    foreach (QString key, input->headers.keys()) { request.setRawHeader(key.toStdString().c_str(), input->headers.value(key).toStdString().c_str()); }
    if (request_content.size() > 0 && !isFormData && (input->var_layout != MULTIPART)) {
        if (!input->headers.contains("Content-Type")) {
            request.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
        } else {
            request.setHeader(QNetworkRequest::ContentTypeHeader, input->headers.value("Content-Type"));
        }
        if(isRequestCompressionEnabled){
            request.setRawHeader("Content-Encoding", "gzip");
        }
    } else if (input->var_layout == URL_ENCODED) {
        request.setHeader(QNetworkRequest::ContentTypeHeader, "application/x-www-form-urlencoded");
    } else if (input->var_layout == MULTIPART) {
        request.setHeader(QNetworkRequest::ContentTypeHeader, "multipart/form-data; boundary=" + boundary);
    }
    if(isResponseCompressionEnabled){
        request.setRawHeader("Accept-Encoding", "gzip");
    } else {
        request.setRawHeader("Accept-Encoding", "identity");
    }
    if (input->http_method == "GET") {
        reply = manager->get(request);
    } else if (input->http_method == "POST") {
        reply = manager->post(request, request_content);
    } else if (input->http_method == "PUT") {
        reply = manager->put(request, request_content);
    } else if (input->http_method == "HEAD") {
        reply = manager->head(request);
    } else if (input->http_method == "DELETE") {
        reply = manager->deleteResource(request);
    } else {
#if (QT_VERSION >= 0x050800)
        reply = manager->sendCustomRequest(request, input->http_method.toLatin1(), request_content);
#else
        QBuffer *buffer = new QBuffer;
        buffer->setData(request_content);
        buffer->open(QIODevice::ReadOnly);
        reply = manager->sendCustomRequest(request, input->http_method.toLatin1(), buffer);
        buffer->setParent(reply);
#endif
    }
    if (reply != nullptr) {
        reply->setParent(this);
        connect(reply, &QNetworkReply::finished, [this, reply] {
            on_reply_finished(reply);
        });
    }
    if (timeOutTimer.interval() > 0) {
        QObject::connect(&timeOutTimer, &QTimer::timeout, [this, reply] {
            on_reply_timeout(reply);
        });
        timeOutTimer.start();
    }
}
References OpenAPI::ADDRESS, compress(), error_str, error_type, OpenAPI::OAIHttpRequestInput::files, OpenAPI::OAIHttpRequestInput::headers, http_attribute_encode(), OpenAPI::OAIHttpRequestInput::http_method, isRequestCompressionEnabled, isResponseCompressionEnabled, manager, OpenAPI::MULTIPART, OpenAPI::NOT_SET, on_reply_finished(), on_reply_timeout(), randomGenerator, OpenAPI::OAIHttpRequestInput::request_body, response, sslDefaultConfiguration, timeOutTimer, OpenAPI::URL_ENCODED, OpenAPI::OAIHttpRequestInput::url_str, OpenAPI::OAIHttpRequestInput::var_layout, and OpenAPI::OAIHttpRequestInput::vars.
Referenced by OpenAPI::OAIDefaultApi::getConflictLanelets(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::listDepartureLanelets(), OpenAPI::OAIDefaultApi::listEntryLanelets(), and OpenAPI::OAIDefaultApi::listLinkLanelets().
getHttpFileElement()
OAIHttpFileElement OpenAPI::OAIHttpRequestWorker::getHttpFileElement (const QString & fieldname = QString())
Definition at line 89 of file OAIHttpRequest.cpp.
                                                                                    {
    if (!files.isEmpty()) {
        if (fieldname.isEmpty()) {
            return files.first();
        } else if (files.contains(fieldname)) {
            return files[fieldname];
        }
    }
    return OAIHttpFileElement();
}
References files.
getHttpResponseCode()
int OpenAPI::OAIHttpRequestWorker::getHttpResponseCode () const
Definition at line 132 of file OAIHttpRequest.cpp.
                                                    {
    return httpResponseCode;
}
References httpResponseCode.
getMultiPartField()
QByteArray * OpenAPI::OAIHttpRequestWorker::getMultiPartField (const QString & fieldname = QString())
Definition at line 100 of file OAIHttpRequest.cpp.
                                                                            {
    if (!multiPartFields.isEmpty()) {
        if (fieldname.isEmpty()) {
            return multiPartFields.first();
        } else if (multiPartFields.contains(fieldname)) {
            return multiPartFields[fieldname];
        }
    }
    return nullptr;
}
References multiPartFields.
getResponseHeaders()
QMap< QString, QString > OpenAPI::OAIHttpRequestWorker::getResponseHeaders () const
Definition at line 85 of file OAIHttpRequest.cpp.
                                                                      {
    return headers;
}
References headers.
Referenced by process_response().
http_attribute_encode()
QString OpenAPI::OAIHttpRequestWorker::http_attribute_encode (QString attribute_name, QString input)
Definition at line 136 of file OAIHttpRequest.cpp.
                                                                                         {
    // result structure follows RFC 5987
    bool need_utf_encoding = false;
    QString result = "";
    QByteArray input_c = input.toLocal8Bit();
    char c;
    for (int i = 0; i < input_c.length(); i++) {
        c = input_c.at(i);
        if (c == '\\' || c == '/' || c == '\0' || c < ' ' || c > '~') {
            // ignore and request utf-8 version
            need_utf_encoding = true;
        } else if (c == '"') {
            result += "\\\"";
        } else {
            result += c;
        }
    }
    if (result.length() == 0) {
        need_utf_encoding = true;
    }
    if (!need_utf_encoding) {
        // return simple version
        return QString("%1=\"%2\"").arg(attribute_name, result);
    }
    QString result_utf8 = "";
    for (int i = 0; i < input_c.length(); i++) {
        c = input_c.at(i);
        if ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
            result_utf8 += c;
        } else {
            result_utf8 += "%" + QString::number(static_cast<unsigned char>(input_c.at(i)), 16).toUpper();
        }
    }
    // return enhanced version with UTF-8 support
    return QString("%1=\"%2\"; %1*=utf-8''%3").arg(attribute_name, result, result_utf8);
}
References simulate_bsm::i.
Referenced by execute().
on_execution_finished
void OpenAPI::OAIHttpRequestWorker::on_execution_finished (OAIHttpRequestWorker * worker) [signal]
Referenced by OpenAPI::OAIDefaultApi::getConflictLanelets(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::listDepartureLanelets(), OpenAPI::OAIDefaultApi::listEntryLanelets(), OpenAPI::OAIDefaultApi::listLinkLanelets(), on_reply_finished(), and on_reply_timeout().
on_reply_finished()
void OpenAPI::OAIHttpRequestWorker::on_reply_finished (QNetworkReply * reply) [private]
Definition at line 398 of file OAIHttpRequest.cpp.
                                                                 {
    bool codeSts = false;
    if(timeOutTimer.isActive()) {
        QObject::disconnect(&timeOutTimer, &QTimer::timeout, nullptr, nullptr);
        timeOutTimer.stop();
    }
    error_type = reply->error();
    error_str = reply->errorString();
    if (reply->rawHeaderPairs().count() > 0) {
        for (const auto &item : reply->rawHeaderPairs()) {
            headers.insert(item.first, item.second);
        }
    }
    auto rescode = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt(&codeSts);
    if(codeSts){
        httpResponseCode = rescode;
    } else{
        httpResponseCode = -1;
    }
    process_response(reply);
    reply->deleteLater();
    emit on_execution_finished(this);
}
References error_str, error_type, headers, httpResponseCode, on_execution_finished(), process_response(), and timeOutTimer.
Referenced by execute().
on_reply_timeout()
void OpenAPI::OAIHttpRequestWorker::on_reply_timeout (QNetworkReply * reply) [private]
Definition at line 422 of file OAIHttpRequest.cpp.
                                                                {
    error_type = QNetworkReply::TimeoutError;
    response = "";
    error_str = "Timed out waiting for response";
    disconnect(reply, nullptr, nullptr, nullptr);
    reply->abort();
    reply->deleteLater();
    emit on_execution_finished(this);
}
References error_str, error_type, on_execution_finished(), and response.
Referenced by execute().
process_response()
void OpenAPI::OAIHttpRequestWorker::process_response (QNetworkReply * reply) [private]
Definition at line 432 of file OAIHttpRequest.cpp.
                                                                {
    QString contentDispositionHdr;
    QString contentTypeHdr;
    QString contentEncodingHdr;
    for(auto hdr: getResponseHeaders().keys()){
        if(hdr.compare(QString("Content-Disposition"), Qt::CaseInsensitive) == 0){
            contentDispositionHdr = getResponseHeaders().value(hdr);
        }
        if(hdr.compare(QString("Content-Type"), Qt::CaseInsensitive) == 0){
            contentTypeHdr = getResponseHeaders().value(hdr);
        }
        if(hdr.compare(QString("Content-Encoding"), Qt::CaseInsensitive) == 0){
            contentEncodingHdr = getResponseHeaders().value(hdr);
        }
    }
    if (!contentDispositionHdr.isEmpty()) {
        auto contentDisposition = contentDispositionHdr.split(QString(";"), SKIP_EMPTY_PARTS);
        auto contentType =
            !contentTypeHdr.isEmpty() ? contentTypeHdr.split(QString(";"), SKIP_EMPTY_PARTS).first() : QString();
        if ((contentDisposition.count() > 0) && (contentDisposition.first() == QString("attachment"))) {
            QString filename = QUuid::createUuid().toString();
            for (const auto &file : contentDisposition) {
                if (file.contains(QString("filename"))) {
                    filename = file.split(QString("="), SKIP_EMPTY_PARTS).at(1);
                    break;
                }
            }
            OAIHttpFileElement felement;
            felement.saveToFile(QString(), workingDirectory + QDir::separator() + filename, filename, contentType, reply->readAll());
            files.insert(filename, felement);
        }
    } else if (!contentTypeHdr.isEmpty()) {
        auto contentType = contentTypeHdr.split(QString(";"), SKIP_EMPTY_PARTS);
        if ((contentType.count() > 0) && (contentType.first() == QString("multipart/form-data"))) {
            // TODO : Handle Multipart responses
        } else {
            if(!contentEncodingHdr.isEmpty()){
                auto encoding = contentEncodingHdr.split(QString(";"), SKIP_EMPTY_PARTS);
                if(encoding.count() > 0){
                    auto compressionTypes = encoding.first().split(',', SKIP_EMPTY_PARTS);
                    if(compressionTypes.contains("gzip", Qt::CaseInsensitive) || compressionTypes.contains("deflate", Qt::CaseInsensitive)){
                        response = decompress(reply->readAll());
                    } else if(compressionTypes.contains("identity", Qt::CaseInsensitive)){
                        response = reply->readAll();
                    }
                }
            }
            else {
                response = reply->readAll();
            }
        }
    }
}
References decompress(), files, getResponseHeaders(), response, OpenAPI::OAIHttpFileElement::saveToFile(), SKIP_EMPTY_PARTS, and workingDirectory.
Referenced by on_reply_finished().
setRequestCompressionEnabled()
void OpenAPI::OAIHttpRequestWorker::setRequestCompressionEnabled (bool enable)
Definition at line 128 of file OAIHttpRequest.cpp.
                                                                   {
    isRequestCompressionEnabled = enable;
}
References isRequestCompressionEnabled.
setResponseCompressionEnabled()
void OpenAPI::OAIHttpRequestWorker::setResponseCompressionEnabled (bool enable)
Definition at line 124 of file OAIHttpRequest.cpp.
                                                                    {
    isResponseCompressionEnabled = enable;
}
References isResponseCompressionEnabled.
setTimeOut()
void OpenAPI::OAIHttpRequestWorker::setTimeOut (int timeOutMs)
Definition at line 111 of file OAIHttpRequest.cpp.
                                                   {
    timeOutTimer.setInterval(timeOutMs);
    if(timeOutTimer.interval() == 0) {
        QObject::disconnect(&timeOutTimer, &QTimer::timeout, nullptr, nullptr);
    }
}
References timeOutTimer.
Referenced by OpenAPI::OAIDefaultApi::getConflictLanelets(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::listDepartureLanelets(), OpenAPI::OAIDefaultApi::listEntryLanelets(), and OpenAPI::OAIDefaultApi::listLinkLanelets().
setWorkingDirectory()
void OpenAPI::OAIHttpRequestWorker::setWorkingDirectory (const QString & path)
Definition at line 118 of file OAIHttpRequest.cpp.
                                                                  {
    if (!path.isEmpty()) {
        workingDirectory = path;
    }
}
References workingDirectory.
Referenced by OpenAPI::OAIDefaultApi::getConflictLanelets(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::listDepartureLanelets(), OpenAPI::OAIDefaultApi::listEntryLanelets(), and OpenAPI::OAIDefaultApi::listLinkLanelets().
Member Data Documentation
error_str
QString OpenAPI::OAIHttpRequestWorker::error_str
Definition at line 69 of file OAIHttpRequest.h.
Referenced by execute(), OpenAPI::OAIDefaultApi::getConflictLaneletsCallback(), OpenAPI::OAIDefaultApi::getIntersectionInfoCallback(), OpenAPI::OAIDefaultApi::listDepartureLaneletsCallback(), OpenAPI::OAIDefaultApi::listEntryLaneletsCallback(), OpenAPI::OAIDefaultApi::listLinkLaneletsCallback(), on_reply_finished(), and on_reply_timeout().
error_type
QNetworkReply::NetworkError OpenAPI::OAIHttpRequestWorker::error_type
Definition at line 68 of file OAIHttpRequest.h.
Referenced by execute(), OpenAPI::OAIDefaultApi::getConflictLaneletsCallback(), OpenAPI::OAIDefaultApi::getIntersectionInfoCallback(), OpenAPI::OAIDefaultApi::listDepartureLaneletsCallback(), OpenAPI::OAIDefaultApi::listEntryLaneletsCallback(), OpenAPI::OAIDefaultApi::listLinkLaneletsCallback(), on_reply_finished(), and on_reply_timeout().
files
QMap<QString, OAIHttpFileElement> OpenAPI::OAIHttpRequestWorker::files [private]
Definition at line 93 of file OAIHttpRequest.h.
Referenced by getHttpFileElement(), and process_response().
headers
QMap<QString, QString> OpenAPI::OAIHttpRequestWorker::headers [private]
Definition at line 92 of file OAIHttpRequest.h.
Referenced by getResponseHeaders(), and on_reply_finished().
httpResponseCode
int OpenAPI::OAIHttpRequestWorker::httpResponseCode [private]
Definition at line 99 of file OAIHttpRequest.h.
Referenced by getHttpResponseCode(), and on_reply_finished().
isRequestCompressionEnabled
bool OpenAPI::OAIHttpRequestWorker::isRequestCompressionEnabled [private]
Definition at line 98 of file OAIHttpRequest.h.
Referenced by execute(), and setRequestCompressionEnabled().
isResponseCompressionEnabled
bool OpenAPI::OAIHttpRequestWorker::isResponseCompressionEnabled [private]
Definition at line 97 of file OAIHttpRequest.h.
Referenced by execute(), and setResponseCompressionEnabled().
manager
QNetworkAccessManager* OpenAPI::OAIHttpRequestWorker::manager [private]
Definition at line 91 of file OAIHttpRequest.h.
Referenced by OAIHttpRequestWorker(), and execute().
multiPartFields
QMap<QString, QByteArray *> OpenAPI::OAIHttpRequestWorker::multiPartFields [private]
Definition at line 94 of file OAIHttpRequest.h.
Referenced by ~OAIHttpRequestWorker(), and getMultiPartField().
randomGenerator
QRandomGenerator OpenAPI::OAIHttpRequestWorker::randomGenerator [private]
Definition at line 101 of file OAIHttpRequest.h.
Referenced by OAIHttpRequestWorker(), and execute().
response
QByteArray OpenAPI::OAIHttpRequestWorker::response
Definition at line 67 of file OAIHttpRequest.h.
Referenced by execute(), OpenAPI::OAIDefaultApi::getConflictLaneletsCallback(), OpenAPI::OAIDefaultApi::getIntersectionInfoCallback(), OpenAPI::OAIDefaultApi::listDepartureLaneletsCallback(), OpenAPI::OAIDefaultApi::listEntryLaneletsCallback(), OpenAPI::OAIDefaultApi::listLinkLaneletsCallback(), on_reply_timeout(), and process_response().
sslDefaultConfiguration
QSslConfiguration * OpenAPI::OAIHttpRequestWorker::sslDefaultConfiguration [static]
Definition at line 74 of file OAIHttpRequest.h.
Referenced by execute().
timeOutTimer
QTimer OpenAPI::OAIHttpRequestWorker::timeOutTimer [private]
Definition at line 96 of file OAIHttpRequest.h.
Referenced by OAIHttpRequestWorker(), ~OAIHttpRequestWorker(), execute(), on_reply_finished(), and setTimeOut().
workingDirectory
QString OpenAPI::OAIHttpRequestWorker::workingDirectory [private]
Definition at line 95 of file OAIHttpRequest.h.
Referenced by OAIHttpRequestWorker(), process_response(), and setWorkingDirectory().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIHttpRequest.h
streets_utils/streets_api/intersection_client_api/OAIHttpRequest.cpp