OpenAPI Namespace Reference
Classes
class OAIApiRequestHandler
class OAIApiRouter
class OAIDefaultApi
class OAIDefaultApiHandler
class OAIDefaultApiRequest
class OAIEnum
class OAIHttpFileElement
class OAIHttpRequestInput
class OAIHttpRequestWorker
class OAIIntersection_info
class OAILanelet_info
class OAIObject
class OAISerializerSettings
class OAIServerConfiguration
class OAIServerVariable
class OptionalParam
Enumerations
enum OAIHttpRequestVarLayout { NOT_SET
, ADDRESS
, URL_ENCODED
, MULTIPART
 }
Functions
bool setDateTimeFormat (const QString &dateTimeFormat)
bool setDateTimeFormat (const Qt::DateFormat &dateTimeFormat)
QString toStringValue (const QString &value)
QString toStringValue (const QDateTime &value)
QString toStringValue (const QByteArray &value)
QString toStringValue (const QDate &value)
QString toStringValue (const qint32 &value)
QString toStringValue (const qint64 &value)
QString toStringValue (const bool &value)
QString toStringValue (const float &value)
QString toStringValue (const double &value)
QString toStringValue (const OAIObject &value)
QString toStringValue (const OAIEnum &value)
QString toStringValue (const OAIHttpFileElement &value)
QJsonValue toJsonValue (const QString &value)
QJsonValue toJsonValue (const QDateTime &value)
QJsonValue toJsonValue (const QByteArray &value)
QJsonValue toJsonValue (const QDate &value)
QJsonValue toJsonValue (const qint32 &value)
QJsonValue toJsonValue (const qint64 &value)
QJsonValue toJsonValue (const bool &value)
QJsonValue toJsonValue (const float &value)
QJsonValue toJsonValue (const double &value)
QJsonValue toJsonValue (const OAIObject &value)
QJsonValue toJsonValue (const OAIEnum &value)
QJsonValue toJsonValue (const OAIHttpFileElement &value)
bool fromStringValue (const QString &inStr, QString &value)
bool fromStringValue (const QString &inStr, QDateTime &value)
bool fromStringValue (const QString &inStr, QByteArray &value)
bool fromStringValue (const QString &inStr, QDate &value)
bool fromStringValue (const QString &inStr, qint32 &value)
bool fromStringValue (const QString &inStr, qint64 &value)
bool fromStringValue (const QString &inStr, bool &value)
bool fromStringValue (const QString &inStr, float &value)
bool fromStringValue (const QString &inStr, double &value)
bool fromStringValue (const QString &inStr, OAIObject &value)
bool fromStringValue (const QString &inStr, OAIEnum &value)
bool fromStringValue (const QString &inStr, OAIHttpFileElement &value)
bool fromJsonValue (QString &value, const QJsonValue &jval)
bool fromJsonValue (QDateTime &value, const QJsonValue &jval)
bool fromJsonValue (QByteArray &value, const QJsonValue &jval)
bool fromJsonValue (QDate &value, const QJsonValue &jval)
bool fromJsonValue (qint32 &value, const QJsonValue &jval)
bool fromJsonValue (qint64 &value, const QJsonValue &jval)
bool fromJsonValue (bool &value, const QJsonValue &jval)
bool fromJsonValue (float &value, const QJsonValue &jval)
bool fromJsonValue (double &value, const QJsonValue &jval)
bool fromJsonValue (OAIObject &value, const QJsonValue &jval)
bool fromJsonValue (OAIEnum &value, const QJsonValue &jval)
bool fromJsonValue (OAIHttpFileElement &value, const QJsonValue &jval)
template<typename T >
QString toStringValue (const QList< T > &val)
template<typename T >
QString toStringValue (const QSet< T > &val)
template<typename T >
bool fromStringValue (const QList< QString > &inStr, QList< T > &val)
template<typename T >
bool fromStringValue (const QSet< QString > &inStr, QList< T > &val)
template<typename T >
bool fromStringValue (const QMap< QString, QString > &inStr, QMap< QString, T > &val)
template<typename T >
QJsonValue toJsonValue (const QList< T > &val)
template<typename T >
QJsonValue toJsonValue (const QSet< T > &val)
template<typename T >
QJsonValue toJsonValue (const QMap< QString, T > &val)
template<typename T >
bool fromJsonValue (QList< T > &val, const QJsonValue &jval)
template<typename T >
bool fromJsonValue (QSet< T > &val, const QJsonValue &jval)
template<typename T >
bool fromJsonValue (QMap< QString, T > &val, const QJsonValue &jval)
Detailed Description
Intersection Model API No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
The version of the OpenAPI document: 1.0.0
NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
Intersection Model API No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
The version of the OpenAPI document: 1.0.0
NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually. Based on http://www.creativepulse.gr/en/blog/2014/restful-api-requests-using-qt-cpp-for-linux-mac-osx-ms-windows By Alex Stylianos
Intersection Model API No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
The version of the OpenAPI document: 1.0.0
NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually. Representing a Server configuration.
Intersection Model API No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
The version of the OpenAPI document: 1.0.0
NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually. Representing a Server Variable for server URL template substitution.
Enumeration Type Documentation
OAIHttpRequestVarLayout
enum OpenAPI::OAIHttpRequestVarLayout
Enumerator
NOT_SET
ADDRESS
URL_ENCODED
MULTIPART
Definition at line 35 of file OAIHttpRequest.h.
                             {
    NOT_SET,
    ADDRESS,
    URL_ENCODED,
    MULTIPART
};
Function Documentation
fromJsonValue() [1/15]
bool OpenAPI::fromJsonValue (bool & value, const QJsonValue & jval)
Definition at line 376 of file OAIHelpers.cpp.
                                                        {
    bool ok = true;
    if (jval.isBool()) {
        value = jval.toBool();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [2/15]
bool OpenAPI::fromJsonValue (double & value, const QJsonValue & jval)
Definition at line 396 of file OAIHelpers.cpp.
                                                          {
    bool ok = true;
    if (jval.isDouble()) {
        value = jval.toDouble();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [3/15]
bool OpenAPI::fromJsonValue (float & value, const QJsonValue & jval)
Definition at line 386 of file OAIHelpers.cpp.
                                                         {
    bool ok = true;
    if (jval.isDouble()) {
        value = static_cast<float>(jval.toDouble());
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [4/15]
bool OpenAPI::fromJsonValue (OAIEnum & value, const QJsonValue & jval)
Definition at line 417 of file OAIHelpers.cpp.
                                                           {
    value.fromJsonValue(jval);
    return true;
}
References simulate_bsm::value.
fromJsonValue() [5/15]
bool OpenAPI::fromJsonValue (OAIHttpFileElement & value, const QJsonValue & jval)
Definition at line 422 of file OAIHelpers.cpp.
                                                                      {
    return value.fromJsonValue(jval);
}
References simulate_bsm::value.
fromJsonValue() [6/15]
bool OpenAPI::fromJsonValue (OAIObject & value, const QJsonValue & jval)
Definition at line 406 of file OAIHelpers.cpp.
                                                             {
    bool ok = true;
    if (jval.isObject()) {
        value.fromJsonObject(jval.toObject());
        ok = value.isValid();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [7/15]
bool OpenAPI::fromJsonValue (QByteArray & value, const QJsonValue & jval)
Definition at line 334 of file OAIHelpers.cpp.
                                                              {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull() && jval.isString()) {
        value = QByteArray::fromBase64(QByteArray::fromStdString(jval.toString().toStdString()));
        ok = value.size() > 0;
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [8/15]
bool OpenAPI::fromJsonValue (QDate & value, const QJsonValue & jval)
Definition at line 345 of file OAIHelpers.cpp.
                                                         {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull() && jval.isString()) {
        value = QDate::fromString(jval.toString(), Qt::ISODate);
        ok = value.isValid();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [9/15]
bool OpenAPI::fromJsonValue (QDateTime & value, const QJsonValue & jval)
Definition at line 317 of file OAIHelpers.cpp.
                                                             {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull() && jval.isString()) {
        if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isStringSet) {
            value = QDateTime::fromString(jval.toString(), OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatString);
        } else if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isEnumSet) {
            value = QDateTime::fromString(jval.toString(), OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatEnum);
        } else {
            value = QDateTime::fromString(jval.toString(), Qt::ISODate);
        }
        ok = value.isValid();
    } else {
        ok = false;
    }
    return ok;
}
References OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatEnum, OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatString, OpenAPI::OAISerializerSettings::getCustomDateTimeFormat(), OpenAPI::OAISerializerSettings::getInstance(), and simulate_bsm::value.
fromJsonValue() [10/15]
bool OpenAPI::fromJsonValue (qint32 & value, const QJsonValue & jval)
Definition at line 356 of file OAIHelpers.cpp.
                                                          {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull() && !jval.isObject() && !jval.isArray()) {
        value = jval.toInt();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [11/15]
bool OpenAPI::fromJsonValue (qint64 & value, const QJsonValue & jval)
Definition at line 366 of file OAIHelpers.cpp.
                                                          {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull() && !jval.isObject() && !jval.isArray()) {
        value = jval.toVariant().toLongLong();
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
fromJsonValue() [12/15]
template<typename T >
bool OpenAPI::fromJsonValue (QList< T > & val, const QJsonValue & jval)
Definition at line 226 of file OAIHelpers.h.
                                                          {
    bool ok = true;
    if (jval.isArray()) {
        for (const auto jitem : jval.toArray()) {
            T item;
            ok &= fromJsonValue(item, jitem);
            val.push_back(item);
        }
    } else {
        ok = false;
    }
    return ok;
}
References fromJsonValue().
fromJsonValue() [13/15]
template<typename T >
bool OpenAPI::fromJsonValue (QMap< QString, T > & val, const QJsonValue & jval)
Definition at line 256 of file OAIHelpers.h.
                                                                  {
    bool ok = true;
    if (jval.isObject()) {
        auto varmap = jval.toObject().toVariantMap();
        if (varmap.count() > 0) {
            for (const auto &itemkey : varmap.keys()) {
                T itemVal;
                ok &= fromJsonValue(itemVal, QJsonValue::fromVariant(varmap.value(itemkey)));
                val.insert(itemkey, itemVal);
            }
        }
    } else {
        ok = false;
    }
    return ok;
}
References fromJsonValue().
fromJsonValue() [14/15]
template<typename T >
bool OpenAPI::fromJsonValue (QSet< T > & val, const QJsonValue & jval)
Definition at line 241 of file OAIHelpers.h.
                                                         {
    bool ok = true;
    if (jval.isArray()) {
        for (const auto jitem : jval.toArray()) {
            T item;
            ok &= fromJsonValue(item, jitem);
            val.insert(item);
        }
    } else {
        ok = false;
    }
    return ok;
}
References fromJsonValue().
fromJsonValue() [15/15]
bool OpenAPI::fromJsonValue (QString & value, const QJsonValue & jval)
Definition at line 299 of file OAIHelpers.cpp.
                                                           {
    bool ok = true;
    if (!jval.isUndefined() && !jval.isNull()) {
        if (jval.isString()) {
            value = jval.toString();
        } else if (jval.isBool()) {
            value = jval.toBool() ? "true" : "false";
        } else if (jval.isDouble()) {
            value = QString::number(jval.toDouble());
        } else {
            ok = false;
        }
    } else {
        ok = false;
    }
    return ok;
}
References simulate_bsm::value.
Referenced by OpenAPI::OAIIntersection_info::fromJsonObject(), OpenAPI::OAILanelet_info::fromJsonObject(), fromJsonValue(), OpenAPI::OAIDefaultApi::getConflictLaneletsCallback(), OpenAPI::OAIDefaultApi::listDepartureLaneletsCallback(), OpenAPI::OAIDefaultApi::listEntryLaneletsCallback(), and OpenAPI::OAIDefaultApi::listLinkLaneletsCallback().
fromStringValue() [1/15]
template<typename T >
bool OpenAPI::fromStringValue (const QList< QString > & inStr, QList< T > & val)
Definition at line 180 of file OAIHelpers.h.
                                                                 {
    bool ok = (inStr.count() > 0);
    for (const auto &item : inStr) {
        T itemVal;
        ok &= fromStringValue(item, itemVal);
        val.push_back(itemVal);
    }
    return ok;
}
References fromStringValue().
fromStringValue() [2/15]
template<typename T >
bool OpenAPI::fromStringValue (const QMap< QString, QString > & inStr, QMap< QString, T > & val)
Definition at line 202 of file OAIHelpers.h.
                                                                                 {
    bool ok = (inStr.count() > 0);
    for (const auto &itemkey : inStr.keys()) {
        T itemVal;
        ok &= fromStringValue(inStr.value(itemkey), itemVal);
        val.insert(itemkey, itemVal);
    }
    return ok;
}
References fromStringValue().
fromStringValue() [3/15]
template<typename T >
bool OpenAPI::fromStringValue (const QSet< QString > & inStr, QList< T > & val)
Definition at line 191 of file OAIHelpers.h.
                                                                {
    bool ok = (inStr.count() > 0);
    for (const auto &item : inStr) {
        T itemVal;
        ok &= fromStringValue(item, itemVal);
        val.push_back(itemVal);
    }
    return ok;
}
References fromStringValue().
fromStringValue() [4/15]
bool OpenAPI::fromStringValue (const QString & inStr, bool & value)
Definition at line 262 of file OAIHelpers.cpp.
                                                        {
    value = QVariant(inStr).toBool();
    return ((inStr == "true") || (inStr == "false"));
}
References simulate_bsm::value.
fromStringValue() [5/15]
bool OpenAPI::fromStringValue (const QString & inStr, double & value)
Definition at line 273 of file OAIHelpers.cpp.
                                                          {
    bool ok = false;
    value = QVariant(inStr).toDouble(&ok);
    return ok;
}
References simulate_bsm::value.
fromStringValue() [6/15]
bool OpenAPI::fromStringValue (const QString & inStr, float & value)
Definition at line 267 of file OAIHelpers.cpp.
                                                         {
    bool ok = false;
    value = QVariant(inStr).toFloat(&ok);
    return ok;
}
References simulate_bsm::value.
fromStringValue() [7/15]
bool OpenAPI::fromStringValue (const QString & inStr, OAIEnum & value)
Definition at line 290 of file OAIHelpers.cpp.
                                                           {
    value.fromJson(inStr);
    return true;
}
References simulate_bsm::value.
fromStringValue() [8/15]
bool OpenAPI::fromStringValue (const QString & inStr, OAIHttpFileElement & value)
Definition at line 295 of file OAIHelpers.cpp.
                                                                      {
    return value.fromStringValue(inStr);
}
References simulate_bsm::value.
fromStringValue() [9/15]
bool OpenAPI::fromStringValue (const QString & inStr, OAIObject & value)
Definition at line 279 of file OAIHelpers.cpp.
{
    QJsonParseError err;
    QJsonDocument::fromJson(inStr.toUtf8(),&err);
    if (err.error == QJsonParseError::NoError){
        value.fromJson(inStr);
        return true;
    }
    return false;
}
References simulate_bsm::value.
fromStringValue() [10/15]
bool OpenAPI::fromStringValue (const QString & inStr, QByteArray & value)
Definition at line 226 of file OAIHelpers.cpp.
                                                              {
    if (inStr.isEmpty()) {
        return false;
    } else {
        value.clear();
        value.append(inStr.toUtf8());
        return value.count() > 0;
    }
}
References simulate_bsm::value.
fromStringValue() [11/15]
bool OpenAPI::fromStringValue (const QString & inStr, QDate & value)
Definition at line 236 of file OAIHelpers.cpp.
                                                         {
    if (inStr.isEmpty()) {
        return false;
    } else {
        auto date = QDate::fromString(inStr, Qt::DateFormat::ISODate);
        if (date.isValid()) {
            value.setDate(date.year(), date.month(), date.day());
        } else {
            qDebug() << "Date is invalid";
        }
        return date.isValid();
    }
}
References simulate_bsm::value.
fromStringValue() [12/15]
bool OpenAPI::fromStringValue (const QString & inStr, QDateTime & value)
Definition at line 203 of file OAIHelpers.cpp.
                                                             {
    if (inStr.isEmpty()) {
        return false;
    } else {
       QDateTime dateTime;
        if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isStringSet) {
            dateTime = QDateTime::fromString(inStr, OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatString);
        } else if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isEnumSet) {
            dateTime = QDateTime::fromString(inStr, OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatEnum);
        } else {
            dateTime = QDateTime::fromString(inStr, Qt::ISODate);
        }
        if (dateTime.isValid()) {
            value.setDate(dateTime.date());
            value.setTime(dateTime.time());
        } else {
            qDebug() << "DateTime is invalid";
        }
        return dateTime.isValid();
    }
}
References OpenAPI::OAISerializerSettings::getInstance(), and simulate_bsm::value.
fromStringValue() [13/15]
bool OpenAPI::fromStringValue (const QString & inStr, qint32 & value)
Definition at line 250 of file OAIHelpers.cpp.
                                                          {
    bool ok = false;
    value = QVariant(inStr).toInt(&ok);
    return ok;
}
References simulate_bsm::value.
fromStringValue() [14/15]
bool OpenAPI::fromStringValue (const QString & inStr, qint64 & value)
Definition at line 256 of file OAIHelpers.cpp.
                                                          {
    bool ok = false;
    value = QVariant(inStr).toLongLong(&ok);
    return ok;
}
References simulate_bsm::value.
fromStringValue() [15/15]
bool OpenAPI::fromStringValue (const QString & inStr, QString & value)
Definition at line 197 of file OAIHelpers.cpp.
                                                           {
    value.clear();
    value.append(inStr);
    return !inStr.isEmpty();
}
References simulate_bsm::value.
Referenced by fromStringValue(), and OpenAPI::OAIDefaultApiRequest::getConflictLaneletsRequest().
setDateTimeFormat() [1/2]
bool OpenAPI::setDateTimeFormat (const QString & dateTimeFormat)
Definition at line 62 of file OAIHelpers.cpp.
                                                     {
    bool success = false;
    auto dt = QDateTime::fromString(QDateTime::currentDateTime().toString(dateTimeFormat), dateTimeFormat);
    if (dt.isValid()) {
        success = true;
        OAISerializerSettings::setDateTimeFormatString(dateTimeFormat);
    }
    return success;
}
References OpenAPI::OAISerializerSettings::setDateTimeFormatString().
setDateTimeFormat() [2/2]
bool OpenAPI::setDateTimeFormat (const Qt::DateFormat & dateTimeFormat)
Definition at line 72 of file OAIHelpers.cpp.
                                                          {
    bool success = false;
    auto dt = QDateTime::fromString(QDateTime::currentDateTime().toString(dateTimeFormat), dateTimeFormat);
    if (dt.isValid()) {
        success = true;
        OAISerializerSettings::setDateTimeFormatEnum(dateTimeFormat);
    }
    return success;
}
References OpenAPI::OAISerializerSettings::setDateTimeFormatEnum().
toJsonValue() [1/15]
QJsonValue OpenAPI::toJsonValue (const bool & value)
Definition at line 173 of file OAIHelpers.cpp.
                                          {
    return QJsonValue(value);
}
References simulate_bsm::value.
toJsonValue() [2/15]
QJsonValue OpenAPI::toJsonValue (const double & value)
Definition at line 181 of file OAIHelpers.cpp.
                                            {
    return QJsonValue(value);
}
References simulate_bsm::value.
toJsonValue() [3/15]
QJsonValue OpenAPI::toJsonValue (const float & value)
Definition at line 177 of file OAIHelpers.cpp.
                                           {
    return QJsonValue(static_cast<double>(value));
}
References simulate_bsm::value.
toJsonValue() [4/15]
QJsonValue OpenAPI::toJsonValue (const OAIEnum & value)
Definition at line 189 of file OAIHelpers.cpp.
                                             {
    return value.asJsonValue();
}
References simulate_bsm::value.
toJsonValue() [5/15]
QJsonValue OpenAPI::toJsonValue (const OAIHttpFileElement & value)
Definition at line 193 of file OAIHelpers.cpp.
                                                        {
    return value.asJsonValue();
}
References simulate_bsm::value.
toJsonValue() [6/15]
QJsonValue OpenAPI::toJsonValue (const OAIObject & value)
Definition at line 185 of file OAIHelpers.cpp.
                                               {
    return value.asJsonObject();
}
References simulate_bsm::value.
toJsonValue() [7/15]
QJsonValue OpenAPI::toJsonValue (const QByteArray & value)
Definition at line 157 of file OAIHelpers.cpp.
                                                {
    return QJsonValue(QString(value.toBase64()));
}
References simulate_bsm::value.
toJsonValue() [8/15]
QJsonValue OpenAPI::toJsonValue (const QDate & value)
Definition at line 161 of file OAIHelpers.cpp.
                                           {
    return QJsonValue(value.toString(Qt::ISODate));
}
References simulate_bsm::value.
toJsonValue() [9/15]
QJsonValue OpenAPI::toJsonValue (const QDateTime & value)
Definition at line 144 of file OAIHelpers.cpp.
                                               {
    if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isStringSet) {
        return QJsonValue(value.toString(OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatString));
    }
    if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isEnumSet) {
        return QJsonValue(value.toString(OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatEnum));
    }
    // ISO 8601
    return QJsonValue(value.toString(Qt::ISODate));
}
References OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatEnum, OpenAPI::OAISerializerSettings::CustomDateTimeFormat::formatString, OpenAPI::OAISerializerSettings::getCustomDateTimeFormat(), OpenAPI::OAISerializerSettings::getInstance(), and simulate_bsm::value.
toJsonValue() [10/15]
QJsonValue OpenAPI::toJsonValue (const qint32 & value)
Definition at line 165 of file OAIHelpers.cpp.
                                            {
    return QJsonValue(value);
}
References simulate_bsm::value.
toJsonValue() [11/15]
QJsonValue OpenAPI::toJsonValue (const qint64 & value)
Definition at line 169 of file OAIHelpers.cpp.
                                            {
    return QJsonValue(value);
}
References simulate_bsm::value.
toJsonValue() [12/15]
template<typename T >
QJsonValue OpenAPI::toJsonValue (const QList< T > & val)
Definition at line 140 of file OAIHelpers.h.
                                            {
    QJsonArray jArray;
    for (const auto &item : val) {
        jArray.append(toJsonValue(item));
    }
    return jArray;
}
References toJsonValue().
toJsonValue() [13/15]
template<typename T >
QJsonValue OpenAPI::toJsonValue (const QMap< QString, T > & val)
Definition at line 158 of file OAIHelpers.h.
                                                    {
    QJsonObject jObject;
    for (const auto &itemkey : val.keys()) {
        jObject.insert(itemkey, toJsonValue(val.value(itemkey)));
    }
    return jObject;
}
References toJsonValue().
toJsonValue() [14/15]
template<typename T >
QJsonValue OpenAPI::toJsonValue (const QSet< T > & val)
Definition at line 149 of file OAIHelpers.h.
                                           {
    QJsonArray jArray;
    for (const auto &item : val) {
        jArray.append(toJsonValue(item));
    }
    return jArray;
}
References toJsonValue().
toJsonValue() [15/15]
QJsonValue OpenAPI::toJsonValue (const QString & value)
Definition at line 140 of file OAIHelpers.cpp.
                                             {
    return QJsonValue(value);
}
References simulate_bsm::value.
Referenced by OpenAPI::OAIIntersection_info::asJsonObject(), OpenAPI::OAILanelet_info::asJsonObject(), OpenAPI::OAIDefaultApiRequest::getConflictLaneletsError(), OpenAPI::OAIDefaultApiRequest::getConflictLaneletsResponse(), OpenAPI::OAIDefaultApiRequest::getIntersectionInfoError(), OpenAPI::OAIDefaultApiRequest::getIntersectionInfoResponse(), OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsError(), OpenAPI::OAIDefaultApiRequest::listDepartureLaneletsResponse(), OpenAPI::OAIDefaultApiRequest::listEntryLaneletsError(), OpenAPI::OAIDefaultApiRequest::listEntryLaneletsResponse(), OpenAPI::OAIDefaultApiRequest::listLinkLaneletsError(), OpenAPI::OAIDefaultApiRequest::listLinkLaneletsResponse(), and toJsonValue().
toStringValue() [1/14]
QString OpenAPI::toStringValue (const bool & value)
Definition at line 116 of file OAIHelpers.cpp.
                                         {
    return QString(value ? "true" : "false");
}
References simulate_bsm::value.
toStringValue() [2/14]
QString OpenAPI::toStringValue (const double & value)
Definition at line 124 of file OAIHelpers.cpp.
                                           {
    return QString::number(value);
}
References simulate_bsm::value.
toStringValue() [3/14]
QString OpenAPI::toStringValue (const float & value)
Definition at line 120 of file OAIHelpers.cpp.
                                          {
    return QString::number(static_cast<double>(value));
}
References simulate_bsm::value.
toStringValue() [4/14]
QString OpenAPI::toStringValue (const OAIEnum & value)
Definition at line 132 of file OAIHelpers.cpp.
                                            {
    return value.asJson();
}
References simulate_bsm::value.
toStringValue() [5/14]
QString OpenAPI::toStringValue (const OAIHttpFileElement & value)
Definition at line 136 of file OAIHelpers.cpp.
                                                       {
    return value.asJson();
}
References simulate_bsm::value.
toStringValue() [6/14]
QString OpenAPI::toStringValue (const OAIObject & value)
Definition at line 128 of file OAIHelpers.cpp.
                                              {
    return value.asJson();
}
References simulate_bsm::value.
toStringValue() [7/14]
QString OpenAPI::toStringValue (const QByteArray & value)
Definition at line 99 of file OAIHelpers.cpp.
                                               {
    return QString(value);
}
References simulate_bsm::value.
toStringValue() [8/14]
QString OpenAPI::toStringValue (const QDate & value)
Definition at line 103 of file OAIHelpers.cpp.
                                          {
    // ISO 8601
    return value.toString(Qt::DateFormat::ISODate);
}
References simulate_bsm::value.
toStringValue() [9/14]
QString OpenAPI::toStringValue (const QDateTime & value)
Definition at line 86 of file OAIHelpers.cpp.
                                              {
    if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isStringSet) {
        return value.toString(OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatString);
    }
    if (OAISerializerSettings::getInstance()->getCustomDateTimeFormat().isEnumSet) {
        return value.toString(OAISerializerSettings::getInstance()->getCustomDateTimeFormat().formatEnum);
    }
    // ISO 8601
    return value.toString(Qt::ISODate);
}
References OpenAPI::OAISerializerSettings::getInstance(), and simulate_bsm::value.
toStringValue() [10/14]
QString OpenAPI::toStringValue (const qint32 & value)
Definition at line 108 of file OAIHelpers.cpp.
                                           {
    return QString::number(value);
}
References simulate_bsm::value.
toStringValue() [11/14]
QString OpenAPI::toStringValue (const qint64 & value)
Definition at line 112 of file OAIHelpers.cpp.
                                           {
    return QString::number(value);
}
References simulate_bsm::value.
toStringValue() [12/14]
template<typename T >
QString OpenAPI::toStringValue (const QList< T > & val)
Definition at line 103 of file OAIHelpers.h.
                                           {
    QString strArray;
    for (const auto &item : val) {
        strArray.append(toStringValue(item) + ",");
    }
    if (val.count() > 0) {
        strArray.chop(1);
    }
    return strArray;
}
References toStringValue().
toStringValue() [13/14]
template<typename T >
QString OpenAPI::toStringValue (const QSet< T > & val)
Definition at line 115 of file OAIHelpers.h.
                                          {
    QString strArray;
    for (const auto &item : val) {
        strArray.append(toStringValue(item) + ",");
    }
    if (val.count() > 0) {
        strArray.chop(1);
    }
    return strArray;
}
References toStringValue().
toStringValue() [14/14]
QString OpenAPI::toStringValue (const QString & value)
Definition at line 82 of file OAIHelpers.cpp.
                                            {
    return value;
}
References simulate_bsm::value.
Referenced by OpenAPI::OAIDefaultApi::getConflictLanelets(), and toStringValue().