signal_phase_and_timing::spat Struct Reference
#include <spat.h>
Public Member Functions
std::string toJson () const
Serialize SPaT object to rapidjson::Value for writing as JSON string.
void fromJson (const std::string &json)
Deserialize SPaT JSON into SPaT object.
void update (ntcip::ntcip_1202_ext &ntcip_data, bool use_ntcip_timestamp)
Update spat object data using ntcip_1202_ext data received via UDP socket. Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information.
void initialize_intersection (const std::string &intersection_name, const int intersection_id, const std::unordered_map< int, int > &phase_number_to_signal_group)
Method to initialize intersection information not provided in the ntcip SPaT UDP message but necessary for the J2735 SPaT message. This method must be executed prior to using the update method.
void set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Method to set SPaT timestamp based on NTCIP message timestamp. The NTCIP message timestamp consists of a seconds_of_day and a milliseconds of second field. This method will get the current day from system time and then apply seconds and milliseconds informat as a offset for the current day.
void set_timestamp_local ()
Method to set SPaT timestamp based on system time.
void update_intersection_state (ntcip::ntcip_1202_ext &ntcip_data)
Method to update the front entry in the intersections list of intersection_state(s) with the provided NTCIP SPaT data.
bool operator== (const spat &other) const
Equals operator to asses whether two objects contain equivalent data.
bool operator!= (const spat &other) const
Returns the inverse of equals operator.
Public Attributes
u_int32_t timestamp = 0
Timestamp in minutes of the UTC year (see J2735 SPaT message documentation for reference).
std::string name
Descriptive name for this collection.
std::list< intersection_state > intersections
Sets of SPaT data (one per intersection).
std::unordered_map< int, int > phase_to_signal_group
Map of phase number(NTCIP) to signal group(J2735).
Detailed Description
Definition at line 18 of file spat.h.
Member Function Documentation
fromJson()
void signal_phase_and_timing::spat::fromJson (const std::string & json)
Deserialize SPaT JSON into SPaT object.
Parameters
val SPaT JSON.
Definition at line 33 of file spat.cpp.
                                               {
        rapidjson::Document doc;
        doc.Parse(json);
        if (doc.HasParseError()) {
            throw signal_phase_and_timing_exception("SPaT message JSON is misformatted. JSON parsing failed!");
        }
        if (doc.HasMember("time_stamp") && doc.FindMember("time_stamp")->value.IsUint64()) {
            timestamp = (uint32_t) doc["time_stamp"].GetUint64(); // OPTIONAL in J2735 SPaT definition
        }
        if (doc.FindMember("name")->value.IsString()) {
            name = doc["name"].GetString(); // OPTIONAL see J2735 SPaT definition
        }
        if (doc.FindMember("intersections")->value.IsArray()) {
            // REQUIRED see J2735 SPaT definition
            // Clear intersection state list in case it is populated.
            intersections.clear();
            for (const auto &intersection : doc["intersections"].GetArray()){
                intersection_state cur_state;
                cur_state.fromJson(intersection);
                intersections.push_back(cur_state);
            }
        }
        else {
            throw signal_phase_and_timing_exception("SPaT message is missing required intersections property!");
        }
            
        
    }
References signal_phase_and_timing::intersection_state::fromJson(), intersections, name, and timestamp.
initialize_intersection()
void signal_phase_and_timing::spat::initialize_intersection (const std::string & intersection_name, const int intersection_id, const std::unordered_map< int, int > & phase_number_to_signal_group)
Method to initialize intersection information not provided in the ntcip SPaT UDP message but necessary for the J2735 SPaT message. This method must be executed prior to using the update method.
Parameters
intersection_name name of intersection
intersection_id J2735 intersection ID
phase_number_to_signal_group a map of phase numbers (NTCIP) to signal groups (J2735)
Definition at line 79 of file spat.cpp.
                                                                                                                                                                     {
        if (!intersections.empty()) {
            intersections.clear();
        }
        intersection_state cur_state;
        cur_state.name = intersection_name;
        cur_state.id = (uint16_t) intersection_id;
        phase_to_signal_group = _phase_number_to_signal_group;
        cur_state.initialize_movement_states(phase_to_signal_group);
        intersections.push_back(cur_state);
    }
References signal_phase_and_timing::intersection_state::id, signal_phase_and_timing::intersection_state::initialize_movement_states(), intersections, signal_phase_and_timing::intersection_state::name, and phase_to_signal_group.
operator!=()
bool signal_phase_and_timing::spat::operator!= (const spat & other) const
Returns the inverse of equals operator.
Parameters
other second object to compare current object with.
Returns
true if both objects do not contain equivalent data.
false if both objects do contain equivalent data.
Definition at line 131 of file spat.cpp.
                                                {
        return !operator==(other);
    }
References operator==().
operator==()
bool signal_phase_and_timing::spat::operator== (const spat & other) const
Equals operator to asses whether two objects contain equivalent data.
Parameters
compare second object to compare current object with.
Returns
true if both object contain equivalent data.
false if not.
Definition at line 127 of file spat.cpp.
                                                {
        return timestamp == other.timestamp && name == other.name && intersections == other.intersections;
    }
References intersections, name, and timestamp.
Referenced by operator!=().
set_timestamp_local()
void signal_phase_and_timing::spat::set_timestamp_local ()
Method to set SPaT timestamp based on system time.
Definition at line 102 of file spat.cpp.
                                   {
        if (!intersections.empty()) {
            intersection_state &intersection = intersections.front();
            intersection.set_timestamp_local();
            timestamp = intersection.moy;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate timestamp information!");
        }
    }
References intersections, and timestamp.
Referenced by update().
set_timestamp_ntcip()
void signal_phase_and_timing::spat::set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Method to set SPaT timestamp based on NTCIP message timestamp. The NTCIP message timestamp consists of a seconds_of_day and a milliseconds of second field. This method will get the current day from system time and then apply seconds and milliseconds informat as a offset for the current day.
Parameters
second_of_day NTCIP message timestamp information (seconds of the current UTC day).
millisecond_of_second NTCIP message timestamp information (millisecond of the current second).
Definition at line 91 of file spat.cpp.
                                                                                                      {
        if (!intersections.empty()) {
            intersection_state &intersection = intersections.front();
            intersection.set_timestamp_ntcip(second_of_day, millisecond_of_second);
            timestamp = intersection.moy;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate timestamp information!");
        }
    }
References intersections, and timestamp.
Referenced by update().
toJson()
std::string signal_phase_and_timing::spat::toJson () const
Serialize SPaT object to rapidjson::Value for writing as JSON string.
Returns
rapidjson::Value serialize SPaT object
Definition at line 5 of file spat.cpp.
                                 {
        rapidjson::Document doc;
        auto allocator = doc.GetAllocator();
        // Create SPaT JSON value
        rapidjson::Value spat(rapidjson::kObjectType);
        // Populate SPat JSON
        spat.AddMember("time_stamp", timestamp, allocator);
        spat.AddMember("name", name, allocator);
        if (!intersections.empty()) {
            rapidjson::Value list(rapidjson::kArrayType);
            for (const auto &intersection : intersections) {
                list.PushBack(intersection.toJson(allocator), allocator);
            }
            spat.AddMember("intersections", list, allocator);
        }else {
            throw signal_phase_and_timing_exception("SPaT message is missing required intersections property!");
        }
        rapidjson::StringBuffer buffer;
        try {
            rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
            spat.Accept(writer);
        }
        catch(const std::exception &e) {
            throw signal_phase_and_timing_exception(e.what());
        }
        return buffer.GetString();
    }
References intersections, name, and timestamp.
update()
void signal_phase_and_timing::spat::update (ntcip::ntcip_1202_ext & ntcip_data, bool use_ntcip_timestamp)
Update spat object data using ntcip_1202_ext data received via UDP socket. Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information.
Parameters
ntcip_data bytes from UDP socket, read into a struct
use_ntcip_timestamp Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information. If true will use message timestamp.
Definition at line 63 of file spat.cpp.
                                                                                {
        if (phase_to_signal_group.empty() || intersections.front().name.empty() || intersections.front().id == 0) {
            throw signal_phase_and_timing_exception("Before updating SPAT with NTCIP information spat::initialize() must be called! See README documentation!");
        }
        if (use_ntcip_timestamp) {
            set_timestamp_ntcip(ntcip_data.get_timestamp_seconds_of_day(), ntcip_data.spat_timestamp_msec);
        }
        else {
            set_timestamp_local();
        }
        update_intersection_state(ntcip_data);
        
        
        
    }
References ntcip::ntcip_1202_ext::get_timestamp_seconds_of_day(), intersections, phase_to_signal_group, set_timestamp_local(), set_timestamp_ntcip(), ntcip::ntcip_1202_ext::spat_timestamp_msec, and update_intersection_state().
update_intersection_state()
void signal_phase_and_timing::spat::update_intersection_state (ntcip::ntcip_1202_ext & ntcip_data)
Method to update the front entry in the intersections list of intersection_state(s) with the provided NTCIP SPaT data.
Parameters
ntcip_data
Definition at line 113 of file spat.cpp.
                                                                          {
        if (!intersections.empty()) {
            intersection_state &intersection = intersections.front();
            intersection.update_movements(ntcip_data, phase_to_signal_group);
            // Update Intersection Status
            intersection.status = ntcip_data.spat_intersection_status;
            // From V2X-Hub TODO: Investigate
            intersection.revision = 1;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate status information!");
        }
    }
References intersections, phase_to_signal_group, and ntcip::ntcip_1202_ext::spat_intersection_status.
Referenced by update().
Member Data Documentation
intersections
std::list<intersection_state> signal_phase_and_timing::spat::intersections
Sets of SPaT data (one per intersection).
Definition at line 30 of file spat.h.
Referenced by fromJson(), initialize_intersection(), operator==(), set_timestamp_local(), set_timestamp_ntcip(), toJson(), update(), and update_intersection_state().
name
std::string signal_phase_and_timing::spat::name
Descriptive name for this collection.
Definition at line 26 of file spat.h.
Referenced by fromJson(), operator==(), and toJson().
phase_to_signal_group
std::unordered_map<int,int> signal_phase_and_timing::spat::phase_to_signal_group
Map of phase number(NTCIP) to signal group(J2735).
Definition at line 35 of file spat.h.
Referenced by initialize_intersection(), update(), and update_intersection_state().
timestamp
u_int32_t signal_phase_and_timing::spat::timestamp = 0
Timestamp in minutes of the UTC year (see J2735 SPaT message documentation for reference).
Definition at line 22 of file spat.h.
Referenced by fromJson(), operator==(), set_timestamp_local(), set_timestamp_ntcip(), and toJson().
The documentation for this struct was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/spat.h
streets_utils/streets_signal_phase_and_timing/src/models/spat.cpp